- src/componentes/PrestacaoDeContas/DetalheDasPrestacoes/TabelaValoresPendentesPorAcao/index.js
- src/services/TabelaValoresPendentesPorAcao.service.js
Devido a mudanças nas regras de negócio que passaram a considerar
na conciliação transações não conciliadas mesmo de periodos
anteriores, a action tabela-valores-pendentes passa a ser
chamada no detalhe da prestação e o período não precisa mais ser
passado como parâmetro.
Foi também corrigido um erro na exibição da coluna de receitas
conciliadas.
> feat(17138): Altera a consulta da tabela de conciliação

- src/paginas/Dashboard/index.js
Esse PR:
- Altera o painel de ações para chamar o endpoint que retorna apenas os períodos até o dia de hoje.
> feat(17158): Não exibir períodos futuros no painel de ações

- src/componentes/Receitas/Formularios/index.js
- src/componentes/Receitas/Schemas/index.js
- src/componentes/SidebarLeft/index.js
- src/paginas/Receitas/EdicaoReceita/index.js
- src/paginas/Receitas/ListaDeReceitas/index.js
- src/utils/Modais.js
Esse PR:
- Remove do menu a opção de cadastrar créditos;
- Renomeia o botão "Cancelar" no form para "Voltar";
- Altera o termo "Receita" para "Crédito" em vários locais.
> feat(17960): Remove do menu a opção cadastro de créditos

- package.json
- Correção no build do front.
Hoje dia 06/07/2020 houve uma atualização da biblioteca react-bootstrap para a [versão 1.1.0](https://www.npmjs.com/package/react-bootstrap/v/1.1.0) e que acabou causando problema no build da aplicação, como mostrado abaixo:
para mais detalhes do erro clique [aqui](http://jenkins.sme.prefeitura.sp.gov.br/job/SME-PTRF-FrontEnd/job/develop/165/console). É preciso ter acesso ao jenkins para visualizar.
Para corrigi o problema eu fixei a versão da biblioteca na última que está funcionando na aplicação, [versão 1.0.1](https://www.npmjs.com/package/react-bootstrap/v/1.0.1).
Temos que verificar quando a biblioteca irá corrigi o problema e então atualizar para a mais recente.
> Correção no build do front

- src/componentes/escolas/PrestacaoDeContas/index.js
- src/services/escolas/Associacao.service.js
Esse PR:
- Altera a prestação de contas para permitir apenas  a seleção de períodos que já tem prestação de contas para a Associação ou o próximo período sem prestação feita.
> feat(19957): Prestações de contas apenas até o próximo período

- src/services/dres/Associacoes.service.js
Enquanto a parte de definição de visões no login não está pronta, o uuid
da dre está sendo passado para a API hardcoded.
> fix(20311): Alterar uuid de teste para a DRE Butantan em Homolog

- src/componentes/Globais/Dashborard/DashboardCard.js
- src/componentes/Globais/Dashborard/DashboardCardInfoConta.js
- src/componentes/Globais/Dashborard/dashboard.scss
Esse PR:
Altera os paineis de resumo financeiro de associações para exibir saldos negativos em vermelho.
> feat(24720):Resumo Financeiro Saldos negativos em vermelho

- src/componentes/Globais/Dashborard/dashboard.scss
Passa cor darkred para a sua representação hexadecimal para manter o
padrão.
> refactor(24720): Cor para hexadecimal em CSS

- README.md
- package.json
- src/services/escolas/RelacaoDeBens.service.js
O download de relação de bens, prévia e final, não estava passando as
informações de autenticação e por isso o download falhava.
> fix(28206): Corrige falha autenticação ao baixar relação de bens

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
Esse PR:
- Altera o comportamento do botão voltar no formulário de edição de
despesas para só pedir confirmação se algum campo houver sido alterado.
> feat(23508): Edição despesas confirma voltar apenas se há mudanças

- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/escolas/Receitas/ModalSelecionaRepasse.js
- src/services/escolas/Receitas.service.js
* Consultar endpoint para pegar lista de repasses: 
*  Exibir modal de seleção de repasses:
*  Limpar tipo de receita quando modal for fechado sem selecionar repasse:
*  Preencher campos com valores do repasse e torna-los apenas leitura: 
*  Passar uuid do repasse no payload de gravação: 
*  Refatorar código removendo todos os controles feitos para a forma de controle anterior.
> Features/29927 selecao repasse.

- src/componentes/dres/Dashboard/index.js
Esse PR:
Altera a a seleção de período do acompanhamento de Prestação de Contas
da DRE para trazer como default o período anterior ao período corrente.
História: [AB#29297](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/29297)
> feat(29297): Período anterior default no acompanhamento PC

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/utils/Modais.js
Esse PR altera o lançamento de despesas que passa a tratar o lançamento de despesas anteriores ao período inicial da associação.
História [AB#35135](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/35135)
> feat(35135): Permite despesas anteriores ao período inicial

- src/componentes/Globais/Dashborard/index.js
- src/services/escolas/PrestacaoDeContas.service.js
Esse PR altera a consulta de Resumo de Recursos que passa a chamar novo endpoint que retorna os períodos a partir do período de implantação da associação até o período em andamento.
História [AB#39524](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39524)
> feat(39524): Resumo de recursos apenas períodos a partir da implantação

- src/componentes/Globais/Dashborard/DashboardCard.js
- src/componentes/Globais/Dashborard/DashboardCardInfoConta.js
- src/componentes/Globais/Dashborard/index.js
Esse PR:
- Corrige a exibição do destaque (cor e ponto de exclamação) nos valores de Despesa e Outras receitas em períodos finalizados, cuja PC fora aprovada pela DRE
Historia: [AB#37949](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/37949)
> fix(37949): Bug resumo dos recursos

- src/componentes/Globais/Dashborard/index.js
- src/services/escolas/PrestacaoDeContas.service.js
- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR:
- Altera a cor do destaque e a cor do ícone para os valores de Outras receitas e Despesas quando o período for em andamento.
História: [AB#29418](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/29418)
> feat(29418): Alterar cor do destaque (em andamento)

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroSaidaForm.js
- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR:
- Corrige a validação do campo Número do documento no cadastro de despesa de um recurso externo que agora leva em consideração se o campo deve ou não ser digitado e se aceita somente números, parametrizados no admin do sistema
História: [AB#42457](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42457)
> fix(42457): [Associação] Cadastro de despesa a partir de recurso externo não segue a configuração do cadastro de despesa comum

- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/escolas/Receitas/ModalDeletarReceita.js
- src/services/escolas/Receitas.service.js
- src/utils/Modais.js
Esse PR: 
- Exclui a despesa vinculada ao crédito do recurso externo, caso exista, e no momento de exclusão do crédito o usuário é avisado
História: [AB#42271](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42271)
> feat(42271): Remove despesa vinculada ao crédito de recurso externo

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroSaidaForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/ModalValorReceitaDespesaDiferente.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/rotas/index.js
Esse PR:
- Implementa o preenchimento automático do valor de uma despesa vinculada
- Implementa a validação do valor da despesa maior que zero
- Permite valores diferentes da entrada, mas solicita uma confirmação ao gravar
- Remove mensagem de "Crédito salvo com sucesso" ao cadastrar/editar saída 
- Exibe mensagem quando for a gravação de um crédito NÃO recurso externo 
Historia: [AB#42269](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42269)
> feat(42269): [Associação] Créditos de recursos externos: Melhorias no formulário de saída do recurso externo

- src/componentes/escolas/Receitas/Formularios/index.js
Esse PR:
- Resolve a passagem de parâmetro para o cadastro de saída
- Anteriormente ao clicar em cadastrar saída, não estava enviando o uuid da receita
História: [AB#42269](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42269)
> feat(42269): [Associação] Créditos de recursos externos: Melhorias no formulário de saída do recurso externo - Parte 2

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
Esse PR:
- Altera o cadastro de despesas para não permitir a escolha de uma ação do tipo recurso externo
História: [AB#42275](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42275)
> feat(42275): Gastos da Escola. Não permitir usar ações do tipo recursos externos

- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR remove a mensagem de obrigatoriedade de nome quando trata-se de um membro do tipo aluno.
[AB#39282](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39282)
> feat(39282): Altera validação código eol membro

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
- src/componentes/dres/PrestacaoDeContas/ModalErroPrestacaoDeContasPosterior.js
Esse PR:
- Implementa tratamento e exibição de mensagem amigável para usuário quando da reabertura ou conclusão de uma prestação de contas que tenha prestações de contas posteriores
História: [AB#31424](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/31424)
> feat(31424): [DRE] Não permitir reabrir ou devolver para ajustes PC com PC´s posteriores

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroSaidaForm.js
- src/componentes/escolas/Despesas/ListaDeDespesas/index.jsx
feat(42704): Exibe loading antes do retorno da API
Esse PR:
- Adiciona loading ao esperar retorno da API na listagem de despesas,
- Adiciona loading ao esperar o retorno da API na edição de despesa.
História: [AB#42704](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42704)
> feat(42704) Exibe loading antes do retorno da API

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/FormRecebimentoPelaDiretoria.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
feat(29936): Remove seta do campo status
Esse PR:
- Adiciona classe css para remover dropdown do campo,
- Adiciona a nova classe ao campo de status.
História: [AB#29936](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/29936)
> feat(29936) Remove seta do campo status

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
- src/utils/ValidacoesAdicionaisFormularios.js
feat(43985): Permite cadastro CNPJ zerado
Esse PR:
- Altera a interface para permitir cadastro de um CNPJ zerado;
- Altera regra de campos obrigatórios quando for um CNPJ zerado;
História: [AB#43985](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43985)
> feat(43985) Permite cadastro CNPJ zerado

- src/componentes/Globais/GestaoDePerfis/GestaoDePerfisForm.js
- src/componentes/Globais/GestaoDePerfis/GestaoDePerfisFormFormik.js
Esse PR altera o Perfil Acessos quando na visão UE:
[X] Não deve ser exibida a lista de Unidades vinculadas
[X] Trazer a opção UE selecionada.
[X] Ao salvar o usuário o vínculo ja deve ser feito com a UE logada.
[X] O seletor de visões deve ser apenas leitura.
[X] Botão "Desvincular e Deletar usuário" caso o usuário tenha apenas a visão UE, e esteja vinculado apenas à unidade logada
[X] Botão "Desvincular usuário" caso o usuário tenha outras visões ou outros vínculos
História: [AB#42226](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42226)
> feat(42226):  Altera Perfil Acessos na visão UE

- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoApuracao/index.js
Esse PR ajusta a página de apuração do relatório consolidado DRE para alterar o status do relatório
no momento em que se pede a geração do relatório, para que tenha inicio o ciclo de verificação 
de status que atualiza o caption do botão de geração.
História [AB#31426](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/31426)
> feat(31426): Relatório consolidado DRE - Assíncrono - Parte 2

- src/componentes/escolas/Associacao/DadosDaAssociacao/index.js
- src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/index.js
Esse PR alterar a página de Dados da Associação para não exibir os botões de cancelar e salvar quando o usuário tiver perfil de apenas visualização.
Corrige bug: [AB#42727](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42727)
> fix(42727): Oculta botões salvar e cancelar quando apenas visualização

- src/componentes/Globais/CentralDeNotificacoes/index.js
- src/services/Notificacoes.service.js
fix(32818) Soluciona marcação não sendo aplicada
Esse PR:
- Atualiza o estado da notificação, após seleção de check box
História: [AB#32818](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/32818)
> fix(32818) Soluciona marcação não sendo aplicada

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/TabsArquivosDeReferencia.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/componentes/escolas/GeracaoDaAta/ModalEditarAta.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
- src/services/escolas/PrestacaoDeContas.service.js
Esse PR:
- Altera ata de PC
- Agora o Presidente e o Secretário podem ser selecionados pelo retorno da API de membros da Associação
- Caso não queira escolher um membro, continua sendo possível digitar os dados
- Faz a rediagramação dos dados para se adequar
História: [AB#42261](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42261)
> feat(42261): Atas de prestação de contas: Presidente e secretário: Selecionar membros da associação

- src/componentes/Globais/DatePickerField/index.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/componentes/escolas/Receitas/Formularios/index.js
Esse PR:
Inclui validações de data maiores que a data atual, fazendo validações pelo componente Datepicker e nas validações do Form
- Em lançamento de créditos
- Em lancamento de despesas (data do documento e data da transação)
- Em conciliação bancária data do extrato
Hisrória: [AB#46263](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46263)
> feat(46263): Não aceitar lançamentos com datas futuras

- src/componentes/Globais/Dashborard/DashboardCard.js
- src/componentes/Globais/Dashborard/DashboardCardInfoConta.js
- src/componentes/Globais/Dashborard/index.js
Esse PR: 
-  Altera condições de exibição de ícones resumo dos recursos e situação financeira
História: [AB#46268](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46268)
> feat(46268): Resumo de recursos: ícones exclamação sendo exibidos em períodos fechados para lançamentos

- src/componentes/dres/Diretoria/DadosDaDiretoria/index.js
Esse PR:
- Limpa campo nome do diretor quando não existe codigo RF
História: [AB#42277](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42277)
> fix(42277): Dados da Diretoria: Nome do diretor não é apagado ao se apagar o RF

- src/componentes/Globais/SidebarLeft/getUrls.js
- src/services/visoes.service.js
Esse PR:
- Altera os menus de UE e SME para exigirem para acesso à Gestão de Perfis apenas as permissões das respectivas visões;
- Alterar o algoritmo de verificação de permissões que exigia que o usuário tivesse todas as permissões da lista passada e não apenas uma delas.
Solução para o bug [AB#47932](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/47932)
> fix(47932): Corrige exibição da Gestão de Perfis nos menus das visões UE e SME

- src/componentes/Globais/ArquivosDeCarga/index.js
fix(48162) Opção "Dados dos perfis"
Esse PR:
- Soluciona problema da opção "Dados dos perfis" não ser apresentada
História: [AB#48162](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/48162)
> fix(48162) Opção "Dados dos perfis"

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/BotaoSalvarRodape.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
Esse PR:
- Replica botão salvar no rodapé para PC em Análise
História: [AB#43915](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43915)
> feat(43915): Acompanhamento PC: Em análise: Parte 9 - Replicar botão salvar do topo na base da página

- src/componentes/escolas/Receitas/Formularios/index.js
- src/paginas/escolas/Receitas/CadastroReceita/index.js
Esse PR Altera o lançamento de crédito para:
- Não exibir o botão deletar na edição de créditos de tipo repasse.
- Pedir confirmação ao incluir crédito de tipo repasse.
- Altera título do formulário de crédito para "Cadastro de Crédito".
História: [AB#47838](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/47838)
> feat(47838): Altera a edição de créditos tipo repasse

- src/assets/css/styles.scss
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosLancamentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
Esse PR:
- Remove imagem da mensagem de Não existem ajustes para serem exibidos
- Padroniza tamanho dos textos em 18px
História: [AB#44206](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/44206)
> feat(44206): Consulta de análises da DRE: Detalhamento da análise

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
Esse PR:
-  Resolve bug na gravação de conciliação
Bug: [AB#50478](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50478)
> hotfix(50478): Conciliação bancária: a data e valor do saldo só são gravados quando há um comprovante selecionado

- src/componentes/dres/RegularidadeAssociacoes/AnalisesRegularidade/NomeAssociacaoBotaoVoltar.js
- src/componentes/dres/RegularidadeAssociacoes/AnalisesRegularidade/RegularidadeAssociacaoNoAno/MotivoNaoRegularidade.js
- src/componentes/dres/RegularidadeAssociacoes/AnalisesRegularidade/RegularidadeAssociacaoNoAno/index.js
- src/componentes/dres/RegularidadeAssociacoes/AnalisesRegularidade/index.js
Esse PR:
- Corrige a exibição de análise de regularidade na aba histórico para apenas exibir o campo motivo de não regularidade sem permitir edição.
- Corrige a exibição do nome da Associação para não exibir "undefined" enquanto carrega os dados.
História: [AB#40174](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/40174)
> feat(40174): Altera exibição motivo não regularidade se apenas leitura

- src/componentes/Globais/ModalBootstrap/index.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/escolas/ValoresReprogramados/index.js
- src/utils/Modais.js
feat(52005): Parametrização aplicações aceitas pela ação
Esse PR:
- Refatora formulario de receitas, agora só é permitido uma aplicação que o tipo de receita e a ação permitem
- Refatora formulario de despesas, agora é exibido uma mensagem caso a aplicação selecionada não seja compativel com a ação
- Refatora formulario de valores reprogramados, agora só é permitido uma aplicação que a ação permita
História: [AB#52005](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52005)
> feat(52005): Parametrização aplicações aceitas pela ação

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
Esse PR:
- Altera o formulário de saldo bancário na conciliação para exibir a data e hora da última atualização do comprovante de saldo bancário.
História: AB#56679
> feat(56679): Altera conciliação para exibir data de atualização do comprovante

- src/componentes/dres/Diretoria/DadosDaDiretoria/index.js
- src/utils/ValidacoesAdicionaisFormularios.js
feat(52316): Não obrigar informação do CNPJ
Esse PR:
- Remove CNPJ como campo obrigatório
- Cria condição que só libera o botão de salvar se algum campo estiver preenchido
História: [AB#52316](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52316)
> feat(52316): Não obrigar informação do CNPJ

- src/componentes/escolas/GeracaoDaAta/ModalDevolucaoAoTesouro.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/DevolucoesAoTesouro/InformacoesDevolucaoAoTesouro.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TopoComBotoes/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
Esse PR altera o formulário de devolução ao tesouro na ata de retificação para:
- Não ser possível adicionar devoluções ao tesouro.
- Não ser possível editar uma devolução ao tesouro.
- Não ser possível excluir uma devolução ao tesouro.
- Ser possível atualizar a data de realização de uma devolução ao tesouro.
- Remover área de busca por despesas (botão "filtrar").
- Atender novo layout proposto no protótipo. 
- Exibir o botão "Devoluções ao Tesouro" na ata de retificação apenas se houver devoluções ao tesouro. 
História: [AB#55934](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55934)
> feat(55934): Altera form devolução ao tesouro na ata

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TopoComBotoes/index.js
Esse PR remove o botão de copiar na ata em tela.
História: [AB#52133](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52133)
> feat(52133): Remove da ata função copiar

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/FormularioEditaAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TextoDinamicoSuperior/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
Esse PR:
- Altera textos da ata para variarem conforme seu tipo, apresentação ou retificação
- inclui o campo retificações no formulário quando for uma ata de retificação
História: [AB#55188](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55188)
> feat(55188): Altera ata de retificação texto e formulário

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaValoresPendentesPorAcao/index.js
Esse PR:
- Altera o quadro de saldos de conciliação para exibir os saldos conciliados e a conciliar na linha de saldo anterior.
História: [AB#56099](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/56099)
> feat(56099): Altera quadro de saldos de conciliação

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
Remove o bloco de devoluções ao tesouro da ata de retificação quando não
há devoluções.
> feat(55187): Altera ata de retificação em tela

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
fix(59073):  Padroniza exibição do vazio
Esse PR:
- Padroniza exibição do valor "vazio" (valor zero)
História: [AB#59073](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59073)
> fix(59073): Padroniza exibição do vazio

- src/componentes/escolas/Receitas/ReferenciaDaDespesaEstorno/index.js
Esse PR:
- Exibe tabela de estorno na inclusão da receita correspondente ao estorno
História: [AB#59984](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59984)
> feat(59984): Créditos da Escola: Exibir a tabela de gasto estornado também no formulário de inclusão do estorno

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/ComprovacaoFiscal/comprovacaoFiscal.scss
- src/componentes/escolas/Despesas/ComprovacaoFiscal/index.js
feat(59509): Cadastro de despesa sem comprovação fiscal.
Esse PR:
- Refatora formulário de despesa
- Adiciona campos para perguntar se é despesa com comprovação fiscal e despesa reconhecida pela associacao
- Adiciona campo de boletim de ocorrencia
- Habilita e desabilita campos do formulario de acordo com respostas dos campos citados acima
História: [AB#59509](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59509)
> feat(59509): Cadastro de despesa sem comprovação fiscal

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
Esse PR: 
- Corrige exibição ou não de tipos de documento de acordo com parâmetro documento_comprobatorio_de_despesa
História: [AB#61291](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61291)
> feat(61291): Parametrizar tipos de documento que serão exibidos no select de docs comprobatórios de despesas - Parte 02

- src/componentes/Globais/DatePickerField/index.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/RetemImposto/index.js
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- src/context/Despesa/index.js
- src/paginas/escolas/Despesas/EdicaoDeDespesa/index.js
- src/utils/ValidacoesAdicionaisFormularios.js
feat(61290): Cadastro de mais de um imposto
Esse PR:
- Possibilita cadastro de mais de um imposto por despesa
- Altera validações de imposto
- Adiciona lista de impostos ao payload
História: [AB#61290](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61290)
> feat(61290): Cadastro de mais de um imposto

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabsConferenciaDeLancamentos.js
Esse PR: 
- Corrige exibição dos gastos com seus respectivos tooltip
História: [AB#61151](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61151)
> feat(61151): Exibir informações de retenção de imposto na análise de PC - Parte 02

- hotfixes.md
- package.json
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
História: [AB#63355](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63355)
> fix(63355): Cadastro de despesa não salva lançamento em ação configurada como "livre aplicação" 

- src/componentes/escolas/GeracaoAtaRetificadora/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/FormularioEditaAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/index.js
- src/componentes/escolas/PrestacaoDeContas/index.js
Esse PR altera a exibição e emissão de atas de apresentação e retificação de prestação de contas para passarem a informar quando a ata estiver incompleta e só permitir a emissão de PDF quando ela estiver completa.
História: [AB#59547](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59547)
> feat(59547): Altera status ata de apresentação da ata

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
Esse PR,  na conferência de lançamentos no acompanhamento de PCs, altera o tooltip
de estorno para exibir a data de transação em vez da data do documento.
História: [AB#63021](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63021)
> feat(63021): Altera tootip despesa acompanhamento de PC

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
Corrige: [AB#65643](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/65643)
> fix(65643): O saldo das PCs 2022.1 e 2021.3 da DRE Ipiranga exibe os dados da PC 2021.2

- src/componentes/Globais/EscolheUnidade/ListaDeUnidades.js
- src/componentes/Globais/EscolheUnidade/index.js
- src/componentes/Globais/SuporteAsUnidades/index.js
- src/services/visoes.service.js
Esse PR:
[X] Adiciona o tipo de unidade na seleção da unidade para acesso
[X] Adiciona Nome e UUID da Associação e visão na seleção de unidade para acesso
[X] Grava unidade do suporte como unidade do próximo acesso do usuário
História: [AB#62851](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62851)
> feat(62851): Suporte às Unidades: Viabilizar acesso de suporte - Parte 2

- src/componentes/Globais/BarraMensagemUnidadeEmSuporte/ModalConfirmaEncerramentoSuporte.js
- src/componentes/Globais/BarraMensagemUnidadeEmSuporte/index.js
- src/paginas/PaginasContainer.js
- src/services/auth.service.js
Esse PR:
História: [AB#62837](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62837)
> feat(62837): Suporte às Unidades: Encerrar acesso de suporte

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TextoDinamicoSuperior/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TopoComBotoes/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/index.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/services/dres/AtasParecerTecnico.service.js
- src/services/dres/RelatorioConsolidado.service.js
- src/utils/Modais.js
Esse PR:
- Exibe mensagem caso ata não esteja preenchida
- Remove botões de gerar ata
- Refatora componentes da ata
- Altera nome dos endpoints de download da ata e relatorio consolidado
- Remove chamada ao endpoint de gerar ata
História: [AB#63307](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63307)
> feat(63307): Geração de ata no momento da publicação

- src/componentes/Globais/EscolheUnidade/index.js
- src/componentes/Globais/SuporteAsUnidades/index.js
- src/componentes/Globais/SuporteAsUnidades/suporte-as-unidades.scss
- src/paginas/SME/SuporteAsUnidades/index.js
- src/paginas/dres/SuporteAsUnidades/index.js
Esse PR implementa algumas melhorias na página de seleção de unidade para suporte:
História: [AB#67886](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67886)
> feat(67886) Suporte às unidades: Melhorias na escolha de unidade

- src/componentes/Globais/Dashborard/index.js
Esse PR:
- Alterar o seletor de período do resumo de recursos para permitir a escolha de períodos além dos fechados e último em aberto.
História: [AB#60431](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60431)
> feat(60431): Altera seletor de período do Resumo de Recursos

- src/componentes/escolas/PrestacaoDeContas/index.js
Esse PR:
História: [AB#58005](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58005)
> feat(58005): Altera exibição de atas de retificação

- src/componentes/Globais/CardsDevolucoesParaAcertoDaDre/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/JustificativaDeFaltaDeAjustes.js
Esse PR:
- Exibe Justificativa de Falta de Ajustes em PC 
- Trata quando não existe data de devolução em CardsDevolucoesParaAcertoDaDre
História: [AB#58248](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58248)
> feat(58248): Acompanhamento de PC: Ver justificativa de falta de ajustes em PC retornada após acertos

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Receitas/CancelarModalReceitas.js
- src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/services/escolas/Receitas.service.js
- src/utils/Modais.js
feat(67647): Reabertura seletiva, exclusao de credito
Esse PR:
- Permite acessar formulario de receitas a partir da analise de acertos
- Remove validação de periodo fechado quando acessado pela analise
- Esconde botão de salvar quando exclusao
- Permite acessar formulario de receitar a partir da analise de acertos pela DRE
- Adiciona chamada de API para marcar lancamento como excluido
História: [AB#67647](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67647)
> feat(67647): Reabertura seletiva, exclusao de credito

- src/componentes/Globais/BarraMensagem/barraMensagem.scss
- src/componentes/Globais/BarraMensagem/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
Esse PR:
História: [AB#72442](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72442)
> feature(72442) Adiciona mensagem de inativa em row expansivo.

- src/componentes/Globais/BarraMensagem/barraMensagem.scss
- src/componentes/Globais/ModalBootstrap/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/scss/tagInformacaoTemplate.scss
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/useRowExpansionDespesaTemplate.js
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/useRowExpansionReceitaTemplate.js
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/useTagInformacaoTemplate.js
Esse PR:
História: [AB#73292](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73292)
> Feat(73292) dre lancamentos inativos front

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- src/services/escolas/Despesas.service.js
- src/utils/Modais.js
feat(67652) Reabertura seletiva, inclusão de gasto
Esse PR:
- Altera formulario de gasto para permitir inclusao de gasto mesmo com periodo fechado
- Adiciona chamada a API para marcar inclusao de um gasto no ajuste do documento
- Adiciona regra para não permitir inclusão de gasto incompleto quando feito pelo ajuste do documento
- Adiciona modal de aviso para despesa incompleta
História: [AB#67652](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67652)
> feat(67652) Reabertura seletiva, inclusão de gasto

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/DevolucoesAoTesouro/InformacoesDevolucaoAoTesouro.js
Corrige o bug que ocorria ao clicar-se no botão devoluções ao tesouro da ata de retificação quando a devolução ao tesouro estava relacionada a uma despesa sem comprovação e que não tinha um tipo de documento definido.
> fix(74773): Corrige página dev. tesouro vazia em ata retificação

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/FormularioAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
feat(74825): Marcar documentos como corretos
Esse PR:
- Adiciona "Selecionar todos com solicitação de ajuste" ao menu de seleção
- Permite marcar como correto documentos com ajuste
- Exibe link para remover item ou considerar correto, dependendo se é uma copia ou não
- Adiciona uuid e copiado ao payload
História: [AB#74825](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74825)
> feat(74825): Marcar documentos como corretos

- hotfixes.md
- src/componentes/escolas/AnaliseDre/index.js
Esse PR:
- Corrige exibição ícone de detalhamento em Análise da DRE
História: [AB#76006](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76006)
> fix(76006): Análise DRE: Ícone de detalhamento deve ser exibido também para os demais status

- src/componentes/Globais/BarraMensagem/barraMensagem.scss
- src/componentes/Globais/BarraMensagem/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotaoAcertosLancamentosEdicaoGasto.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosEmExtratosBancarios.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosLancamentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
Esse PR:
História [AB#76332](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76332)
> Feat(76332): Altera nomenclatura das opcoes ver resumo

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertosDevolucaoAoTesouro.js
Corrige a validação de valores parciais de devolução ao tesouro.
Quando o usuário selecionava "Valor total" e depois "valor parcial" a validação não recusava um valor igual ao total do documento.
Corrige [AB#78550](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/78550)
> fix(78550): Corrige validação valor parcial dev tesouro

- src/utils/ValidacoesAdicionaisFormularios.js
A função falhava quando os objetos comparados tinham outros objetos como propriedades.Em uma comparação simples, obj1 === obj2 são considerados diferentes mesmos que iguais em conteúdo.
A função foi alterada para verificar se uma propriedade era um 'object' e, nesse caso, usar a si própria recursivamente para comparar um objeto com o outro.
Corrige [AB#78552](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/78552)
> fix(78552): Corrige função de comparação de objetos

- src/componentes/escolas/Associacao/Membros/CadastroDeMembrosDaAssociacao/index.js
O regex de validação de e-mail de membro de associação não estava validando o caso de um ponto após o e-mail (ex: teste@teste.com.) Esse e-mail era considerado válido.
O regex foi alterado para considerar essa situação.
> fix(78755): Corrige validação e-mail membro associação

- hotfixes.md
- package.json
- src/componentes/escolas/Associacao/Membros/CadastroDeMembrosDaAssociacao/index.js
* docs(1.33.4): Hotfix
Corrige 78755
* fix(78755): Corrige validação e-mail membro associação (#1350)
O regex de validação de e-mail de membro de associação não estava validando o caso de um ponto após o e-mail (ex: teste@teste.com.) Esse e-mail era considerado válido.
O regex foi alterado para considerar essa situação.
> Hotfix/1.33.4 (#1351)

- src/componentes/escolas/Despesas/metodosAuxiliares.js
A validação de valores originais da despesa estavam considerando o campo de valor realizado do imposto, quando deveria usar o valor original.
Corrige [AB#79016](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79016)
> fix(79016): Corrige validação de valores despesa

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/FormularioAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertos.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
feat(77677): Nao permitir incluir itens repetidos
Esse PR:
[x] Não permite seleção repetida de tipos de acerto (exceto para as categorias inclusão de crédito e gasto)
[x] Não permite seleção repetida das categorias (exclusão de lancto e esclarecimento)
História: [AB#77677](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/77677)
> feat(77677): Nao permitir incluir itens repetidos

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertosDevolucaoAoTesouro.js
fix(80934): Incluir acerto dev tesouro
Esse PR:
- Corrige liberação do botão salvar quando acerto de devolução ao tesouro
História: [AB#80934](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80934)
> fix(80934): Incluir acerto dev tesouro

- src/componentes/escolas/PrestacaoDeContas/index.js
Agora, ao fazer a conclusão de uma PC devolvida, a mensagem de aviso de devolução é fechada se estiver aberta.
Corrige [AB#83014](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83014)
> fix(83014): Altera conclusão PC. Fecha mensagem de devolução.

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDocumentos/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
feat(83473): Não permitir marcar como justificado
Esse PR:
- Adiciona regra para desabilitar caixa de esclarecimento quando o status for justificado
- Adiciona modal informando que não foi possivel justificar o acerto
História: [AB#83473](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83473)
> feat(83473): Não permitir marcar como justificado

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
Esse PR:
- Bloqueia o botão de retroceder o recebimento de um PC em retificação
- Modifica a função que gerência o bloqueio do botão retroceder PCs adicionando a condição para verificar PC recebida
História: [AB#83020](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83020)
> feat(83020): Não permitir que a PC retificada retorne para o status de Não Recebida

- src/componentes/Globais/Cabecalho/ModalNotificaErroConcluirPC.js
- src/context/Notificacoes/index.js
Esse PR:
- Altera texto modal erro ao concluir PC
História: [AB#85660](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85660)
> fix(85660): Monitoramento de PCs: reversão de devoluções não pode apagar os arquivos, apenas alterar o status para devolvido

- package-lock.json
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TextoDinamicoSuperior/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
Esse PR altera a exibição em tela da ata de um consolidado DRE :
- O texto da ata é alterado para os casos que tratar-se de uma retificação de consolidado DRE.
- A condição para exibição do alerta de prévia também foi revisto.
[AB#80219](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80219)
> feat(80219): Altera texto ata da retificação de consolidado

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/BotoesAvancarRetroceder.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
Esse PR:
- Adiciona nova propriedade de tooltip ao componente BotoesAvancarRetroceder
- Adiciona função que define qual a tooltip vai ser apresentada no botão de retrocesso de estado de PCs
História: [AB#83020](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83020)
> feat(83020): Não permitir PC retificada retornar para Não Recebida - Parte 2

- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js
Esse PR:
- Adiciona um estado totalizando as PCs retificáveis
- Adiciona a verificação de visibilidade do bloco de PCs retificáveis
História: [AB#83915](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83915)
> feat(83915): Editar Retificação - Incluir PCs na Retificação - Parte 2

- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/ComentariosNotificados/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/TabelaConferenciaDeDocumentosRelatorios/index.js
Esse PR:
- Modifica a visualização do bloco de comentários notificados, baseado em um novo estado
- Modifica a visualização do bloco de acertos
História: [AB#82945](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82945)
> feat(82945): Não exibir blocos de comentários e acertos

- src/componentes/dres/RelatorioConsolidado/index.js
Esse PR:
- Adiciona um estado específico para o carregamento do relatório consolidado
- Modifica o estado do relatório consolidado automaticamente ao gerar um consolidado
- Remove função não mais utilizada de verificação de status do relatório consolidado
História: [AB#80272](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80272)
> feat(80272): Gera relatório consolidado automaticamente - Parte 3

- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/BotoesAvancarRetroceder/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/index.js
Esse PR:
- adiciona função seletiva para a mensagem do botão de avançar o acompanhamento do relatorio
- adiciona prop que repassa a mensagem para o componente BotoesAvancarRetroceder
História: [AB#84792](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/84792)
> feat(84792): Incluir orientação para o usuário na opção de Concluir

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/Cabecalho.js
Esse PR:
- Adiciona o controle de qual mensagem é apresentada para o usuário na análise de PCs
História: [AB#84790](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/84790)
> feat(84790): Adiciona referência no acompanhamento de PCs

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
Esse PR:
- Altera a análise de lançamentos de PC para considerar as categorias de acerto de conciliação
- Bloqueia a repetição de solicitações repetidas nessas categorias
- Bloqueia a exibição dessas categorias em lançamentos de tipo crédito
- Trata a exibição das categorias conforme situação de conciliação da despesa
História: [AB#85901](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85901)
> feat(85901): Inclui tratamento de categorias de conciliação

- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/ModalNotificacaoNaoEntregue.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/index.js
Esse PR:
- Adiciona o modal para indicar ao usuário quando a mensagem não foi enviada com sucesso.
- Altera o estado do modal conforme o retorno da API indicando se a mensagem foi enviada.
História: [AB#86761](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/86761)
> feat(86761): Exibir modal verificando a não possibilidade de notificar a DRE

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/FormularioAcertos.js
feat(88025): Detalhar acertos, exibe nova categoria
Esse PR:
- Refatora funções utilizadas para exibir ou não categoria e seus itens
- Adiciona categoria "EDICAO_INFORMACAO" a categorias que não podem se repetir
História: [AB#88025](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88025)
> feat(88025): Detalhar acertos, exibe nova categoria

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/Cabecalho.js
feat(88259): Acompanhamento de PC
Esse PR:
- Remove regra de negócio do front, agora utiliza apenas o retorno do back
História: [AB#88259](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88259)
> feat(88259): Acompanhamento de PC

- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/index.js
Esse PR:
- Altera o cabeçalho de pc para exibir informações da associação mesmo quando não apresentada.
Corrige AB#89842
> fix(89842): Exibe info de pcs não apresentadas

- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/ModalFormAssociacoes.js
- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js
- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR:
- Adiciona o campo observação na modal de criar e ditar associações com um help-text informativo.
- Remove o campo status de regularidade que não é mais utilizado na modal de criar/editar associação. Remove a sua verificação no frontend.
- Modifica o payload enviado para a API que altera as assoçiações/unidades.
História: [AB#89378](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89378)
> feat(89378): Adiciona o campo observação no modal de associação

- src/componentes/dres/RelatorioConsolidado/BlocoRetificacao/IconeEditarRetificacao.js
Esse PR:
- Adiciona identificar único na tooltip e sua referência, evitando a duplam renderização devido a loops na página.
História: [AB#90108](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90108)
> fix(90108): Adiciona identificar único na tooltip e sua referência

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
Agora a tooltip de estorno utiliza a data de transação, caso não encontre a data de documento
> fix(90066): Corrige data em conferência lançamento

- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/ModalFormAssociacoes.js
- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js
- src/services/sme/Parametrizacoes.service.js
Esse PR:
- Adiciona o DateField de data de encerramento de associação.
- Adiciona a inativação da seleção de período inicial conforme resposta do backend.
- Adiciona tooltip com informativo de bloqueio do campo.
- Adiciona chamada prévia à edição e criação de associação para verificar a validade da data de encerramento.
História: [AB#91682](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91682)
> feat(91682): Adiciona data de encerramento de associação

- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/ModalFormAssociacoes.js
- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js
Esse PR:
- Recebe o novo objeto de erro enviado pelo backend e apresenta ao usuário.
- Fixa mensagens de informação que não estavam presentes no momento de criação da associação.
- Remove loadings no momento de criar e atualizar as associações.
História: [AB#91682](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91682)
> feat(91682): Adiciona mensagem de erro campo encerrar associação

- src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/services/escolas/Receitas.service.js
Esse PR:
- Implementa Validações data de encerramento em Receitas.
- Refatora Módulo de Receitas
História: [AB#91752](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91752)
> feat(91752): Créditos da escola: Não permitir cadastrar/alterar crédito com data posterior ao encerramento da associação

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/services/escolas/Despesas.service.js
Esse PR:
- Adiciona a chamada para API de verificação dos campos de data do pagamento e data do documento
- Adiciona a verificação para que as datas selecionadas não sejam maiores que a data de encerramento da associação.
História: [AB#91755](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91755)
> feat(91755): Adiciona verificação data documento e pagamento

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
Esse PR:
- Desabilita o botão salvar antes do processo de ativação do serviço de encadeamento de modais no cadastro de despesas, assim impossibilitando o registro da mesma despesa mais de uma vez na ação de salvar.
História: [AB#93028](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93028)
> Merge fix 93028 em homolog r2

- src/assets/css/variaveis.scss
- src/componentes/Globais/Tag/index.js
- src/componentes/Globais/Tag/tag.scss
- src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/AutoCompleteAssociacoes.js
- src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/Filtros.js
- src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/TabelaAcoesDasAssociacoes.js
- src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/index.js
- src/services/sme/Parametrizacoes.service.js
Esse PR:
- Adiciona coluna com informação e modal com legenda de etiqueta
- Adiciona sinalização de associação encerrada na pesquisa e bloqueia seleção
- Implementa filtro por informações
História: [AB#93756](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93756)
> feat(93756): Não permitir selecionar associação encerrada

- src/componentes/Globais/EscolheUnidade/ListaDeUnidades.js
- src/componentes/Globais/EscolheUnidade/index.js
- src/componentes/Globais/ModalLegendaInformacao/ModalLegendaInformacao.js
- src/componentes/Globais/TagInformacao/index.js
- src/componentes/Globais/TagInformacao/tagInformacaoTemplate.scss
- src/componentes/dres/Associacoes/TabelaAssociacoes.js
- src/componentes/dres/Associacoes/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/escolas/Despesas/ListaDeDespesas/LegendaInformacao.js
- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/TabelaAssociacoes.js
- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js
- src/services/escolas/Associacao.service.js
Esse PR:
- Adiciona tags conciliação.
- Altera a apresentação das tags de associações e despesas.
- Adiciona endpoint de resgate de tags de associações.
História: [AB#94327](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94327)
> feat(94327): Refatora tags conciliacao bancaria

- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/ModalFormAssociacoes.js
- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js
Esse PR:
- Altera a apresentação do hint do campo período inicial quando apenas leitura que passa a ter múltiplas linhas
- Passa a exibir "*" em campos obrigatórios
Atende [AB#93201](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93201)
> feat(93201): Altera os hints de período inicial apenas leitura e passa a exibir "*" em campos obrigatórios

- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/ModalFormAssociacoes.js
- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR:
- Torna o campo período inicial obrigatória no cadastro de associações
Atende: [AB#93201](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93201)
> feat(93201): Associações - Torna o campo período inicial obrigatório.

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
Esse PR corrige a validação de despesas não reconhecidas.
A validação de campos obrigatórios na despesa não estava levando em consideração que documentos de transação não são obrigatórios em despesas não reconhecidas pela associação.
Corrige [AB#96131](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96131)
> fix(96131): Corrige validação de despesas não reconhecidas

- Dockerfile
- package-lock.json
- package.json
Esse PR:
- Atualiza a versão do NodeJS de 13.14.0 para 14.21.3
- Atualiza a versão do Node-Sass de 4.13.1 para 4.14.1
História: [AB#96256](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96256)
> feat(96256): Atualização de versão - NodeJS 13.14.0 --> 14.21.3

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ArquivosDeReferencia/ArquivosDeReferenciaVisualizacaoDownload.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
- src/services/dres/PrestacaoDeContas.service.js
Esse PR:
- Adiciona na listagem dos materiais de referência, do acompanhamento de pcs, a ata de apresentação da pc e a ata da retificação da apresentação da pc.
- Refatora a apresentação da marca dagua segundo os dados recebidos da ata.
História: [AB#96759](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96759)
> feat(96759): Acompanhamento de pc exibir ata apresentação

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
Esse PR:
- Adiciona ordenamento múltiplo padrão prime react na tabela de conferência de lançamentos
História: [AB#94329](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94329)
> feat(94329): Adiciona ordenamento múltiplo na tabela de conferência de lançamentos

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ArquivosDeReferencia/ArquivosDeReferenciaVisualizacaoDownload.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
feat(97899): Inclui acerto comprovante
Esse PR:
- Remove extrato bancário da lista de documentos
- Adiciona extrato bancário ao acerto da conta
- Adiciona opção de solicitar um novo extrato bancario 
- Adiciona campo observação
- Altera condições para bloqueio do botão salvar ao criar acerto
- Refatora função que calcula se há acertos da conta para habilitar botão ver resumo
História: [AB#97899](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/97899)
> feat(97899): Inclui acerto comprovante

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabsConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/services/mantemEstadoAcompanhamentoDePc.service.js
Esse PR:
- Adiciona o gerenciamento de estado do ordenamento do filtro de conferência e informações de lançamento.
História: [AB#98017](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/98017)
> feat(98017): Mantem estado conferência e informações

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabsConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/services/mantemEstadoAcompanhamentoDePc.service.js
Esse PR:
- Adiciona serviço para manter estado de ordenamento da tabela de análise de lançamentos.
- Altera serviço de manter estados de filtros para incluir o ordenamento no mesmo objeto de acompanhamento de pc.
História: [AB#98017](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/98017)
> feat(98017): Cria servico para manter ordenamento

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/BotoesAvancarRetroceder.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
fix(100511): Desfazer analise de pc em retificação
Esse PR:
- Bloqueia botão para desfazer analise quando uma PC está em retificação
História: [AB#100511](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/100511)
> fix(100511): Desfazer analise de pc em retificação

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertos.js
feat(101624): Categoria devolução ao tesouro não permitida
Esse PR:
- Não permite categoria devolução ao tesouro quando seleção em massa
História: AB#101624
> feat(101624): Categoria devolução ao tesouro não permitida

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/Assinaturas/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/FormularioEditarAta/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
Esse PR:
- Adiciona tooltip na ata de parecer técnico.
- Modifica na visualização prévia e na final da ata a data da assinatura para a data de preenchimento da reunião.
História: AB#100076
> feat(100076): Utiliza a data da reuniao na assinatura da ata

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR:
- Alterar a análise de PC para permitir saldos negativos na solicitação de ajuste em saldos de extrato
Atende AB#103047
> feat(103047): Permitir saldo negativo na análise de extrato

- src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
- src/componentes/escolas/Receitas/Formularios/index.js
Esse PR:
- Adiciona a verificação da data inicial das contas ao digitar a data do crédito que vai ser editado ou adicionado.
- Adiciona mensagem de aviso caso não exita contas para selecionar na data especificada no crédito.
História: AB#103823
> feat(103823): Tratamento data inicial conta no crédito da escola

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/Modais/ModalBloqueioConclusaoContaEncerradaNaoZerada.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
- src/services/dres/PrestacaoDeContas.service.js
Esse PR:
- Adiciona bloqueio de conclusão de PC em análise quando existem contas encerradas com saldo diferente de zero.
- Adiciona modal de bloqueio informativo.
História: AB#104192
> feat(104192): Não permite concluir analise pc com conta não zerada

- src/componentes/Globais/EscolheUnidade/ListaDeUnidades.js
- src/componentes/Globais/TableTags/index.js
- src/componentes/sme/Parametrizacoes/Estrutura/Acoes/TabelaAssociacaoAcao.js
- src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/TabelaAcoesDasAssociacoes.js
- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/TabelaAssociacoes.js
Esse PR:
- Cria a condicionar de exclusão de tags das tabelas de associações.
- Remove a tag de encerramento de conta das tabelas de parametrização e legendas de informações.
História: AB#103479
> fix(103479): Remove etiqueta das tabelas e legendas

- src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
Esse PR:
-  Corrige erro que ocorria ao digitar a data de um crédito do tipo repasse.
Resolve AB#106430
> fix(106430): Erro ao digitar data em crédito tipo repasse

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
Esse PR:
- Altera exibição do valor extrato na análise de PC, para mostrar zeros e não "-"
Resolve AB#106045
> fix(106045): Altera exibição valor extrato para mostrar zeros e não "-"

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
Esse PR:
- Corrige a seleção de contas encerradas quando o fluxo de acesso a edição e inclusão de despesa não é de ajuste solicitado pela DRE.
História: AB#107877
> fix(107877): Corrige selecao de conta quando nao e ajuste despesa

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
Esse PR:
- Corrige o retorno de conta encerrada em nova solicitação de acerto.
História: AB#108395
> fix(108395): Corrige o retorno de conta encerrada em nova solicitação de acerto

- src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
- src/componentes/escolas/Receitas/Formularios/index.js
Esse PR:
- Corrige a seleção de contas que aparecia em branco no momento de cadastrar um estorno pelos gastos da unidade.
História: AB#108899
> fix(108899): Corrige a selecao de conta no cadastro de estorno

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
Esse PR:
- Permite o cadastro de despesas na mesma data de criação da conta, mesmo sendo anterior a data de criação da associação.
História: AB#108693
> feat(108693): Permite o cadastro de despesa baseado no periodo da conta

- package-lock.json
- package.json
Esse PR:
- Atualiza dependências
História: AB#107735
> tec(107735): Preparação para atualização de versão - NodeJS 14.21.3 --> 15.14.0 - atualizar react-datepicker da versão 3.0.0 para 4.21.0

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
Esse PR:
- Adiciona uma validação extra para apresentar contas encerradas que já eram existente nos rateios e nos impostos da despesa.
História: AB#109651
> fix(109651): Contas encerradas pré-selecionadas aparecem na edição despesa

- src/componentes/escolas/PrestacaoDeContas/ModalAvisoAssinatura.js
- src/componentes/escolas/PrestacaoDeContas/index.js
Esse PR:
- Adiciona modal de aviso antes da conclusão da PC quando a flag historico-de-membro está ativa.
História: AB#108546
> feat(108546): Adiciona modal aviso assinatura

- package-lock.json
- package.json
Esse PR:
- Substitui a biblioteca node-sass que está depreciada e adiciona a biblioteca sass que tem a mesma função;
História: AB#107740
> feat(107740): Substitui node-sass por sass

- src/componentes/escolas/PrestacaoDeContas/DemonstrativoFinanceiroPorConta/index.js
Esse PR:
- Remove botão split do downlaod do demonstrativo financeiro;
- Adiciona ícone de download seguindo novo padrão do sistema;
- Retira texto PDF do lado do ícone de download.
História: AB#116393
> feat(116393): Modifica botão de download demo financeiro

- src/componentes/escolas/PrestacaoDeContas/RelacaoDeBens/index.js
Esse PR:
- Remove botão split do downlaod do arquivo de relações de bens;
- Adiciona ícone de download seguindo novo padrão do sistema;
- Retira texto PDF do lado do ícone de download.
História: AB#116394
> feat(116394): Modifica botao download demo financeiro de relacoes bens

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
Esse PR:
- Corrige o posicionamento do checkbox "Não exibir na relação de bens".
História: AB#116392
> feat(116392): Corrigir posicionamento checkbox na despesa

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/NovoFormularioEditaAta/index.js
Esse PR:
- Desabilita a ausência do presidente e do secretário da ata de apresentação.
História: AB#117564
> feat(117564): Desabilita ausência presidente e secretário ata

- src/componentes/Globais/EditorWysiwyg/index.js
- src/componentes/sme/Parametrizacoes/EdicaoDeTextos/FiqueDeOlho/index.js
- src/rotas/index.js
Esse PR:
- Adiciona permissão de acesso e edição no bloco de texto da parametrização de fique de olho.
História: [AB#118557](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118557)
> feat(118557): Adiciona permissão de acesso e edição na parametrização do texto fique olho

- src/rotas/index.js
Esse PR:
- Adiciona permissão na rota de parametrização de motivos de estorno.
História: [AB#118552](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118552)
> feat(118552): Adiciona permissão na rota de parametrização de motivos de estorno

- src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/ModalFormAcoesDasAssociacoes.js
- src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/index.js
Esse PR:
- Adiciona um loading para informar ao usuario sobre o carregamento das unidades em tela.
História: [AB#118536](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118536)
> feat(118536): Adiciona loading no carregamento de associações na parametrização de ações

- src/componentes/sme/Parametrizacoes/EdicaoDeTextos/FiqueDeOlho/index.js
- src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/AutoCompleteAssociacoes.js
- src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/ModalFormAcoesDasAssociacoes.js
- src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/index.js
Esse PR:
- Remove modal de sucesso, para seguir o padrão do projeto de apenas apresentar a mensagem por toast;
- Altera a localização do loading de carregamento de associação e bloqueia input enquanto está carregando.
História: [AB#118536](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118536)
> feat(118536): Remove modal de sucesso e altera localizacao do loading de carregamento

- src/componentes/escolas/GeracaoAtaRetificadora/BoxAtaRetificadora/index.js
- src/componentes/escolas/GeracaoDaAta/GeracaoAtaApresentacao/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/NovoFormularioEditaAta/ModalNotificarRegeracaoAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/NovoFormularioEditaAta/ModalNotificarRegeracaoAta/modal.scss
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/NovoFormularioEditaAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/index.js
Esse PR:
- Adiciona modal de aviso de necessidade de gerar novamente a ata;
- Modifica texto de ata para download.
História: [AB#119648](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119648)
> feat(119648): Remove PDF de apresentacao ao editar ata e adiciona modal de aviso

- src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js
Esse PR:
- Corrige dados repassados para o estado de associações para o filtro de cnpj.
História: [AB#120323](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120323)
> fix(120323): Corrige dados do filtro de cnpj do modal de associacao

- src/componentes/Globais/CentralDeDownloads/ModalConfirmarExclusaoArquivo.js
- src/componentes/Globais/CentralDeDownloads/index.js
Esse PR:
- Altera e padroniza o modal de exclusão de arquivos da central de download;
- Adiciona toast de sucesso e erro.
História: [AB#120418](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120418)
> feat(120418): Altera modal central de download e adiciona toast

- src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/components/ModalForm.js
- src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/components/TopoComBotoes.js
Esse PR:
- Altera labels no cadastro de repasses para "repasse previsto" em vez de apenas "repasse".
Atende história AB#121998
> feat(121998): Altera labels para repasse previsto

- src/componentes/escolas/Receitas/Formularios/index.js
Esse PR,  corrige a confirmação de cancelamento da ação de incluir um crédito que estava sempre abrindo a janela de edição de despesa, o que devia ocorrer apenas no caso de tratar-se da inclusão de um 
estorno.
Resolve AB#122298
> fix(122298): Corrige retorno ao voltar da inclusão de crédito

- src/componentes/escolas/Despesas/ListaDeDespesas/index.js
- src/services/mantemEstadoFiltrosUnidade.service.js
Esse PR:
- Cria o serviço para armazenar os estados dos filtros de pesquisa de despesas;
- Implementa na lógica da tela de despesas os resultados salvos no local storage.
História: AB#124144
> feat(124144): Armazena o estado dos filtros

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/metodosAuxiliares.js
Esse PR:
- Adiciona o index no momento de limpar os dados do select de rateio, assim apagando os dados do rateio correto.
História: AB#124082
> feat(124082): Não apagar dados na edição de rateio no acerto

- src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/ModalForm.js
- src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/Tabela.js
- src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/__tests__/ModalForm.test.js
- src/setupTests.js
Esse PR:
Inclui a lógica de redefinir para valor padrão dos elementos radio quando estes forem reabilitados
Inclui os testes unitários para esta implementação, inclusive as configurações no setup de testes para redução de logs Warning no terminal
> feat(124182): Tipos de documentos - lógica para set de valores dos campos radio no formulário

- src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/ModalForm.js
- src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/Tabela.js
- src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/__tests__/ModalForm.test.js
- src/setupTests.js
Esse PR:
Inclui a lógica de redefinir para valor padrão dos elementos radio quando estes forem reabilitados
Inclui os testes unitários para esta implementação, inclusive as configurações no setup de testes para redução de logs Warning no terminal
> feat(124182): Tipos de documentos - lógica para set de valores dos campos radio no formulário - homolog

- src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/Paginacao.js
- src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/index.js
Esse PR:
- Ajusta a paginação para 20 itens
- Adiciona imagem de "não encontrado" quando não há ações disponíveis na listagem
> feat(126749): Ajustes na tela de listagem de ações pdde

- src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/ModalForm.js
- src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/hooks/useDeleteCategoriaAcaoPDDE.js
Esse PR:
-Ajustes na lógica de exclusão pra ficar no onSuccess/onError do request
-Mostrar botão da lixeira (exclusão de categoria) somente na edição de Ação PDDE
> feature(126749): Ajustes na lógica de exclusão de categoria

- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/hooks/usePatchReceitaPrevistaPdde.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/ModalConfirmarPararAtualizacaoSaldo.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/ReceitasPrevistasModalForm.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/TabelaReceitasPrevistas.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/hooks/useGetAcoesAssociacao.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/hooks/usePararAtualizacaoSaldoPaa.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/index.js
- src/componentes/escolas/Paa/ElaboracaoPaa/index.js
- src/services/escolas/Paa.service.js
Esse PR:
Adiciona a feature de Congelamento de Saldo,
- Modal de confirmação
- Services de ativação/desativação do congelamento
- Inclusão de DADOS_PAA no locastorage para salvar o objeto, inclusive a data de congelamento que será utilizada para determinar se um saldo está ou não "congelado".
- Considera valor zero para soma de totais quando os saldos atuais são negativos (inclusive, exibição de tootips para os respectivos campos - custeio, capital e Livre)
História #126467
> feat(126467): Congelar saldo

- src/componentes/escolas/SituacaoPatrimonial/ListaBemProduzido/__tests__/FormFiltrosBens.test.js
- src/componentes/escolas/SituacaoPatrimonial/ListaBemProduzido/__tests__/index.test.js
Esse PR:
- Adiciona testes unitários na listagem e filtros de situação patrimonial.
História: [AB#127458](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127458)
> feat(127458): Adiciona testes unitários

- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/FormFiltros.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/ModalFormAdicionarPrioridade.js
Esse PR:
- Altera a lógica no uso do map nos arrays para usar um valor padrão de array vazio caso a variável esteja indefinida e assim evitar erro de execução
> feature(127464): Alteração da lógica nos maps

- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/Tabela.js
Esse PR:
Ajusta a legendado da coluna de Ações (botões)
> feature(127464): Ajuste na legenda da coluna de Ação - botões

- src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/InformarValores/index.js
- src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/VincularDespesas/index.css
- src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/VincularDespesas/index.js
Esse PR:
- Adiciona o bloqueio de seleção de despesa com valores totais utilizados na criação de bens produzidos, deixando desbloqueado apenas na edição que já possuía esse despesa.
- Adiciona correções na visualização de valores disponíveis na seção de informar valores de bens produzidos.
História: [AB#129378](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/129378)
> feat(129378): adiciona bloqueio de selecao na listagem despesa

- src/componentes/escolas/Associacao/IconeDadosDaAssociacaoPendentes.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/IconeDataSaldoBancarioPendentes.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/Justivicativa/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
Esse PR:
- Volta campos obrigatórios em conciliação bancária
- Torna campo de justificativa obrigatório condicionado as conciliações e diferença do saldo para pc.
[AB#129997](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/129997)
> feat(129997): Volta campos obrigatórios em conciliação bancária

- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/BadgeCustom.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/Tabela.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/useGetPrioridades.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/usePatchPrioridade.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/usePostPrioridade.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/index.js
- src/index.js
- src/services/escolas/Paa.service.js
Esse PR:
- Inclui um componente para reutilização em duas colunas na tabela (BadgeCustom)
- Hook de API de duplicação
- Adiciona a funcionalidade de duplicar uma prioridade na tabela
Os registros duplicados deve ser exibidos no topo da tabela
História [AB#127468](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127468)
> feat(127468): Ação para duplicar Prioridade

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/PendenciasRecebimento/index.js
Esse PR:
- Adiciona um ajuste que permite o recebimento de PC após acerto quando possui apenas ajuste externo e/ou solicitação de esclarecimento.
História: AB#134733
> hotfix(134733): Adiciona categoria que não requer ata de retificação

- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/ModalImportarPrioridades.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/ModalImportarPrioridades.test.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/index.test.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/__tests__/usePostImportarPrioridades.test.js
- src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/usePostImportarPrioridades.js
- src/rotas/index.js
- src/services/escolas/Paa.service.js
Esse PR:
- Adiciona Modal de Confirmação de Importação do PAA quando já existem prioridades(anteriormente importadas) no Paa Atual
- Validação quando há tentativa de importar as prioridades do mesmo PAA já importado
- Atualização e Inclusão de novos testes unitários sobre a feature
- Inclusão de parâmetro de confirmação no service endpoint
História [AB#134186](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/134186)
> feature(134186): Regras de Importação de Prioridades do PAA

- package.json
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/PendenciasRecebimento/index.js
Esse PR:
- Adiciona um ajustes que permitem o recebimento de PCs após acerto sem ata de retificação apenas quando possui ajuste externo, solicitação de esclarecimento e acertos não realizados.
História: AB#134733
> hotfix(134733): Ajuste no recebimento após acerto
