prefeiturasp/SME-PTRF-FrontEnd

src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/FormularioEditarAta/index.js
src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/index.js
src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js

feat(80032): Motivo retificacao ata parecer tecnico
Esse PR:
- Adiciona motivo retificacao ao formulario de edição da ata
- Altera regra de exibição dos botões na listagem de consolidados
- Adiciona validacao para não permitir que motivo retificacao seja enviado vazio
História: [AB#80032](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80032)

feat(80032): Motivo retificacao ata parecer tecnico

---

src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/acertos-lancamentos.scss
src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/FormularioEditarAta/index.js
src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/index.js
src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/InfoPublicacaoNoDiarioOficial.js
src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/Cabecalho.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/Filtros.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/MotivoRetificacao.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/TabelaPcsEmRetificacao.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/TituloTabela.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js
src/componentes/dres/RelatorioConsolidado/Retificar/index.js
src/componentes/dres/RelatorioConsolidado/relatorio-consolidado.scss
src/services/dres/RelatorioConsolidado.service.js

História: [AB#83752](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83752)

Posição de Develop em 27/01/2023 14:05

---

src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/MotivoRetificacao.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js
src/services/dres/RelatorioConsolidado.service.js

Esse PR:
- Adiciona botão salvar motivo
- Adiciona controle do estado do botão
História: [AB#80011](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80011)

feat(80011): Adiciona edição do motivo de retificação

---

src/componentes/dres/RelatorioConsolidado/DemonstrativoDaExecucaoFisicoFinanceira.js

feat(80031)-retificacao relatorio fisico financeiro
Esse PR:
- Adiciona função para pegar informações de execução fisico financeiro de uma retificacao (para controlar botoes de preencher/consultar resumo)
História: [AB#80031](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80031)

feat(80031)-retificacao relatorio fisico financeiro

---

src/componentes/dres/RelatorioConsolidado/DemonstrativoDaExecucaoFisicoFinanceira.js

[AB#85049](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85049)

Update homolog 03 fev23 10h27m

---

src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/LinkCustom.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategoriasDocumentos/LinkCustom.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
src/componentes/escolas/Despesas/metodosAuxiliares.js

fix(85204): Conciliacao reabertura seletiva
Esse PR:
- Adiciona função para conciliar despesa criada a partir da reabertura seletiva
- Adiciona função para validar se deve conciliar despesa editada a partir da reabertura seletiva
- Adiciona validacao de objeto ao componente LinkCustom
História: [AB#85204](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85204)

fix(85204): Conciliacao reabertura seletiva

---

src/componentes/dres/RelatorioConsolidado/index.js

[AB#85049](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85049)

Update homolog 06 fev23 10h35m

---

src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/TopoComBotoes/index.js
src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/index.js

Esse PR:
- Adiciona o cabeçalho contendo o nome da DRE e o período do resumo
- Edita o padding para padronização do layout do sistema
História: [AB#83697](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83697)

feat(83697): Adiciona cabeçalho em ver resumo

---

src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js

Esse PR:
- Implementa a validação de quando o bloco de PCs deve aparecer para adição na retificação
- Padroniza as mensagens de remoção de PCs da retificação
História: [AB#83915](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83915)

feat(83915): Editar Retificação - Incluir PCs na Retificação

---

src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js

Esse PR:
- Adiciona as mensagens de quando a retificação é feita ou quando é adicionado uma PC a retificação
História: [AB#83168](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83168)

feat(83168): Incluir Retificação: Ajuste de obrigatoriedade e mensagem

---

package-lock.json
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TextoDinamicoSuperior/index.js
src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js
src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/TopoComBotoes/index.js
src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/index.js

[AB#85049](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85049)

Update homolog 07 fev23 13h13m

---

src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/index.js
src/componentes/dres/RelatorioConsolidado/DemonstrativoDaExecucaoFisicoFinanceira.js
src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/BotaoMarcarPublicacaoNoDiarioOficial.js
src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/InfoPublicacaoNoDiarioOficial.js
src/componentes/dres/RelatorioConsolidado/PreviaDocumentoRetificado.js
src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
src/componentes/dres/RelatorioConsolidado/Retificar/index.js
src/componentes/dres/RelatorioConsolidado/index.js
src/utils/Modais.js

feat(80606): Gerar documentos retificacao
Esse PR:
- Altera componente de retificação
- Altera regra para habilitação/desabilitação de botões
- Adiciona chamada de serviço de publicacao ao botão de gerar
- Adiciona uuid retificacao ao payload do serviço de publicacao
História: [AB#80606](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80606)

feat(80606): Gerar documentos retificacao

---

src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/ComentariosNotificados/index.js
src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/TabelaConferenciaDeDocumentosRelatorios/index.js

[AB#85049](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85049)

Update homolog 09 fev23 14h05m

---

src/componentes/dres/RelatorioConsolidado/PreviaDocumentoRetificado.js
src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoEmTela/index.js
src/componentes/dres/RelatorioConsolidado/index.js

feat(74496): Retificacao gerar pdf demonstrativo financeiro
Esse PR:
- Adiciona chamada ao serviço de gerar previa retificacao ao botao gerar
- Altera componente de justificativa do demonstrativo para considerar retificacoes
História: [AB#74496](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74496)

feat(74496): Retificacao gerar pdf demonstrativo financeiro

---

hotfixes.md
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/LinkCustom.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategoriasDocumentos/LinkCustom.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
src/componentes/escolas/Despesas/metodosAuxiliares.js

Merge bug 85204 na branch hotfix 6.0.1

Merge bug 85204 na branch hotfix 6.0.1

---

src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
src/componentes/dres/RelatorioConsolidado/index.js

feat(74496): Retificacao gerar demonstrativo
Esse PR:
- Ajusta estado que controla o modal ao clicar no botão gerar
História: [AB#74496](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74496)

feat(74496): Retificacao gerar demonstrativo

---

src/componentes/dres/RelatorioConsolidado/index.js

feat(74496): Retificacao gerar previa

---

src/componentes/Globais/ModalBootstrap/index.js
src/componentes/dres/RelatorioConsolidado/PreviaDocumentoRetificado.js
src/utils/Modais.js

Esse PR:
- Implementa geração PDF Ata da retificação do Consolidado DRE
História: [AB#79896](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79896)

feat(79896): Retificação do Consolidado das PCs: Gerar PDF - Ata

---

src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/TabelaPcsEmRetificacao.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/TabelaPcsRetificaveis.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js
src/componentes/dres/RelatorioConsolidado/Retificar/index.js
src/services/dres/RelatorioConsolidado.service.js

feat(81495): Incluir novas retificações
Esse PR:
- Refatora componente RetificacaoRelatorioConsolidado
- Altera controle de botões de acordo com o retorno da API
- Controla qual endpoint chamar de acordo com situação da pagina (edição ou adição de retificação)
História: [AB#81495](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/81495)

feat(81495): Incluir novas retificações

---

src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js

feat(85370) Altera termo "Desfazer Retificação"
Esse PR:
- Altera termo para "Cancelar Retificação"
História: [AB#85370](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85370)

feat(85370) Altera termo "Desfazer Retificação"

---

src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
src/componentes/dres/RelatorioConsolidado/index.js
src/services/dres/RelatorioConsolidado.service.js

Esse PR:
- remove o endpoint, não mais utilizado, de geração do relatório consolidado
- remove botão de gerar relatório consolidado
História: [AB#80272](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80272)

feat(80272): Gera relatório consolidado automaticamente

---

src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
src/componentes/dres/RelatorioConsolidado/index.js
src/services/dres/RelatorioConsolidado.service.js

Esse PR:
- Adiciona função de verificação de status do relatório consolidado
- Atualiza o estado do bloco de relatório consolidado

feat(80272): Gera relatório consolidado automaticamente - Parte 2

---

src/componentes/dres/RelatorioConsolidado/index.js

Esse PR:
- Altera modo de setar o estado de acordo com retorno API EM_PROCESSAMENTO
História: [AB#85715](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85715)

fix(85715): Relatório consolidado: o loading não é exibido corretamente na solicitação de geração do demonstrativo - Parte 02

---

src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/FormularioEditarAta/index.js
src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/index.js

Esse PR:
Atende [AB#85372](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85372)

feat(85372): Desobriga motivo retificação em ata do consolidado

---

src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/MotivoRetificacao.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js

Esse PR: 
- Retira obrigatoriedade do campo motivo
História: [AB#86610](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/86610)

feat(86610): Retificação do Consolidado das PCs: Inclusão/Edição da Retificação : Retirar obrigatoriedade do campo Motivo

---

src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/MotivoRetificacao.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js

Esse PR:
- Resolve conflitos
História: [AB#86610](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/86610)

feat(86610): Retificação do Consolidado das PCs: Inclusão/Edição da Retificação : Retirar obrigatoriedade do campo Motivo - Parte 02

---

src/componentes/dres/RelatorioConsolidado/PreviaDocumentoRetificado.js
src/utils/Modais.js

Esse PR:
- Modificar o modal de publicação de retificação
- Gerencia os estados para renderizar o modal conforme a pendência necessária
História: [AB#85993](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85993)

feat(85993):Validar preenchimento Motivo da Retificação na geração da publicação de retificação

---

src/componentes/sme/AcompanhamentoPcsSme/ResumoPorDre.js
src/componentes/sme/AcompanhamentoPcsSmePorDre/BarraTotalAssociacoes.js
src/componentes/sme/AcompanhamentoPcsSmePorDre/FiltroUnidadeEducacional.js
src/componentes/sme/AcompanhamentoPcsSmePorDre/index.js

Esse PR:
- Modifica tabela de resumo geral do período.
- Soma coluna das PCS não recebidas, Em análise e Devolvidas para acertos na coluna Em análise.
- Remove as colunas sobressalentes.
- Remove icones da coluna DRE.
- Adiciona tooltip na coluna Em análise.
- Corrige o layout do botão voltar que estava fora do padrão do projeto.
- Corrige o posicionamento do botão filtrar.
- Altera a faixa de totalização de unidades no detalhamento por DRE.
História: [AB#84793](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/84793)

feat(84793): Ajustar Resumo Geral do Período e Detalhamento por DRE

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/Cabecalho.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertos.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
src/componentes/dres/RelatorioConsolidado/PreviaDocumentoRetificado.js
src/componentes/sme/AcompanhamentoPcsSme/ResumoPorDre.js
src/componentes/sme/AcompanhamentoPcsSmePorDre/BarraTotalAssociacoes.js
src/componentes/sme/AcompanhamentoPcsSmePorDre/FiltroUnidadeEducacional.js
src/componentes/sme/AcompanhamentoPcsSmePorDre/index.js
src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/ModalNotificacaoNaoEntregue.js
src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/index.js
src/utils/Modais.js

Update homolog 09/03/2023 11h55m

---

src/componentes/Globais/SidebarLeft/index.js
src/componentes/escolas/PrestacaoDeContas/ModalNotificaErroConcluirPC.js
src/componentes/escolas/PrestacaoDeContas/TopoSelectPeriodoBotaoConcluir.js
src/componentes/escolas/PrestacaoDeContas/index.js
src/context/Notificacoes/index.js
src/rotas/index.js
src/services/Notificacoes.service.js

Esse PR:
- Implementa Monitoramento de PC com registro de falhas na geração da PC
História: [AB#85587](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85587)

feat(85587): Geração de documentos: Monitoramento do processo de geração de PC

---

src/componentes/sme/ExtracaoDados/Cards.js

Esse PR:
- Adiciona o card de exportação de dados de especificações de materiais e serviços.
História: [AB#86738](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/86738)

feat(86738): Adiciona card de exportação de materiais e serviços

---

src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/TabelaAcertosLancamentos.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotaoAcertosLancamentosConciliacaoGasto.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotaoAcertosLancamentosDesconciliacaoGasto.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/botoesAcertosLancamentosService.service.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertos.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
src/services/dres/PrestacaoDeContas.service.js

Esse PR:
-  Implementa conferir acerto do tipo Conciliação Bancária na Análise DRE
História: [AB#85994](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85994)

feat(85994): Análise DRE: Conferir acerto do tipo Conciliação Bancária

---

src/componentes/escolas/PrestacaoDeContas/index.js
src/context/Notificacoes/index.js

Esse PR:
- Realiza ajustes no Monitoramento de PC

feat(85587): Geração de documentos: Monitoramento do processo de geração de PC - Parte 02

---

src/utils/Modais.js

Esse PR:
- Altera a cor do botão "Editar Justificativa" e do botão "Editar Motivo".
- Altera o texto do botão de "Cancelar" para "Fechar".
História: [AB#85993](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85993)

feat(85993): Altera a cor e o texto dos botões da modal

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js

Agora as informações das contas são exibidas corretamente de acordo com a conta selecionada.

fix(88561): Acertos dados bancários não exibem corretamente

---

src/componentes/dres/RelatorioConsolidado/BlocoPublicacaoParcial.js
src/componentes/dres/RelatorioConsolidado/DemonstrativoDaExecucaoFisicoFinanceira.js
src/componentes/dres/RelatorioConsolidado/PreviaDocumentoRetificado.js
src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
src/componentes/dres/RelatorioConsolidado/index.js
src/componentes/dres/RelatorioConsolidado/relatorio-consolidado.scss

Esse PR:
- Adiciona o componente BlocoPublicacaoParcial que unifica as requisições para o endpoint de reasgate das informações da execução financeira, e refatora componentes para remover onde as requisições não são mais utilizadas.
- Adiciona o loading no botão Gerar até o momento que os dados da execução financeira foram obtidos com sucesso.
- Adiciona estilo botão de loading.
História: [AB#88261](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88261)

feat(88261): Adicionado loading botão gerar

---

hotfixes.md
package.json
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
src/componentes/dres/RelatorioConsolidado/index.js
src/context/Notificacoes/index.js
src/services/dres/RelatorioConsolidado.service.js

[AB#88422](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88422)

Update homolog 22 mar2315h

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/Cabecalho.js

Esse PR:
- Corrige erro na exibição da tag "em retificação" em PCs já publicadas
Corrige [AB#89872](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89872)

fix(89872): Exibição de tag "em retificação" em PC publicada

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/Cabecalho.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js

[AB#88422](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88422)

Update homolog 24 mar2316h

---

src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDocumentos/index.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategoriasDocumentos/InfoAcertoDocumentoEdicaoInformacao.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategoriasDocumentos/LinkCustomSemAcao.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategoriasDocumentos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/Modais/ModalRestaurarJustificativa.js
src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
src/componentes/escolas/Associacao/associacao.scss
src/services/dres/PrestacaoDeContas.service.js

feat(88047): Analise dre Edição informação
Esse PR:
- Exibe novo tipo de acerto
- Adiciona link para restaurar justificativa original
- Adiciona novo componente para exibir se o acerto foi atualizado
História: [AB#88047](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88047)

feat(88047): Analise dre Edição informação

---

src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDocumentos/index.js

feat(88047): Analise DRE, edicao informação
Esse PR:
- Realiza ajuste na exibição da opção "Restaurar justificativas"
História: [AB#88047](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88047)

feat(88047): Analise DRE, edicao informação

---

src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/BotaoMarcarPublicacaoNoDiarioOficial.js
src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/FormMarcarPublicacaoNoDiarioOficial.js
src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js
src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentosRelatorios.js

Esse PR:
- Ajusta mensagens de sucesso
História: [AB#88281](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88281)

feat(88281): Ajustar as mensagens de sucesso

---

src/componentes/dres/RelatorioConsolidado/Retificar/index.js
src/rotas/index.js

feat(90038): Adiciona permissão
Esse PR:
- Adiciona validação de permissão para visualizar a opção retificar
História: [AB#90038](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90038)

feat(90038): Adiciona permissão

---

Dockerfile
Jenkinsfile
src/componentes/dres/RelatorioConsolidado/DemonstrativoDaExecucaoFisicoFinanceira.js
src/componentes/dres/RelatorioConsolidado/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/ModalFormAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js
src/services/dres/AtasParecerTecnico.service.js
src/services/dres/RelatorioConsolidado.service.js
src/utils/ValidacoesAdicionaisFormularios.js

Esse PR:
- Corrige geração relatório consolidado automaticamente em Homolog

fix(90117): Consolidado das PCs: ao concluir a geração do consolidado, o sistema não é atualizado sozinho

---

Jenkinsfile
hotfixes.md
package.json
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js

fix(90066): Conferencia lancamentos 
Esse PR:
- Utiliza data transacao para tooltip, caso não encontre a data de documento
História: [AB#90066](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90066)

fix(90066): Conferencia lancamentos 

---

hotfixes.md
package.json
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js

Necessário para preparação da Release 7.
[AB#88666](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88666)

Atualiza hotfix/6.0.3

---

README.md
hotfixes.md
package-lock.json
package.json
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
src/componentes/dres/RelatorioConsolidado/index.js

Esse PR atualiza a release 7 no ambiente develop.
[AB#88667](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88667)

Release 7 -> Develop

---

src/componentes/sme/ExtracaoDados/Cards.js

feat(90617): Extração de dados saldo final periodo
Esse PR:
- Adiciona card para extrair dados do saldo final do periodo
História: [AB#90617](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90617)

feat(90617): Extração de dados saldo final periodo

---

src/componentes/dres/RelatorioConsolidado/DemonstrativoDaExecucaoFisicoFinanceira.js
src/componentes/dres/RelatorioConsolidado/index.js

Esse PR:
- Corrige loading em Consolidade DRE
História: [AB#91116](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91116)

fix(91116): Geração do consolidado DRE está apresentando loanding perpertuo até apresentar a página

---

src/componentes/sme/ExtracaoDados/Cards.js

feat(90622): Extração de dados relação de bens
Esse PR:
- Adiciona card para extrair dados da relação de bens
História: [AB#90622](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90622)

feat(90622): Extração de dados relação de bens

---

src/componentes/sme/ExtracaoDados/Cards.js

Esse PR:
- Adiciona card de extração dos dados de status de prestações de contas.
História: [AB#90603](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90603)

feat(90603): Adicionado extração status prestações conta

---

hotfixes.md
package.json
src/componentes/dres/RelatorioConsolidado/DemonstrativoDaExecucaoFisicoFinanceira.js
src/componentes/dres/RelatorioConsolidado/index.js

Esse PR:
- Faz o merge de Master em Develop

Merge master em develop

---

src/componentes/sme/ExtracaoDados/Cards.js

Esse PR:
- Adiciona o card de extração de dados das devoluções ao tesouro.
História: [AB#90620](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90620)

feat(90620): Adiciona extração dados devolução ao tesouro

---

src/componentes/sme/ExtracaoDados/Cards.js

feat(90626): Card extração dados rateios
Esse PR:
- Adiciona card para extração de dados de rateios
História: [AB#90626](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90626)

feat(90626): Card extração dados rateios

---

src/componentes/sme/ExtracaoDados/Cards.js

Esse PR:
- Adiciona o card de extração de dados das atas.
História: [AB#90623](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90623)

feat(90623): Adiciona card de exportação de dados das atas

---

src/componentes/sme/ExtracaoDados/Cards.js

Esse PR:
- Implementa Extração de Dados PCs Demonstrativos
História: [AB#90621](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90621)

feat(90621): Extração de dados de Prestações de Contas: Demonstrativos

---

src/componentes/sme/ExtracaoDados/Cards.js

História: [AB#90170](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90170)

feat(90170): Posição em Develop 14/04/2023 às 11:11

---

src/componentes/sme/ExtracaoDados/Cards.js

Esse PR:
- Adiciona o card de extração de dados de despesas.
Historia: [AB#90471](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90471)

Merge 90471 em develop

---

src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/ModalFormAssociacoes.js

Esse PR:
- Diminui mensagem de erro.
História: [AB#91682](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91682)

feat(91682): Diminui mensagem de erro

---

src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js

Esse PR:
- Adiciona uma verificação antes de apresentar os erros no formulário de cadastro de despesa.
História: [AB#91755](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91755)

feat(91755): Adiciona validação mensagem erro

---

src/componentes/sme/AcompanhamentoPcsSmePorDre/index.js

Esse PR:
- Corrige o periodo utilizado para atualizar dados do dashboard.
História: [AB#91273](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91273)

feat(91273): Corrige periodo utilizado para carregar dashboard

---

src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/index.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
src/componentes/sme/AcompanhamentoPcsSmePorDre/index.js
src/services/dres/PrestacaoDeContas.service.js
src/services/escolas/Despesas.service.js

História: [AB#93098](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93098)

Posição em develop 04/05/2023 ás 14:30

---

package-lock.json
package.json

Esse PR atualiza develop com a última posição de master.
[AB#93046](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93046)

Master (8.0.0) -> Develop

---

package-lock.json
package.json
src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/index.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
src/componentes/sme/AcompanhamentoPcsSmePorDre/index.js
src/services/dres/PrestacaoDeContas.service.js
src/services/escolas/Despesas.service.js

História: [AB#93098](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93098)

Posição em develop 05/05/2023 ás 11:55

---

src/componentes/escolas/Associacao/DadosDaAssociacao/index.js
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/index.js
src/componentes/escolas/Associacao/DadosDasContas/index.js
src/componentes/escolas/Associacao/Membros/CadastroDeMembrosDaAssociacao/FormCadastroDeMembrosDaAssociacao.js
src/componentes/escolas/Associacao/Membros/CadastroDeMembrosDaAssociacao/TopoComBotoes.js
src/componentes/escolas/Associacao/Membros/CadastroDeMembrosDaAssociacao/index.js
src/componentes/escolas/Associacao/TabelaMembros/index.js
src/componentes/escolas/Associacao/associacao.scss

feat(92320): Valida se associação encerrada pode editar dados
Esse PR:
- Adiciona validação a aba de dados
- Adiciona validação a aba de membros
- Adiciona validação a aba de contas
História: [AB#92320](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92320)

feat(92320): Valida se associação encerrada pode editar dados

---

src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/ModalFormAssociacoes.js

feat(90879): Altera campo formulário
Esse PR:
- Altera campo no formulário para textarea
História: [AB#90879](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90879)

feat(90879): Altera campo formulário

---

README.md

Atende [AB#92643](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92643)

docs(92643): Altera link para a documentação no readme

---

src/componentes/Globais/EscolheUnidade/ListaDeUnidades.js
src/componentes/Globais/EscolheUnidade/index.js
src/componentes/Globais/LegendaInformaçãoAssociacao/ModalLegendaInformacaoAssociacao.js
src/componentes/Globais/LegendaInformaçãoAssociacao/legendaInformacoesAssociacao.scss
src/hooks/Globais/TagsInformacoesAssociacoes/useTagInformacaoAssociacaoEncerradaTemplate.js

feat(92322): Adiciona nova coluna a suporte de unidades
Esse PR:
- Adiciona hook personalizado para tag de associação encerrada
- Adiciona componente para legenda de informações
- Adiciona nova coluna a tabela
- Adiciona botão para exibir modal de legenda de informações
História: [AB#92322](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92322)

feat(92322): Adiciona nova coluna a suporte de unidades

---

package.json
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
src/componentes/escolas/PrestacaoDeContas/index.js
src/services/escolas/Associacao.service.js

Esse PR:
- Adiciona filtro em periodos para prestação de contas.
História: [AB#93760](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93760)

Merge 93760 em homolog 2

---

src/componentes/escolas/Despesas/FormFiltrosAvancados/index.js
src/componentes/escolas/Despesas/ListaDeDespesas/index.js

Esse PR:
- Adiciona parâmetros na url de soma total das despesas da unidade educacional.
História: [AB#89762](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89762)

feat(89762): Adiciona query params no calculo total despesas

---

src/componentes/dres/Associacoes/FiltrosAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/Filtros.js

Esse PR:
- Corrige os textos informativos da filtragem por informações.
História: [AB#92321](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92321)

feat(92321): Corrigi textos filtro de informações

---

src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/scss/tagInformacaoTemplate.scss

Esse PR:
- Ajusta cores das Tags
História: [AB#89762](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89762)

feat(89762): Gastos da escola: Exibir tags informativas/legenda relacionadas com as despesas

---

Dockerfile
package-lock.json

Esse PR:
-  Atualiza versão do NodeJS de 11.15 para 12.22
História: [AB#92570](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92570)

feat(92570):  Atualização de versão - NodeJS 11.15.0 --> 12.22.12

---

src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js

fix(94556): Alteração data despesa
Esse PR:
- Ajusta função de validar data documento
- Ajusta função de validar data pagamento
História: [AB#94556](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94556)

fix(94556): Alteração data despesa

---

src/componentes/Globais/CardsDevolucoesParaAcertoDaDre/index.js
src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/TopoComBotaoVoltar.js
src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/index.js

Esse PR:
- Adiciona regra para mostrar botão concluir acerto quando a análise selecionada for a última.
[AB#93859](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93859)

feat(93859): Implementa validacao para botao concluir acerto

---

src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js

fix(94556): Valida uuid associacao
Esse PR:
- Valida uuid associação
História: [AB#94556](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94556)

fix(94556): Valida uuid associacao

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js

Esse PR:
- Troca modal por tooltip
- Implementa fluxo para acompanhar mudança de estado das conferências para validação do botão
[AB#90878](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90878)

feat(90878): Modifica fluxo de validação de botão devolução sem acerto

---

src/componentes/escolas/Associacao/Membros/CadastroDeMembrosDaAssociacao/TopoComBotoes.js
src/componentes/escolas/Associacao/Membros/CadastroDeMembrosDaAssociacao/index.js

fix(95182): Form membros associação bloqueado
Esse PR:
- Altera função que valida se pode editar membros
História: [AB#95182](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95182)

fix(95182): Form membros associação bloqueado

---

src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js

Corrige o bug: [AB#94556](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94556)

fix(94556): Alteracao data despesa

---

src/componentes/Globais/EscolheUnidade/ListaDeUnidades.js
src/componentes/Globais/EscolheUnidade/index.js
src/componentes/Globais/ModalLegendaInformacao/ModalLegendaInformacaoAssociacao.js
src/componentes/Globais/ModalLegendaInformacao/ModalLegendaInformacaoDespesa.js
src/componentes/Globais/ModalLegendaInformacao/scss/legendaInformacoesAssociacao.scss
src/componentes/Globais/TagInformacao/index.js
src/componentes/Globais/TagInformacao/tagInformacaoTemplate.scss
src/componentes/dres/Associacoes/TabelaAssociacoes.js
src/componentes/dres/Associacoes/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
src/componentes/escolas/Despesas/ListaDeDespesas/LegendaInformacao.js
src/componentes/escolas/Despesas/ListaDeDespesas/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/TabelaAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js

Esse PR:
- Centraliza as tags do sistema em um único componente.
- Adapta modais e tabelas para utilização do componente criado.
- Adiciona novas etiquetas.
História: [AB#94326](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94326)

feat(94326): Adiciona etiquetas nos gastos da escola

---

src/assets/img/bar-chart.svg
src/componentes/escolas/Despesas/FormFiltroPorEspecificacaoMaterialServico/index.js
src/componentes/escolas/Despesas/FormFiltrosAvancados/index.js
src/componentes/escolas/Despesas/ListaDeDespesas/LegendaInformacao.js
src/componentes/escolas/Despesas/ListaDeDespesas/LimparOrdenacao.js
src/componentes/escolas/Despesas/ListaDeDespesas/ModalOrdenar.js
src/componentes/escolas/Despesas/ListaDeDespesas/Ordenacao.js
src/componentes/escolas/Despesas/ListaDeDespesas/Paginacao.js
src/componentes/escolas/Despesas/ListaDeDespesas/index.js
src/services/escolas/Despesas.service.js

Esse PR: 
- Implementa ordenação em lista de despesas
História: [AB#93248](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93248)

feat(93248): Gastos da escola: Incluir ordenamento das colunas

---

src/componentes/sme/Parametrizacoes/Estrutura/Acoes/AssociacoesDaAcao/FormFiltros/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/AssociacoesDaAcao/ModalInfoNaoPodeDesvincular.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/AssociacoesDaAcao/TabelaAcoes.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/AssociacoesDaAcao/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/TabelaAssociacaoAcao.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/VinculaAssociacoesAAcao/FormFiltros/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/VinculaAssociacoesAAcao/index.js
src/services/sme/Parametrizacoes.service.js

Esse PR:
- Adiciona coluna de informação na tabela de UEs vinculadas
- Adiciona coluna de informação na tabela de associações para vincular 
- Desabilita vincular/desvincular associação encerrada na linha
- Desabilita vincular/desvincular associação encerrada em lote
- Adiciona filtros
- Realiza refact de tabela de associações de ações 
História: [AB#92324](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92324)

feat(92324): Validar vincular/desvincular associação encerrada

---

src/componentes/Globais/CentralDeDownloads/TabelaDownloads.js

feat(92149): Central de downloads
Esse PR:
- Altera texto quantidade de arquivos
História: [AB#92149](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92149)

feat(92149): Central de downloads

---

src/componentes/sme/ConsultaDeSaldosBancarios/ConsultaDeSaldosBancariosDetalhesAssociacoes.js
src/componentes/sme/ConsultaDeSaldosBancarios/TabelaSaldosDetalhesAssociacoes.js
src/componentes/sme/ConsultaDeSaldosBancarios/TabelaSaldosPorUeDre.js

feat(92326): Consulta saldos bancários
Esse PR:
- Exibe nome completo da DRE
- Exibe nome da unidade
- Redimenciosa tabela
História: [AB#92326](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92326)

feat(92326): Consulta saldos bancários

---

src/componentes/Globais/UI/InputSelect.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/FiltrosTransacoes/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaTransacoes/Ordenacao/LimparOrdenacao.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaTransacoes/Ordenacao/ModalOrdenar.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaTransacoes/Ordenacao/Ordenacao.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaTransacoes/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
src/services/escolas/PrestacaoDeContas.service.js

Esse PR:
- Implementa fluxo de ordenação
- Refatora as chamadas de transações de despesa 
- Cria componente de select 
História: [AB#94328](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94328)

feat(94328): Incluir ordenação das colunas em conciliação bancária

---

src/componentes/Globais/TagInformacao/index.js
src/componentes/Globais/TagInformacao/tagInformacaoTemplate.scss

Esse PR:
- Altera a cor das tags Sem comprovação fiscal e Não reconhecida.
História: [AB#94326](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94326)

feat(94326): Altera cor das tags

---

package-lock.json
package.json
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
src/componentes/escolas/Despesas/metodosAuxiliares.js

[AB#95780](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95780)

Release 8.2 -> Develop

---

src/assets/css/styles.scss
src/assets/css/variaveis.scss
src/componentes/escolas/Associacao/associacao.scss
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/FormularioEditaAta/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/TopoComBotoes/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/index.js

Esse PR:
- Adiciona o estilo dos botões de sucesso e erro conforme o styleguide.
- Modifica layout botoões da tela de edição de ata.
- Adiciona o toogle de presença nos participantes que são membros da associação.
História: [AB#94790](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94790)

feat(94790): Adiciona opção membro ausente ata pc

---

src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/index.js

Esse PR:
- Corrige transferência de estado de lista de presença.
História: [AB#94790](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94790)

feat(94790): Ata prestacao conta opcao membro ausente

---

package-lock.json
package.json
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
src/services/visoes.service.js

Esse PR atualiza em develop o hotfix 8.2.1 que resolve os bugs:
- [AB#93550](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93550)
- [AB#96131](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96131)

Update hotfix/8.2.1 em dev

---

src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/IconeDataSaldoBancarioPendentes.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TopoComBotoes/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
src/componentes/escolas/PrestacaoDeContas/index.js
src/rotas/index.js
src/utils/Modais.js

Esse PR:
- Implementa indicação de preenchimento incompleto em Conciliação Bancária
História: [AB#95558](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95558)

feat(95558): Conciliação Bancária Indicar contas com preenchimento incompleto e destacar campos obrigatórios

---

src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/IconeDataSaldoBancarioPendentes.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TopoComBotoes/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
src/componentes/escolas/PrestacaoDeContas/index.js
src/rotas/index.js
src/utils/Modais.js

Esse PR:
- Implementa indicação de preenchimento incompleto em Conciliação Bancária

feat(95558): Conciliação Bancária: Indicar contas com preenchimento incompleto e destacar campos obrigatórios

---

src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/TopoComBotoes/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TabelaPresentes/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TextoDinamicoInferior/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TopoComBotoes/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js

Esse PR:
- Modifica o campo de assinatura para apresentar ausência quando necessário.
- Modifica o layout dos presentes para participantes.
História: [AB#95653](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95653)

feat(95653): Modifica visualização dos membros ausentes na ata

---

src/componentes/dres/RelatorioConsolidado/BlocoRetificacao/IconeEditarRetificacao.js
src/componentes/dres/RelatorioConsolidado/GerarRelatorioRetificacao.js
src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/BotaoMarcarPublicacaoNoDiarioOficial.js
src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/IconeMarcarPublicacaoNoDiarioOficial.js
src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/InfoPublicacaoNoDiarioOficial.js
src/componentes/dres/RelatorioConsolidado/PreviaDocumento.js
src/componentes/dres/RelatorioConsolidado/PreviaDocumentoRetificado.js
src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
src/componentes/dres/RelatorioConsolidado/Retificar/index.js

Esse PR:
- Corrige em Consolidado das PCs - Permissão de ação em usuário de visualização
História: [AB#89995](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89995)

fix(89995): Consolidado das PCs Permissão de ação em usuário de visualização

---

package-lock.json
package.json
src/componentes/dres/RelatorioConsolidado/BlocoRetificacao/IconeEditarRetificacao.js
src/componentes/dres/RelatorioConsolidado/GerarRelatorioRetificacao.js
src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/BotaoMarcarPublicacaoNoDiarioOficial.js
src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/IconeMarcarPublicacaoNoDiarioOficial.js
src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/InfoPublicacaoNoDiarioOficial.js
src/componentes/dres/RelatorioConsolidado/PreviaDocumento.js
src/componentes/dres/RelatorioConsolidado/PreviaDocumentoRetificado.js
src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
src/componentes/dres/RelatorioConsolidado/Retificar/index.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/TopoComBotoes/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TabelaPresentes/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TextoDinamicoInferior/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TopoComBotoes/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
src/services/visoes.service.js

Esse PR:
- Atualiza Homolog com a posição de Develop

Posição em Develop 14/06/2023 às 16:00

---

src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/FormularioEditaAta/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js

Esse PR:
- Ordena os participantes da ata com referência ao padrão apresentado nos membros da associação.
História: [AB#95653](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95653)

feat(95653): Ordena membros da ata de pc

---

src/componentes/Globais/ModalBootstrap/index.js
src/componentes/escolas/Associacao/TopoComBotoes.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TopoComBotoes/index.js
src/componentes/escolas/PrestacaoDeContas/ModalPendenciasCadastrais.js

Esse PR:
- Ajusta posição do botão de voltar para direita
- Adiciona ícone de seta no botão de voltar para padronizar
- Ajusta tamanho do botão de navegação para Dados da Associação e Detalhes da Prestação de Contas.

feat(95557): Muda posição e formato dos botões de voltar

---

package-lock.json
package.json
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TabelaPresentes/index.js

Esse PR atualiza Develop com a posição de master após release 8.3.0.
[AB#96421](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96421)

8.3.0 -> Develop

---

public/index.html

Esse PR:
- Implementa configurações Google Analytics e do Clarity
História: [AB#96883](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96883)

feat(96883): Configuração do Google Analytics e do Clarity

---

src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/ModalFormAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js

Esse PR:
- Corrige validação para criar/editar associação
História: [AB#95530](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95530)

fix(95530): Corrige validação para criar/editar associação

---

package.json
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TabelaPresentes/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/ModalFormAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js

Esse PR atualiza em develop o hotfix 8.3.1 que resolve o bug:
[AB#95530](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95530)

Update hotfix/8.3.1 em dev

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ComentariosDeAnalise.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContasNaoApresentada/index.js
src/services/dres/PrestacaoDeContas.service.js

Esse PR:
- Implementa Comentários da Análise e Notificar a Associação no status de PC Não apresentada
História: [AB#96783](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96783)

feat(96783): Acompanhamento de PC: Inserir Comentários da Análise e Notificar a Associação no status de PC "Não apresentada"

---

package.json
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ComentariosDeAnalise.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContasNaoApresentada/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/ModalFormAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js
src/services/dres/PrestacaoDeContas.service.js

História: [AB#96413](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96413)

Posição em Develop 28/06/2023 às 10:05h

---

src/componentes/dres/PrestacaoDeContas/ModalEditarDeletarComentario.js

Esse PR:
- Corrige label botao modal editar comentario
História: [AB#96783](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96783)

feat(96783): Acompanhamento de PC: Inserir Comentários da Análise e Notificar a Associação no status de PC Não apresentada

---

src/componentes/escolas/Associacao/DadosDaAssociacao/index.js

Esse PR:
-  Troca email da associação por email da unidade e desabilita edição
História: [AB#98095](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/98095)

feat(98095): [Associação] Exibir email da unidade e desabilitar edição

---

Jenkinsfile
package-lock.json
package.json

Esse PR:
- Merge release 8.4.0 em develop
História: [AB#97749](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/97749)

feat(97749): Deploy Homolog2 e Develop

---

src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoEmTela/index.js

Esse PR:
- Substitui modal de mensagem de sucesso para um toast.
História: [AB#90958](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90958)

feat(90958): Altera mensagem sucesso de modal para toast

---

src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertoComprovanteSaldoDaConta.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosEmExtratosBancarios.js

Esse PR:
- Inclui exibição da solicitação de acerto para o comprovante do Saldo da Conta em Análise DRE
História: [AB#98105](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/98105)

feat(98105):  Análise DRE: Exibir acerto para o Comprovante do Saldo da Conta

---

src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertoComprovanteSaldoDaConta.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosEmExtratosBancarios.js

Esse PR:
- Merge develop em homolog 05 07

Posição em Develop 05/07/2023 às 14:58h

---

src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertoComprovanteSaldoDaConta.js

Esse PR:
-  Ajusta layout de acordo com protótipo
História: [AB#98105](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/98105)

feat(98105): Análise DRE: Exibir acerto para o Comprovante do Saldo da Conta

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ArquivosDeReferencia/ArquivosDeReferenciaVisualizacaoDownload.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js

Agora é exibido o comprovante de extrato bancário nos materias de referencia

feat(97899): Inclui acerto comprovante

---

src/assets/css/styles.scss
src/componentes/sme/Parametrizacoes/Estrutura/TiposConta/BtnAddTipoConta.js
src/componentes/sme/Parametrizacoes/Estrutura/TiposConta/Filtros.js
src/componentes/sme/Parametrizacoes/Estrutura/TiposConta/ModalAddEditTipoConta.js
src/componentes/sme/Parametrizacoes/Estrutura/TiposConta/ModalConfirmDeleteTipoConta.js
src/componentes/sme/Parametrizacoes/Estrutura/TiposConta/TabelaTiposConta.js
src/componentes/sme/Parametrizacoes/Estrutura/TiposConta/YupSchemaTipoConta.js
src/componentes/sme/Parametrizacoes/Estrutura/TiposConta/index.js
src/componentes/sme/Parametrizacoes/Estrutura/parametrizacoes-estrutura.scss
src/rotas/index.js
src/services/sme/Parametrizacoes.service.js

Esse PR:
- Adiciona a parametrização dos tipos de conta.
- Adiciona o scss para o novo styleguide dos botões vermelho e verde base.
- Cria componentes, modais e rotas referentes a parametrização dos tipos de conta.
História: [AB#29913](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/29913)

feat(29913): Parametrização dos tipos de conta

---

src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
src/componentes/escolas/Despesas/CadastroDeDespesas/ExibeMotivosPagamentoAntecipadoNoForm.js

Esse PR:
- Corrige a validação do rateio
- Corrige renderização do componente ExibeMotivosPagamentoAntecipadoNoForm que estava quebrando ao entrar na despesa
História: [AB#99086](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/99086)

fix(99086): Corrige validação rateio

---

package.json
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
src/componentes/escolas/Despesas/CadastroDeDespesas/ExibeMotivosPagamentoAntecipadoNoForm.js

Esse PR atualiza em develop o hotfix 8.4.1 que resolve o bug:
[AB#99086](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/99086)

Update hotfix/8.4.1 em dev

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js

História: [AB#94329](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94329)

feat(94329): Adiciona sortField no ordenamento da coluna informações

---

package-lock.json
package.json

Esse PR:
- Realiza o deploy da sprint 69 em develop
História: [AB#99260](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/99260)

feat(99260): Deploy Homolog2/Develop

---

src/componentes/sme/Mandatos/components/Lista.js
src/componentes/sme/Mandatos/components/ModalForm.js
src/componentes/sme/Mandatos/context/Mandatos.js
src/componentes/sme/Mandatos/hooks/usePatchMandato.js
src/componentes/sme/Mandatos/hooks/usePostMandato.js

Esse PR:
-  Corrige exibição dos modais.
- Implementa controle de bloqueio no botão salvar form
História: [AB#99037](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/99037)

feat(99037): Parametrizações do sistema: Períodos de mandato

---

src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/BarraStatusEncerramentoConta.js
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/CardSaldoEncerramentoConta.js
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/ModalConfirmEncerramentoConta.js
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/ModalMotivoRejeicaoEncerramento.js
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/form-dados-das-contas.scss
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/index.js
src/componentes/escolas/Associacao/DadosDasContas/index.js
src/services/escolas/Associacao.service.js
src/utils/FormataData.js

Esse PR:
- Adiciona a funcionalidade de solicitação de encerramento de contas nas associações.
História: [AB#46181](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46181)

feat(46181): Adiciona a solicitacao de encerramento de contas

---

src/componentes/escolas/Associacao/DadosDasContas/index.js
src/componentes/sme/PainelParametrizacoes/index.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/YupSchemaMotivosRejeicao.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/components/ExibicaoQuantidade.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/components/Filtros.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/components/Lista.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/components/ModalConfirmacaoExclusao.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/components/ModalForm.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/components/Paginacao.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/components/TopoComBotoes.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/context/MotivosRejeicao.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/hooks/useDeleteMotivoRejeicao.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/hooks/useGetMotivosRejeicao.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/hooks/usePatchMotivoRejeicao.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/hooks/usePostMotivoRejeicao.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/index.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/motivosRejeicao.scss
src/rotas/index.js
src/services/MotivosRejeicaoEncerramentoConta.service.js
src/services/escolas/Associacao.service.js

Esse PR:
- Adiciona a parametrização dos motivos de rejeição do encerramento de contas.
História: [AB#87224](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/87224)

feat(87224): Parametrização dos motivos de rejeição do encerramento de conta

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/DadosDasContas/InfosContas.js
src/componentes/dres/Associacoes/DadosDasAssociacoes/index.js
src/utils/FormataData.js

Esse PR:
- Separa as informações das contass da associação em uma nova aba.
- Adiciona função auxiliar de transformação de data.
- Modifica layout de apresentação de contas.
História: [AB#87275](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/87275)

feat(87275): Cria nova aba de contas na consulta de associações

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/DadosDasContas/InfosContas.js
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/CardSaldoEncerramentoConta.js
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/index.js
src/componentes/escolas/Associacao/DadosDasContas/index.js
src/componentes/sme/AcompanhamentoPcsSme/ResumoPorDre.js
src/componentes/sme/AcompanhamentoPcsSme/index.js
src/services/sme/DashboardSme.service.js

Esse PR:
- Modifica a apresentação do acompanhamento de PCs na visão SME.
História: [AB#96405](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96405)

feat(96405): Modifica exibição acompanhamento PCs

---

Jenkinsfile
package-lock.json
package.json

Esse PR:
- Atualiza develop com posição em master 04/08/2023

Merge master em dev 04 08

---

Jenkinsfile
package-lock.json
package.json

História: [AB#99794](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/99794)

Posição em Develop 04/08/2023 às 10:35h

---

src/assets/css/styles.scss
src/assets/css/variaveis.scss
src/componentes/dres/Associacoes/DadosDasAssociacoes/DadosDasContas/InfosContas.js
src/componentes/dres/Associacoes/DadosDasAssociacoes/DadosDasContas/TabelaContasEncerradas/index.js
src/componentes/dres/Associacoes/index.js
src/componentes/escolas/Associacao/DadosDasContas/TabelaContasEncerradas/index.js
src/componentes/escolas/Associacao/DadosDasContas/index.js
src/services/dres/Associacoes.service.js
src/services/escolas/Associacao.service.js

Esse PR:
- Implementa componente tabela de contas encerradas para UE e DRE.
História: [AB#99318](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/99318)

feat(99318): Histórico de contas encerradas

---

src/assets/css/styles.scss
src/componentes/escolas/MembrosDaAssociacao/components/CargosDaComposicaoList.js
src/componentes/escolas/MembrosDaAssociacao/components/MandatoInfo.js
src/componentes/escolas/MembrosDaAssociacao/components/Paginacao.js
src/componentes/escolas/MembrosDaAssociacao/context/MembrosDaAssociacao.js
src/componentes/escolas/MembrosDaAssociacao/hooks/useGetCargosDaComposicao.js
src/componentes/escolas/MembrosDaAssociacao/hooks/useGetMandatoVigente.js
src/componentes/escolas/MembrosDaAssociacao/index.js
src/componentes/escolas/MembrosDaAssociacao/membros-da-associacao.scss
src/componentes/escolas/MembrosDaAssociacao/pages/MandatosAnteriores.js
src/componentes/escolas/MembrosDaAssociacao/pages/PaginaMandatoVigente.js
src/paginas/escolas/MembrosDaAssociacao/index.js
src/rotas/index.js
src/services/Mandatos.service.js

Esse PR:
- Implementa consulta Mandato Vigente com Composição Vigente em Membros da Associacao
História: [AB#86461](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/86461)

feat(86461): Dados da associação: Membros: Consultar Mandato vigente com composição vigente

---

src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
src/componentes/escolas/Despesas/FormFiltrosAvancados/index.js

Esse PR:
- Aplica tratamento em filtros 
- Aplica tratamento em criação/edição de despesa
- Aplica tratamento em deletar despesa
História: AB#48770

feat(48770): Implementa tratamento de contas encerradas em gastos

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/DadosDasContas/TabelaContasEncerradas/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
src/componentes/escolas/PrestacaoDeContas/SelectPeriodoConta.js
src/services/escolas/Associacao.service.js
src/utils/FormataData.js

Esse PR:
- Altera chamada de contas para filtrar por período quando necessário.
- Adiciona informação de data encerramento de encerramento da conta no select.
História: AB#48773

feat(48773): Tratamento de contas encerradas em conciliação

---

src/componentes/Globais/Dashborard/SelectConta.js
src/componentes/Globais/Dashborard/index.js
src/services/Dashboard.service.js

Esse PR:
- Modifica chamada de contas em resumo de recursos para UE e DRE
História: AB#48764

feat(48764): Tratamento de contas encerradas em resumo de recursos

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/BotoesAvancarRetroceder.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js

fix(100511): Desfazer analise de pc em retificação

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js

fix(100511): Retira bloqueio do botão desfazer conclusao analise
Esse PR:
- Retira bloqueio do botão de desfazer conclusão analise de uma PC em retificacao
História: AB#100511

fix(100511): Retira bloqueio do botão desfazer conclusao analise

---

src/componentes/escolas/MembrosDaAssociacao/components/CargosDaComposicaoList.js
src/componentes/escolas/MembrosDaAssociacao/components/ComposicaoInfo.js
src/componentes/escolas/MembrosDaAssociacao/components/MandatoInfo.js
src/componentes/escolas/MembrosDaAssociacao/components/Paginacao.js
src/componentes/escolas/MembrosDaAssociacao/hooks/useGetComposicao.js
src/componentes/escolas/MembrosDaAssociacao/index.js
src/componentes/escolas/MembrosDaAssociacao/membros-da-associacao.scss
src/componentes/escolas/MembrosDaAssociacao/pages/PaginaMandatoVigente.js
src/componentes/escolas/MembrosDaAssociacao/pages/PaginaMandatosAnteriores.js
src/rotas/index.js
src/services/Mandatos.service.js

Esse PR:
- Implementa Mandato Vigente com Composições Anteriores
História: AB#99164

feat(99164): Dados da associação: Membros: Consultar Mandato vigente com composições anteriores

---

src/componentes/escolas/Despesas/FormFiltrosAvancados/index.js

feat(101613): Altera data-qa options
Esse PR:
- Altera data-qa options dos selects
História: AB#101613

feat(101613): Altera data-qa options

---

src/assets/css/variaveis.scss
src/componentes/Globais/ModalLegendaInformacao/scss/tagModalLegendaInformacao.scss
src/componentes/Globais/TableTags/tableTags.scss
src/utils/CoresTags.js

Esse PR:
- Adiciona etiqueta de imposto a ser pago.
- Refatora localização das cores das etiquetas.
História: AB#101135

feat(101135): Adiciona etiqueta de imposto a ser pago

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AssociacaoEPeriodoDoCabecalho.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/TopoComBotoes.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/TopoComBotoes.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TopoComBotoes.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js

Esse PR:
- Adiciona componente com nome da associação e período da análise em questão no acompanhamento de PC. 
- Componente adicionado no histórico e na análise atual do resumo de acertos, na tela de ajustes de lançamentos e na tela de ajustes de documentos.
HIstória: AB#100077

feat(100077): Adiciona nome associacao e periodo acompanhamento pc

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/DadosDasContas/InfosContas.js
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/CardSaldoEncerramentoConta.js
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/index.js
src/componentes/escolas/Associacao/DadosDasContas/TabelaContasEncerradas/index.js

Esse PR
- Corrige 102417
História: AB#102417

fix(102417): Encerramento de conta: o fluxo novo está disponível para o usuário em produção, sem a devida conclusão do processo

---

src/assets/css/variaveis.scss
src/componentes/Globais/ModalLegendaInformacao/scss/tagModalLegendaInformacao.scss
src/componentes/Globais/TableTags/tableTags.scss
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AssociacaoEPeriodoDoCabecalho.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/TopoComBotoes.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/TopoComBotoes.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TopoComBotoes.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
src/utils/CoresTags.js

Posição em Develop 28/08/2023 às 14:50h

---

Jenkinsfile
package-lock.json
package.json
src/componentes/dres/Associacoes/DadosDasAssociacoes/DadosDasContas/InfosContas.js
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/CardSaldoEncerramentoConta.js
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/index.js
src/componentes/escolas/Associacao/DadosDasContas/TabelaContasEncerradas/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js

Esse PR:
- Atualiza hotfix 8.7.3 em develop

Merge hotfix 8 7 3 em develop

---

src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
src/componentes/escolas/PrestacaoDeContas/ModalSalvarDataSaldoExtrato.js

feat(101564): Encerramento conta, conciliação
Esse PR:
- Altera formulário de observações para entrar em modo edição quando há solicitação de encerramento de conta
História: AB#101564

feat(101564): Encerramento conta, conciliação

---

src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentosRelatorios.js
src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/conferencia-de-documentos.scss
src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/index.js

Esse PR:
- Corrige seleção em massa sem consolidado estar em análise
Bug#90116

fix(90116): Análise de relatórios DRE: é possível usar a seleção em massa mesmo quando o consolidado não está em análise

---

src/componentes/escolas/PrestacaoDeContas/index.js
src/services/escolas/Associacao.service.js

Esse PR:
- Adiciona o novo end-point que retorna apenas as contas que devem ser exibidas na prestação de contas da UE.
História: AB#48775

feat(48775): Tratamento abas contas encerradas geracao documento

---

src/componentes/escolas/Associacao/DadosDasContas/index.js

Esse PR:
- Adiciona as mensagens de sucesso e erro do toast de encerramento de conta.
História: AB#101137

feat(101137): Modifica mensagens toast encerramento conta

---

src/componentes/Globais/GestaoDePerfis/index.js
src/componentes/Globais/SuporteAsUnidades/index.js
src/services/auth.service.js
src/services/visoes.service.js

Esse PR:
- Cria serviço para verificar se usuário possui uma determinada feature flag ativa
- Implementa uma POC do uso de feature flags
Atende AB#102442

feat:(102442): Implementa recurso de Feature Flags

---

src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js

Esse PR:
- Altera a conciliação para permitir informa saldos negativos
Resolve AB#102972

feat(102972): Permitir saldo negativo em conciliação

---

src/componentes/Globais/GestaoDePerfis/index.js
src/componentes/Globais/SuporteAsUnidades/index.js
src/services/auth.service.js
src/services/visoes.service.js

Esse PR:
- Atualiza Homologação com Posição em Develop 06/09/2023
História: AB#102573

Posição em Develop 06/09/2023

---

src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js

Esse PR:
- Altera a conciliação para exibir no formulário de extrato as informações de solicitação de encerramento da conta.
Atende AB#103003

feat(103003): Exibe informações de encerramento de conta na conciliação

---

src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/index.js

Esse PR:
- Adiciona a validação da edição dos campos da conta se ela estiver inativada.
História: AB#101655

feat(101655): Bloqueia edicao dados contas inativas

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/DadosDasContas/InfosContas.js

Esse PR:
- Altera mensagens quando não existem contas para serem exibidas ou todas foram encerradas.
História: AB#101670

feat(101670): Modifica mensagem quando nao existe conta

---

src/componentes/escolas/PrestacaoDeContas/index.js

feat(102928): Verificar data de criação da conta
Esse PR:
- Cria função para controlar qual conta deve ser exibida
História: AB#102928

feat(102928): Verificar data de criação da conta

---

src/componentes/escolas/PrestacaoDeContas/index.js

feat(102928): Ajuste de texto
Esse PR:
- Realiza ajuste de texto
História: AB#102928

feat(102928): Ajuste de texto

---

package-lock.json
package.json
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js

Esse PR atualiza a release 8.9.0 em develop.
AB#103565

Release 8.9.0 -> Develop

---

src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/BarraStatusEncerramentoConta.js

Esse PR:
- Adiciona o estado da conta no useffect do componente de status de encerramento de conta para atualizar a mensagem conforme o estado da solicitação.
História: AB#104161

feat(104161): Adiciona estado conta no useEffect

---

src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js

Esse PR:
- Filtra contas com base na data de pagamento.
- Ajusta labels. 
História: AB#103824

feat(103824): Valida data inicio conta no formulário de gastos

---

src/App.js
src/componentes/Globais/Modal/Modal.js
src/componentes/Globais/Modal/ModalConfirm.js
src/componentes/escolas/PrestacaoDeContas/index.js
src/store/reducers/componentes/Globais/Modal/actions.js
src/store/reducers/componentes/Globais/Modal/reducer.js
src/store/reducers/index.js

Esse PR:
- Implementa alerta de conclusão de acertos com contas encerradas com saldo diferente de 0.
- Adiciona componente de modal para ser reutilizado.
História: AB#104193

feat(104193): Implementa alerta de conclusão de acertos com contas encerradas com saldo diferente de 0

---

src/componentes/Globais/Modal/ModalInfo.js
src/componentes/sme/Mandatos/components/Lista.js
src/componentes/sme/Mandatos/components/ModalForm.js
src/componentes/sme/Mandatos/hooks/useDeleteMandato.js
src/services/Mandatos.service.js

Esse PR:
- Implementa validação e exclusão de período de mandato
História: AB#99081

feat(99081): Implementa validação e exclusão de período de mandato

---

src/componentes/escolas/Associacao/DadosDasContas/index.js

Esse PR:
- Adiciona loading ao buscar contas
História: AB#103765

feat(103765): Adiciona loading ao buscar contas

---

src/componentes/sme/Parametrizacoes/Estrutura/Periodos/BtnAddPeriodos.js
src/componentes/sme/Parametrizacoes/Estrutura/Periodos/Filtros.js
src/componentes/sme/Parametrizacoes/Estrutura/Periodos/ModalFormPeriodos.js
src/componentes/sme/Parametrizacoes/Estrutura/Periodos/TabelaPeriodos.js
src/componentes/sme/Parametrizacoes/Estrutura/Periodos/index.js

Esse PR:
- Adiciona ids nos componentes referentes as páginas do cadastro de períodos para facilitar a construção de testes automatizados.
Atende a história AB#102930

feat(102930): Adiciona ids para testes automatizados

---

src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
src/services/escolas/PrestacaoDeContas.service.js

Esse PR:
- Unifica endpoint de edição de extrato com o de observações.
- Adiciona condicionais para poupar número de requests.
História: AB#102929

feat(102929): Possibilita edição extrato no periodo criação conta 

---

src/componentes/escolas/Receitas/Formularios/index.js

Esse PR:
- Adiciona a verificação se existe alguma solicitação de encerramento de conta nos elementos do select de contas.
História: AB#103823

feat(103823): Corrige validação select conta

---

src/componentes/escolas/MembrosDaAssociacao/components/CargosDaComposicaoList.js
src/componentes/escolas/MembrosDaAssociacao/components/ComposicaoInfo.js
src/componentes/escolas/MembrosDaAssociacao/components/MandatoInfo.js
src/componentes/escolas/MembrosDaAssociacao/components/Paginacao.js
src/componentes/escolas/MembrosDaAssociacao/components/SelectMandatosAnteriores.js
src/componentes/escolas/MembrosDaAssociacao/context/MembrosDaAssociacao.js
src/componentes/escolas/MembrosDaAssociacao/hooks/useGetMandatoAnterior.js
src/componentes/escolas/MembrosDaAssociacao/hooks/useGetMandatosAnteriores.js
src/componentes/escolas/MembrosDaAssociacao/index.js
src/componentes/escolas/MembrosDaAssociacao/membros-da-associacao.scss
src/componentes/escolas/MembrosDaAssociacao/pages/PaginaMandatoVigente.js
src/componentes/escolas/MembrosDaAssociacao/pages/PaginaMandatosAnteriores.js
src/services/Mandatos.service.js

Esse PR:
- Merge feat 99165 em develop
- 
História: AB#99165

feat(99165): Dados da associação: Membros: Consultar Mandatos anteriores

---

src/componentes/escolas/Receitas/Formularios/index.js
src/utils/Modais.js

Esse PR:
- Remove modal de sucesso quando é adicionado um crédito no sistema.
História: AB#105500

feat(105500): remove modal sucesso cadastro credito

---

src/componentes/Globais/Mensagens/MsgImgCentralizada/index.js
src/componentes/Globais/Modal/CustomModalConfirm.js
src/componentes/Globais/ModalBootstrap/index.js
src/componentes/escolas/GeracaoAtaRetificadora/BoxAtaRetificadora/index.js
src/componentes/escolas/GeracaoDaAta/GeracaoAtaApresentacao/index.js
src/componentes/escolas/GeracaoDaAta/ModalNaoPodeGerarAta.js
src/componentes/escolas/PrestacaoDeContas/BarraDeStatusPrestacaoDeContas.js
src/componentes/escolas/PrestacaoDeContas/DemonstrativoFinanceiroPorConta/index.js
src/componentes/escolas/PrestacaoDeContas/ModalConcluirAcertoComPendencias.js
src/componentes/escolas/PrestacaoDeContas/ModalConcluirAcertoSemPendencias.js
src/componentes/escolas/PrestacaoDeContas/ModalConcluirPeriodo.js
src/componentes/escolas/PrestacaoDeContas/ModalGerarPrevia.js
src/componentes/escolas/PrestacaoDeContas/ModalGerarPreviaSendogerada.js
src/componentes/escolas/PrestacaoDeContas/ModalNotificaErroConcluirPC.js
src/componentes/escolas/PrestacaoDeContas/ModalPendenciasCadastrais.js
src/componentes/escolas/PrestacaoDeContas/RelacaoDeBens/index.js
src/componentes/escolas/PrestacaoDeContas/TopoSelectPeriodoBotaoConcluir.js
src/componentes/escolas/PrestacaoDeContas/index.js

Esse PR adiciona data-qa nos seguintes elementos
- Status PC
- Select de período 
- Botão concluir período/acerto
- tabs contas
- status e botões dos boxs Demonstrativo financeiro, Relação de bens e Ata.
- Modais atrelados ao fluxo
História: AB#105258

feat(105258): Adiciona data-qa nos elementos dinâmicos do fluxo de geração de documentos

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/DadosDasContas/TabelaContasEncerradas/index.js
src/componentes/escolas/Associacao/DadosDasContas/TabelaContasEncerradas/index.js

Esse PR:
- Remove parâmetro de linha clicável
- Adiciona coluna tipo de conta
História: AB#105961

fix(105961): Ajusta tabelas de contas encerradas

---

src/componentes/Globais/GestaoDeUsuariosForm/components/GestaoDeUsuariosFormMain.js
src/componentes/Globais/GestaoDeUsuariosForm/components/UnidadesUsuario.js
src/componentes/Globais/GestaoDeUsuariosForm/context/UnidadesUsuarioProvider.js
src/componentes/Globais/GestaoDeUsuariosForm/hooks/useDesabilitarAcesso.js
src/componentes/Globais/GestaoDeUsuariosForm/hooks/useHabilitarAcesso.js
src/componentes/Globais/GestaoDeUsuariosForm/hooks/useUnidadesUsuario.js
src/componentes/Globais/GestaoDeUsuariosForm/style/gestao-de-usuarios-form.scss
src/componentes/Globais/ToastCustom/index.js
src/services/GestaoDeUsuarios.service.js

feat(87153): Lista de unidades em gestão de usuários
Esse PR:
- Adiciona componente para listar unidades
- Adiciona context para lista de unidades
- Adiciona hook para habilitar acesso
- Adiciona hook para desabilitar acesso
- Adiciona hook para lista de unidades
História: AB#87153

feat(87153): Lista de unidades em gestão de usuários

---

src/componentes/escolas/MembrosDaAssociacao/pages/PaginaMandatosAnteriores.js
src/componentes/sme/Mandatos/components/Lista.js
src/componentes/sme/Mandatos/components/ModalForm.js
src/componentes/sme/Mandatos/components/TopoComBotoes.js
src/componentes/sme/Mandatos/context/Mandatos.js
src/componentes/sme/Mandatos/hooks/useDeleteMandato.js
src/componentes/sme/Mandatos/hooks/useGetMandatoMaisRecente.js
src/componentes/sme/Mandatos/hooks/usePatchMandato.js
src/componentes/sme/Mandatos/hooks/usePostMandato.js
src/services/Mandatos.service.js

Esse PR:
- Implementa períodos de mandato não permitir sobreposições
História: AB#102539

feat(102539): Parametrizações do sistema: Períodos de mandato: Não permitir sobreposição de períodos e edição apenas no último período cadastrado

---

src/componentes/Globais/Dashborard/SelectConta.js

fix(105962): Exibição conta encerrada
Esse PR:
- Ajusta condição para exibir a mensagem de conta encerrada
História: AB#105962

fix(105962): Exibição conta encerrada

---

src/componentes/Globais/Dashborard/SelectConta.js

Agora a label de conta encerrada irá aparecer corretamente em resumo dos recursos

Merge fix/105962 em hotfix/8.10.1

---

src/assets/css/styles.scss
src/componentes/Globais/GestaoDeUsuarios/components/ModalConfirmacaoRemoverAcesso.js
src/componentes/Globais/ModalAntDesign/modal-antdesign.scss
src/componentes/Globais/ModalAntDesign/modalRemoverAcessoUsuario.js

Esse PR:
- Altera os modais de remoção de usuário para cada visão, incluindo a observação na visão de DRE e SME.
História: AB#102479

feat(102479): Modifica modais de remocao de usuario

---

src/componentes/escolas/Receitas/Formularios/index.js

Esse PR:
- Corrige edição do crédito não exibe conta encerrada
- 
História: AB#105959

fix(105959): Edição do crédito: Após a confirmação de encerramento da conta, a conta deixou de ser exibida na edição de crédito

---

Jenkinsfile
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/CardSaldoEncerramentoConta.js

fix(106046): exibir info encerramento conta
Esse PR:
- Ajusta condição para exibir informações de encerramento
História: AB#106046

fix(106046): exibir info encerramento conta

---

src/componentes/Globais/ModalAntDesign/modal-antdesign.scss
src/componentes/Globais/ModalAntDesign/modalAviso.js
src/componentes/dres/Associacoes/DadosDasAssociacoes/DadosDasContas/InfosContas.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js

Esse PR:
- Corrige textos dos modais.
- Organiza componente de modal para maior usabilidade.
História: AB#106271

fix(106271): Ajusta textos dos modais

---

src/componentes/escolas/Associacao/DadosDasContas/index.js
src/utils/FormataData.js

fix(106264): Solicitação encerramento
Esse PR:
- Ajusta formatação da data informada
História: AB#106264

fix(106264): Solicitação encerramento

---

src/componentes/escolas/PrestacaoDeContas/index.js

Esse PR:
- Corrige não é possível concluir pc
História: AB#106869

fix(106869): Prestação de contas: Não é possível gerar a PC ou concluir acertos

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js

Esse PR:
- Corrige a palavra "Obervação" para "Observação" na análise de PC.
Resolve AB#105960

fix(105960): Corrige escrita errada

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/BotoesAvancarRetroceder.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/Cabecalho.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ComentariosDeAnalise.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ComentariosDeAnaliseNotificados.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/FormRecebimentoPelaDiretoria.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/TrilhaDeStatus/TrilhaDeStatusAprovada.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/TrilhaDeStatus/TrilhaDeStatusDevolvidaParaAcertos.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/TrilhaDeStatus/TrilhaDeStatusEmAnalise.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/TrilhaDeStatus/TrilhaDeStatusNaoRecebida.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/TrilhaDeStatus/TrilhaDeStatusRecebida.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContasNaoApresentada/index.js
src/componentes/dres/PrestacaoDeContas/ModalDeleteComentario.js
src/componentes/dres/PrestacaoDeContas/ModalEditarDeletarComentario.js
src/componentes/dres/PrestacaoDeContas/ModalNotificarComentarios.js

Esse PR:
- Adiciona os da-qa-ids para as telas de acompanhamento de pcs em não recebidas e aguardando análise.
História: AB#106052

feat(106052): Adiciona ids data-qa

---

src/componentes/Globais/GestaoDeUsuariosAdicionarUnidade/components/FiltroDeUnidades.js
src/componentes/Globais/GestaoDeUsuariosAdicionarUnidade/components/ListaDeUnidades.js
src/componentes/Globais/GestaoDeUsuariosAdicionarUnidade/components/Paginacao.js
src/componentes/Globais/GestaoDeUsuariosAdicionarUnidade/components/TopoComBotao.js
src/componentes/Globais/GestaoDeUsuariosAdicionarUnidade/context/GestaoUsuariosAdicionarUnidadeProvider.js
src/componentes/Globais/GestaoDeUsuariosAdicionarUnidade/hooks/useIncluirUnidade.js
src/componentes/Globais/GestaoDeUsuariosAdicionarUnidade/hooks/useUnidadesDisponiveisInclusao.js
src/componentes/Globais/GestaoDeUsuariosAdicionarUnidade/index.js
src/componentes/Globais/GestaoDeUsuariosAdicionarUnidade/style/gestao-usuarios-adicionar-unidade.scss
src/componentes/Globais/GestaoDeUsuariosForm/components/BarraTopoListagem.js
src/componentes/Globais/GestaoDeUsuariosForm/components/GestaoDeUsuariosFormMain.js
src/componentes/Globais/GestaoDeUsuariosForm/components/UnidadesUsuario.js
src/componentes/Globais/GestaoDeUsuariosForm/context/UnidadesUsuarioProvider.js
src/componentes/Globais/GestaoDeUsuariosForm/hooks/useUnidadesUsuario.js
src/componentes/Globais/GestaoDeUsuariosForm/style/gestao-de-usuarios-form.scss
src/rotas/index.js
src/services/GestaoDeUsuarios.service.js

feat(100139): Gestão usuários
Esse PR:
- Adiciona página para incluir unidades na visão SME
- Adiciona rota para acessar a nova página
- Adiciona components da nova página
- Adiciona serviços da nova pagina
História: AB#100139

feat(100139): Gestão usuários

---

src/paginas/escolas/MembrosDaAssociacao/index.js

Esse PR:
- Implementa feature flags em histórico de membros
História: AB#106375

feat(106375): Usar Feature Flag na funcionalidade de Histórico de Membros

---

src/componentes/Globais/SidebarLeft/getUrls.js
src/componentes/Globais/SidebarLeft/index.js
src/rotas/index.js

Esse PR:
- Adiciona nas rotas de usuário a feature-flag de gestão de usuários.
- Adiciona na sidebar a feature-flag de gestão de usuários.
História: AB#106378

tec(106378): Adiciona feature flag na gestao de usuarios

---

package-lock.json
package.json
src/componentes/escolas/Receitas/Formularios/index.js

Esse PR:
- Atualiza hotfix 8.11.2 em develop

Merge hotfix 8 11 2 em develop

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js

Esse PR:
- Adiciona validação por período no alerta de criação de acerto 
História: AB#107654

feat(107654): Adiciona validação por período no alerta de criação de acerto 

---

src/componentes/escolas/PrestacaoDeContas/index.js

Esse PR:
- Altera a página de Geração de PC passa a considerar também o novo status 'A processar' para a exibição do loading
da página.
Atende AB#103830

 feat(103830): Considera o status "A Processar" em PCs

---

src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js

Esse PR:
- Altera a seleção de contas encerradas na edição e inclusão de gastos.
História: AB#107877

fix(107877): Corrige apresentacao selecao contas encerradas despesas

---

src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
src/componentes/escolas/Receitas/Formularios/index.js

Esse PR
- Permite incluir ou editar crédito com a conta encerrada quando origem for Analise DRE
História: AB#107828

feat(107828): Análise DRE: Edição/Inclusão de crédito quando existe um pedido de encerramento para a conta bancária

---

package-lock.json
package.json

Esse PR:
- Atualiza dependências
História: AB#107737

tec(107737): Atualização de versão - Preparação para o NodeJS 14.21.3 --> 15.14.0 - reactstrap da versão 8.4.0 para 9.2.1

---

package-lock.json
package.json
src/componentes/escolas/PrestacaoDeContas/index.js

Posição em Develop 16/11/2023 às 08:36h

---

src/componentes/Globais/GestaoDeUsuariosForm/components/GestaoDeUsuariosFormMain.js
src/componentes/Globais/GestaoDeUsuariosForm/components/GruposAcesso.js
src/componentes/Globais/GestaoDeUsuariosForm/hooks/useDesabilitarAcesso.js
src/componentes/Globais/GestaoDeUsuariosForm/hooks/useDesabilitarGrupoAcesso.js
src/componentes/Globais/GestaoDeUsuariosForm/hooks/useGruposDisponiveisAcesso.js
src/componentes/Globais/GestaoDeUsuariosForm/hooks/useHabilitarAcesso.js
src/componentes/Globais/GestaoDeUsuariosForm/hooks/useHabilitarGrupoAcesso.js
src/componentes/Globais/GestaoDeUsuariosForm/hooks/useUnidadesUsuario.js
src/componentes/Globais/GestaoDeUsuariosForm/style/grupos-acesso.scss
src/services/GestaoDeUsuarios.service.js

Esse PR:
- Adiciona a lista de grupos de acessos na gestao de usuários;
- Adiciona rotas para habilitar e desabilitar grupos de acesso;
História: AB#98106

feat(98106): Adiciona grupos de acesso na gestão de usuários

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
src/componentes/escolas/Receitas/Formularios/index.js

Esse PR faz merge com as seguintes histórias:
AB#107877, AB#107828 e AB#108395
História: AB#108929

Merge hotfixes sprint 77

---

src/componentes/Globais/ModalBootstrap/index.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
src/utils/Modais.js

feat(108438) Saldo negativo em ação
Esse PR:
- Altera modal para considerar parametro de permitir saldo negativo
História: AB#108438

feat(108438) Saldo negativo em ação

---

src/componentes/escolas/Receitas/Formularios/index.js

Esse PR:
- Corrige regra para mostrar conta encerrada em inclusão e análise DRE
- Resolve conflito
Histórias: AB#108779, AB#108891

fix(108779, 108891): Corrige regra para mostrar conta encerrada em inclusão e análise DRE no formulário de crédito

---

src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
src/componentes/escolas/Receitas/Formularios/index.js

fix(108565): Impossivel alterar repasse
Esse PR:
- Ajusta condição para identificar se uma despesa é repasse
História: AB#108565

fix(108565): Impossivel alterar repasse

---

src/utils/Modais.js

feat(108438): Ajuste de texto
Esse PR:
- Realiza ajuste de texto na modal
História: AB#108438

feat(108438): Ajuste de texto

---

src/componentes/escolas/MembrosDaAssociacao/YupSignupSchemaHistoricoDeMembros.js
src/componentes/escolas/MembrosDaAssociacao/components/CargosDaComposicaoList.js
src/componentes/escolas/MembrosDaAssociacao/components/FormCadastro.js
src/componentes/escolas/MembrosDaAssociacao/components/TopoComBotoesFormCadastroHistoricoDeMembros.js
src/componentes/escolas/MembrosDaAssociacao/hooks/useGetCargosDaComposicao.js
src/componentes/escolas/MembrosDaAssociacao/hooks/useGetCargosDiretoriaExecutiva.js
src/componentes/escolas/MembrosDaAssociacao/hooks/useGetComposicao.js
src/componentes/escolas/MembrosDaAssociacao/hooks/usePatchStatusPresidente.js
src/componentes/escolas/MembrosDaAssociacao/hooks/usePostCargoDaComposicao.js
src/componentes/escolas/MembrosDaAssociacao/hooks/usePutCargoDaComposicao.js
src/componentes/escolas/MembrosDaAssociacao/membros-da-associacao.scss
src/componentes/escolas/MembrosDaAssociacao/pages/PaginaCadastroHistoricoDeMembros.js
src/rotas/index.js
src/services/Mandatos.service.js

Esse PR:
- Implementa inclusão de novo membro no histórico de membros - Em Homologação

feat(106047): Dados da Associação: Membros: Incluir novo membro no cargo vago (primeira composição do mandato vigente)

---

package.json
src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/BarraStatusEncerramentoConta.js
src/componentes/escolas/Receitas/Formularios/index.js

Esse PR:
- Corrige a data e hora  na mensagem de solicitação de encerramento enviada nas contas da associação.
Corrige AB#109755

fix(109755) Corrige exibição da data/hora da última solicitação de encerramento da conta

---

src/componentes/escolas/MembrosDaAssociacao/components/CargosDaComposicaoList.js
src/componentes/escolas/MembrosDaAssociacao/components/FormCadastro.js
src/componentes/escolas/MembrosDaAssociacao/components/TopoComBotoesFormCadastroHistoricoDeMembros.js
src/componentes/escolas/MembrosDaAssociacao/hooks/usePostCargoDaComposicao.js
src/componentes/escolas/MembrosDaAssociacao/hooks/usePutCargoDaComposicao.js
src/componentes/escolas/MembrosDaAssociacao/pages/PaginaCadastroHistoricoDeMembros.js

Esse PR:
- Implementa edição de Membro no Histórico de Membros - Em Homologação

feat(106054): Dados da associação: Editar membro no cargo preenchido (primeira composição do mandato vigente)

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/index.js

fix(109652): Corrige a verificacao do periodo na funcao contaEncerrada

---

src/componentes/escolas/PrestacaoDeContas/ModalGerarPrevia.js

Esse PR:
- Resolve warnings celery geração de PC
História: AB#110267

fix(110267): Investigar e resolver mensagens anormais nos logs de celery

---

src/utils/Modais.js

Esse PR:
- Modifica modal de apresentação de saldo insuficiente.
História: AB#109692

feat(109692): Adiciona verificacao conta quando saldo insuficiente

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/ProcessosSei/ProcessoSeiPrestacaoDeContaForm.js
src/componentes/dres/Associacoes/DadosDasAssociacoes/ProcessosSei/ProcessosSeiPrestacaoDeContas.js

Esse PR:
- Bloqueia botão de exclusão de processo e adiciona tooltip com texto
- Adiciona modal de confirmação de edição de processo
História: AB#110070

feat(110070): Valida e bloqueia exclusão de processo associação

---

src/componentes/escolas/PrestacaoDeContas/TopoSelectPeriodoBotaoConcluir.js
src/componentes/escolas/PrestacaoDeContas/index.js

Esse PR:
- Adiciona validação por conta para mostrar botão concluir pc/acerto
História: AB#110382

fix(110382): Adiciona validação por conta para mostrar botão concluir pc/acerto

---

src/componentes/escolas/MembrosDaAssociacao/components/FormCadastro.js
src/componentes/escolas/MembrosDaAssociacao/hooks/usePutCargoDaComposicao.js

feat(36588): Altera formulario edição membros
Esse PR:
- Adiciona condição para desabilitar as datas do formulario
- Adiciona validação as datas do formulario
História: AB#36588

feat(36588): Altera formulario edição membros

---

src/componentes/Globais/ModalAntDesign/modalAlterarSEI.js
src/componentes/dres/Associacoes/DadosDasAssociacoes/ProcessosSei/ProcessoSeiRegularidade.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/BotoesAvancarRetroceder.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/InformacoesPrestacaoDeContas.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
src/utils/ProcessoSeiMask.js

Esse PR:
- Adiciona modal de alteração de processo SEI no recebimento de PC.
História: AB#108442

feat(108442): Adiciona bloco de processo SEI acomp PC

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/BotoesAvancarRetroceder.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js

Esse PR:
- Corrige a apresentação da tooltip do botão de receber PC.
História: AB#108442

feat(108442): Corrige apresentao tooltip

---

src/componentes/Globais/Cabecalho/ModalInfoPerdeuAcesso.js
src/componentes/Globais/Cabecalho/index.js
src/componentes/Globais/ModalBootstrap/index.js
src/context/Notificacoes/index.js
src/paginas/Login/LoginForm.js
src/services/auth.service.js

feat(91614): Login gestão usuarios
Esse PR:
- Adiciona loading a tela de login
- Adiciona modal para listar unidades que perdeu acesso
História: AB#91614

feat(91614): Login gestão usuarios

---

src/componentes/Globais/ModalAntDesign/modalAlterarSEI.js

Esse PR:
- Altera os textos dos botões no modal.
História: AB#108442

feat(108442): Altera texto modal

---

src/componentes/Globais/Modal/ModalConfirm.js
src/componentes/escolas/MembrosDaAssociacao/hooks/usePutCargoDaComposicao.js
src/componentes/escolas/MembrosDaAssociacao/pages/PaginaCadastroHistoricoDeMembros.js

- Checa mudança da data fim da ocupação para sugerir inclusão de novo membro
História: AB#105420

feat(105420): Implementa checagem mudança data fim ocupação para sugerir incluir novo membro

---

src/componentes/Globais/GestaoDeUsuariosForm/components/GruposAcesso.js
src/componentes/Globais/GestaoDeUsuariosForm/components/UnidadesUsuario.js
src/componentes/Globais/GestaoDeUsuariosForm/hooks/useGruposDisponiveisAcesso.js
src/services/GestaoDeUsuarios.service.js

Esse PR:
- Corrige listagem de unidades na qual os grupos de acesso usavam como base.
- Corige serviço de listagem de grupos.
- Adiciona mensagem para tela de adição de usuário.
História: AB#109200

fix(109200): Corrige apresentacao e edicao unidades gestao usauarios

---

src/componentes/escolas/MembrosDaAssociacao/components/FormCadastro.js
src/componentes/escolas/MembrosDaAssociacao/pages/PaginaCadastroHistoricoDeMembros.js

- Corrige retorno de cargo para que data final da ocupação seja igual a data final do mandato na criação
- Corrige validação de campo final ocupação para que fique desabilitado na criação
História: AB#105420

feat(105420): Ajusta checagem do campo final ocupação

---

src/assets/css/styles.scss
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/FormRecebimentoPelaDiretoria.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/InformacoesPrestacaoDeContas.js
src/componentes/dres/PrestacaoDeContas/PendeciasRecebimento/index.js

- Adiciona lista de pendências para o recebimento 
- Adiciona sinalização de campos obrigatórios
História: AB#110831

feat(110831): Adiciona lista de pendências para o recebimento e adiciona sinalização de campos obrigatórios

---

src/componentes/dres/PrestacaoDeContas/PendeciasRecebimento/index.js
src/services/dres/PrestacaoDeContas.service.js

- Implementa lógica de envio de notificação
História: AB#110895

feat(110895): Implementa lógica de envio de notificação

---

src/componentes/escolas/MembrosDaAssociacao/pages/PaginaCadastroHistoricoDeMembros.js

- Altera chamada de campo na edição de membro
História: AB#105420

feat(105420): Altera chamada de campo na edição de membro

---

src/componentes/dres/PrestacaoDeContas/PendeciasRecebimento/index.js

- Desabilita botão de enviar notificação após envio
História: AB#110895

feat(110895): Melhora feedback ao usuário após enviar notificação

---

src/componentes/escolas/PrestacaoDeContas/index.js
src/services/escolas/PrestacaoDeContas.service.js

Esse PR:
- Adiciona feature flag a checagem de status da PC
- Adiciona feature flag a chamada do endpoint de concluir PC
- Adiciona novos status da PC a checagem de status
História: AB#110921

feat(110921): Novo processo pc

---

src/componentes/escolas/MembrosDaAssociacao/hooks/useGetStatusCadastroAssociacao.js
src/componentes/escolas/MembrosDaAssociacao/index.js

Esse PR:
- Insere validação para exibição de ícone de pendência no Histórico de Membros em Homologação

feat(108697): Histórico de Membros - Inserir ícone de membro faltante no mandato vigente

---

src/componentes/Globais/GestaoDeUsuariosForm/components/FormUsuario.js

- Corrige payload salvar usuário em criação de novo usuário
História AB#110204

fix(110204): Corrige payload salvar usuário

---

src/componentes/escolas/Receitas/Formularios/index.js

- Corrige retorno de contas em cadastro de crédito
História AB#110432

fix(110432): Corrige retorno de contas em cadastro de crédito

---

src/componentes/dres/ValoresReprogramadosDre/TabelaValoresReprogramados.js

fix(111683): Exibição contas de acordo com parametro

---

package-lock.json
package.json
src/componentes/ChamaTypescriptFirstComponent.tsx
src/componentes/TypescriptFirstComponent.tsx
src/react-app-env.d.ts
src/rotas/index.js
tsconfig.json

Esse PR:
- Adiciona, configura e cria POC Typescript
História: AB#108097

tec[108097]: Implementar Typescript ao front

---

src/componentes/Globais/EscolheUnidade/index.js
src/componentes/Globais/Modal/ModalConfirm.js
src/componentes/Globais/SuporteAsUnidades/SuporteAsUnidadesV2.js
src/componentes/Globais/SuporteAsUnidades/components/UnidadesEmSuporte/ListaUnidadesEmSuporte.js
src/componentes/Globais/SuporteAsUnidades/components/UnidadesEmSuporte/hooks/useRemoverSuporte.js
src/componentes/Globais/SuporteAsUnidades/components/UnidadesEmSuporte/hooks/useUnidadesEmSuporte.js
src/componentes/Globais/SuporteAsUnidades/useAdicionarSuporte.js
src/paginas/SME/SuporteAsUnidades/index.js
src/paginas/dres/SuporteAsUnidades/index.js
src/services/auth.service.js

- Implementa condição para novo suporte as unidades
- Implementa tabela de unidades em suporte com paginação 
- Adiciona botão para login-suporte
- Implementa toasts de validação e ajusta texto do modal de confirmação
História: AB#110667

feat(110667): Novo suporte as unidades

---

src/componentes/Globais/SuporteAsUnidades/components/UnidadesEmSuporte/ListaUnidadesEmSuporte.js
src/componentes/Globais/SuporteAsUnidades/components/UnidadesEmSuporte/hooks/useRemoverSuporte.js
src/services/auth.service.js
src/utils/Loading.js

- Implementa ação em lote na tabela
História: AB#110945

feat(110945): Implementa ação em lote na tabela

---

src/componentes/dres/PrestacaoDeContas/ModalConcluirAnalise.js

- Altera campo status selecionáveis conclusão de PC
História: AB#111928

tec(111928): Altera campo status selecionáveis conclusão de PC

---

src/componentes/sme/AcompanhamentoPcsSmePorDre/FiltroUnidadeEducacional.js

fix(112854): Layout filtro
Esse PR:
- Adiciona classe ao input
História: AB#112854

fix(112854): Layout filtro

---

src/assets/css/styles.scss
src/assets/css/variaveis.scss
src/componentes/escolas/MembrosDaAssociacao/components/CargosDaComposicaoList.js
src/componentes/escolas/MembrosDaAssociacao/components/FormCadastro.js
src/componentes/escolas/MembrosDaAssociacao/pages/PaginaCadastroHistoricoDeMembros.js

- Atribui valores aos campos substituido e substituto
- Adiciona etiquetas de acordo com informação do membro
História: AB#105263

feat(105263): Adiciona etiquetas de acordo com informação do membro

---

src/componentes/escolas/MembrosDaAssociacao/components/CargosDaComposicaoList.js

- Adiciona etiqueta para conselho fiscal
História: AB#105263

feat(105263): Adiciona etiqueta para conselho fiscal

---

src/componentes/escolas/PrestacaoDeContas/index.js

Esse PR:
- Permite concluir a pc mesmo que as tentativas de falhas tenham excedido o parâmetro de tentativas;
História: AB#112558

feat(112558): Permite concluir pc com tentativas excedidas

---

src/componentes/Globais/BarraMensagemUnidadeEmSuporte/ModalConfirmaEncerramentoSuporte.js
src/componentes/Globais/BarraMensagemUnidadeEmSuporte/index.js
src/paginas/PaginasContainer.js

Esse PR:
- Adiciona faixa de acesso suporte;
História: AB#110668

feat(110668): Adiciona faixa de acesso suporte

---

package-lock.json
package.json
src/componentes/Globais/BarraMensagemUnidadeEmSuporte/index.js
src/componentes/Globais/ReactNumberFormatInput/index.js
src/componentes/Globais/ValoresReprogramados/ValoresReprogramadosFormFormik.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertosDevolucaoAoTesouro.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroSaidaForm.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js

Esse PR:
- Remove lib react-currency-input desatualizada;
- Remove lib react-intl-currency-input desatualizada;
- Passa os campos montarios para a biblioteca ja utilizada no sistema react-number-format;
História: AB#107738

tec(107738): Atualiza lib utilizada para campos monetarios

---

src/componentes/Globais/GestaoDeUsuariosList/components/ListaUsuarios.js
src/componentes/Globais/TableTags/tableTags.scss

feat(113377): Inclui tag acesso SME
Esse PR:
- Adiciona tag de acesso concedido SME a listagem de usuarios
História: AB#113377

feat(113377): Inclui tag acesso SME

---

src/componentes/escolas/MembrosDaAssociacao/components/FormCadastro.js
src/paginas/escolas/MembrosDaAssociacao/index.js

Esse PR:
- Corrige não exibir dados pessoais para cargos diferente do Presidente
História: AB#110991

fix(110991): Histórico de Membros - Não exibir dados pessoais para cargos diferente do Presidente

---

src/componentes/sme/Mandatos/components/Lista.js
src/componentes/sme/Mandatos/components/ModalForm.js
src/componentes/sme/Mandatos/context/Mandatos.js
src/componentes/sme/Mandatos/hooks/useGetMandatos.js
src/componentes/sme/Mandatos/hooks/usePatchMandato.js
src/componentes/sme/Mandatos/hooks/usePostMandato.js

feat(108553): Parametrizacoes mandatos
Esse PR:
- Altera validações de data do formulaŕio
- Altera loading da página
História: AB#108553

feat(108553): Parametrizacoes mandatos

---

src/componentes/escolas/MembrosDaAssociacao/components/FormCadastro.js
src/componentes/escolas/MembrosDaAssociacao/components/ModalInformarSaidaDoCargo.js
src/componentes/escolas/MembrosDaAssociacao/components/TopoComBotoesFormCadastroHistoricoDeMembros.js
src/componentes/escolas/MembrosDaAssociacao/pages/PaginaCadastroHistoricoDeMembros.js

- Adiciona modal para solicitar saída do membro
História: AB#112659

feat(112659): Saída do membro

---

src/componentes/escolas/GeracaoDaAta/BarraAvisoPreencerData/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/ModalApagarParticipantesAta.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/NovoFormularioEditaAta/YupSignupSchemaAta.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/NovoFormularioEditaAta/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/index.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
src/componentes/escolas/GeracaoDaAta/geracao-da-ata.scss
src/services/Mandatos.service.js
src/services/escolas/PresentesAta.service.js

Esse PR:
- Adiciona componente para apresentar membros da comissão na ata;
- Altera layout da edição e visualização da ata;
História: AB#105234

feat(105234): Altera exibição membros ata

---

src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/RelatorioAposAcertos.js
src/services/escolas/PrestacaoDeContas.service.js

feat(104245): Permite regerar doc
Esse PR:
- Adiciona botão para regerar relatório
- Adiciona chamada a API para regerar relatório
História: AB#104245

feat(104245): Permite regerar doc

---

src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/NovoFormularioEditaAta/YupSignupSchemaAta.js
src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/NovoFormularioEditaAta/index.js
src/services/escolas/PresentesAta.service.js

Esse PR:
- Adiciona o resgate de membros pelo identificador caso exista uma composição na ata;
- Corrige Schema do novo componente de listagem de ocupantes da ata;
História: AB#105234

feat(105234): Adiciona resgate membros por identificador

---

src/componentes/Globais/BarraMensagemFixa/context/BarraMensagemFixaProvider.js
src/componentes/Globais/BarraMensagemFixa/index.js
src/componentes/escolas/MembrosDaAssociacao/hooks/usePostCargoDaComposicao.js
src/componentes/escolas/MembrosDaAssociacao/hooks/usePutCargoDaComposicao.js
src/paginas/PaginasContainer.js

feat(102526) Faixa informativa
Esse PR:
- Adiciona componente para a faixa informativa
- Adiciona contexto para faixa informativa
- Adiciona condição para exibição da faixa informativa (visão UE e flag historico-de-membros)
História: AB#102526

feat(102526) Faixa informativa

---

src/componentes/Globais/SidebarLeft/getUrls.js

Esse PR:
- Corrige acesso de visualização de novos grupos criados
História: AB#115567

fix(115567): SME - Acesso visualização novos grupos

---

src/componentes/escolas/Associacao/ExportaDadosAssociacao/context/ExportaDadosAssociacao.js
src/componentes/escolas/MembrosDaAssociacao/components/CargosDaComposicaoList.js
src/componentes/escolas/MembrosDaAssociacao/index.js
src/componentes/escolas/MembrosDaAssociacao/pages/PaginaMandatoVigente.js
src/paginas/escolas/MembrosDaAssociacao/index.js

feat(113475): Exportar dados associacao
Esse PR:
- Adiciona context para controlar exibição do componente ExportaDadosDaAsssociacao
- Adiciona condicionais para exibir o componente
História: AB#113475

feat(113475): Exportar dados associacao

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDespesasPeriodosAnteriores/hooks/useGetDespesasPeriodosAnterioresParaConferencia.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDespesasPeriodosAnteriores/index.js

- Corrige atribuição conta ativa inicial 
História: AB#101259

feat(101259): Corrige atribuição conta ativa inicial

---

src/componentes/Globais/SidebarLeft/getUrls.js

fix(115567): Corrige acesso de visualização de novos grupos criados

---

src/componentes/escolas/PrestacaoDeContas/ModalAvisoAssinatura.js
src/componentes/escolas/PrestacaoDeContas/index.js

fix(115827): Modal pendencia assinatura
Esse PR:
- Utiliza função para controlar texto do botão
História: AB#115827

fix(115827): Modal pendencia assinatura

---

src/componentes/Globais/GestaoDeUsuariosList/components/AddUsuario.js

fix(116606): Corrige exibição grupo acesso
Esse PR:
- Remove query de grupos de acesso ao clicar em adicionar usuario
História: AB#116606

fix(116606): Corrige exibição grupo acesso

---

src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDespesasPeriodosAnteriores/TabelaAcertosDespesasPeriodosAnteriores.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDespesasPeriodosAnteriores/acertos-lancamentos.scss
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDespesasPeriodosAnteriores/index.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
src/services/dres/PrestacaoDeContas.service.js
src/services/mantemEstadoAnaliseDre.service.js

- Adiciona tabela de acertos despesas períodos anteriores
História: AB#114585

feat(114585): Adiciona tabela de acertos despesas períodos anteriores

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ComentariosDeAnalise.js

Esse PR:
- Corrige apresentação da listagem vazia de comentários da SME.
História: AB#107739

tec(107739): Corrige apresentacao lista comentarios vazia

---

src/componentes/Globais/GestaoDeUsuariosForm/components/FormUsuario.js

fix(117181): Corrige vinculo visao SME
Esse PR:
- Adiciona validação ao payload
História: AB#117181

fix(117181): Corrige vinculo visao SME

---

src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/index.js
src/services/dres/PrestacaoDeContas.service.js

fix(117419): Filtros PCs
Esse PR:
- Adiciona filtro de status a chamada da API
História: AB#117419

fix(117419): Filtros PCs

---

src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js

Esse PR:
- Cria opção de não incluir um rateio capital na relação de bens.
Atende AB#116392

feat(116392): Opção de não incluir rateios capital na relação de bens

---

src/componentes/Globais/EscolheUnidade/ListaDeUnidades.js

Esse PR:
- Resolve dica de tela em viabilizar acesso
História: AB#117568

fix(117568): Gestão de usuários: Suporte ás unidades: Dica de tela "Viabilizar acesso" não está sendo exibida

---

src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDespesasPeriodosAnteriores/TabelaAcertosDespesasPeriodosAnteriores.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDespesasPeriodosAnteriores/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TabsConferenciaAtualHistorico.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TopoComBotoes.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js

- Ajuste no fluxo de resumo de acertos
História: AB#114585

feat(114585): Ajuste no fluxo de resumo de acertos

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js

- Ajuste na atualização da tela em resumo de acertos após navegação e retorno a tela.
História: AB#114585

feat(114585): Ajuste no resumo de acertos

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js

- Ajuste tabs resumo de acerto
História: AB#114585

feat(114585): Ajuste tabs resumo de acerto

---

src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js

- Corrige edição de ação no formulário de crédito
História: AB#117803

fix(117803): Corrige edição de ação no formulário de crédito

---

src/componentes/Globais/CentralDeDownloads/FormFiltrosDownloads.js
src/componentes/Globais/CentralDeDownloads/TabelaDownloads.js
src/componentes/Globais/ExtracaoDados/index.js

feat(117659): Central de downloads
Esse PR:
- Adiciona nova coluna a tabela
- Adiciona dica de tela
História: AB#117659

feat(117659): Central de downloads

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
src/services/dres/PrestacaoDeContas.service.js

feat(117548): Conferencia de lancamentos
Esse PR:
- Altera função de seleção em massa
História: AB#117548

feat(117548): Conferencia de lancamentos

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/ProcessosSei/ProcessoSeiPrestacaoDeContaForm.js
src/componentes/dres/Associacoes/DadosDasAssociacoes/ProcessosSei/ProcessosSeiPrestacaoDeContas.js
src/componentes/dres/Associacoes/associacoes.scss
src/services/dres/ProcessosAssociacao.service.js

Esse PR:
- Inclui períodos ao processo SEI
História: AB#117484

feat(117484): Associações: Processos SEI: Incluir período relacionado ao Processo SEI

---

src/componentes/Globais/ExtracaoDados/Cards.js

feat(117716): Extração dados repasse
Esse PR:
- Adiciona card para extrair dados repasse
História: AB#117716

feat(117716): Extração dados repasse

---

src/componentes/Globais/ModalAntDesign/modalAlterarSEI.js

Esse PR:
- Passa a exibir processo SEI vinculado
História: AB#117542

feat(117542): Acompanhamento de PC: Exibir processo SEI do período vinculado

---

src/componentes/Globais/ExtracaoDados/Cards.js
src/componentes/Globais/ModalAntDesign/modalAlterarSEI.js

Posição em Develop 26/03/2024 às 08:07h

---

src/componentes/dres/Associacoes/associacoes.scss

Esse PR:
- Realiza ajustes no span de exibição de períodos - Homologação

feat(117484): Associações: Processos SEI: Incluir período relacionado ao Processo SEI - Parte 02

---

src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/RelatorioAposAcertos.js
src/services/escolas/PrestacaoDeContas.service.js

- Adiciona fluxo condicional para regerar relatório após acerto
História: AB#117529

fix(117529): Adiciona fluxo condicional para regerar relatório após acerto

---

src/componentes/escolas/MembrosDaAssociacao/components/FormCadastro.js
src/componentes/escolas/MembrosDaAssociacao/components/ModalInformarSaidaDoCargo.js

- Adiciona campo extra de data fim ocupação em composições passadas
História: AB#118297

fix(118297): Adiciona campo extra de data fim ocupação em composições passadas

---

src/componentes/Globais/ExtracaoDados/Cards.js

Esse PR:
- Adiciona card de extracao de dados dos membros apm.
História: AB#117565

feat(117565): Adiciona extracao de dados membros apm

---

src/componentes/Globais/ExtracaoDados/Cards.js

Esse PR:
- Implementa extração de dados Status PC na visão DRE
História: AB#117454

feat(117454): Extração de dados: Incluir extração de dados de Prestações de contas: Status

---

src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaTransacoes/index.js

- Adiciona checagem permissao em conciliacao bancaria
História: AB#118505

fix(118505): Adiciona checagem de permissão em conciliação bancaria

---

src/componentes/sme/Mandatos/components/ModalForm.js
src/componentes/sme/Mandatos/components/TopoComBotoes.js
src/rotas/index.js

Esse PR:
- Implementa permissão de alterar painel de parametrizações - períodos de mandato
História: [AB#118548](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118548)

feat(118548): Parametrizações: Períodos de mandato: Exibir as telas em modo visualização e/ou de edição conforme a permissão atribuída

---

src/componentes/Globais/Dashborard/index.js

Esse PR:
- Corrige o estado inicial do periodo na tela do dashboard do resumo de recursos.

tec(117512): Corrige estado inicial periodo

---

package-lock.json
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js

Esse PR:
- Cria feature flag que quando ligada habilita o estorno de despesas a partir de análises de PC.
Atende [AB#119111](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119111)

fix(119111): Cria flag "habilita-estorno-ajuste-despesa"

---

package-lock.json

Esse PR:
- Volta package-lock.json para o PR tec/117512-corrige-range-datepicker-att-antds-node

Atualiza PackageLock

---

src/componentes/escolas/Associacao/ExportaDadosAssociacao/index.js
src/componentes/escolas/MembrosDaAssociacao/RetornaSeTemPermissaoEdicaoHistoricoDeMembros.js
src/componentes/escolas/MembrosDaAssociacao/components/FormCadastro.js
src/componentes/escolas/MembrosDaAssociacao/components/TopoComBotoesFormCadastroHistoricoDeMembros.js
src/rotas/index.js

Esse PR:
- Implementa permissão edição Histórico de Membros
História: [AB#119230](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119230)

fix(119230): Incluir histórico de membros na permissão de Dados da Associação

---

src/componentes/escolas/Associacao/ExportaDadosAssociacao/index.js
src/componentes/escolas/MembrosDaAssociacao/RetornaSeTemPermissaoEdicaoHistoricoDeMembros.js
src/componentes/escolas/MembrosDaAssociacao/components/FormCadastro.js
src/componentes/escolas/MembrosDaAssociacao/components/TopoComBotoesFormCadastroHistoricoDeMembros.js
src/rotas/index.js

Corrige: [AB#119230](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119230)

fix(119230): Incluir aba histórico de membros na permissão de Dados da Associação

---

package.json
src/componentes/escolas/Associacao/ExportaDadosAssociacao/index.js
src/componentes/escolas/MembrosDaAssociacao/RetornaSeTemPermissaoEdicaoHistoricoDeMembros.js
src/componentes/escolas/MembrosDaAssociacao/components/FormCadastro.js
src/componentes/escolas/MembrosDaAssociacao/components/TopoComBotoesFormCadastroHistoricoDeMembros.js
src/rotas/index.js

Esse PR:
- Merge hotfix 9.2.1 em develop

Merge hotfix 9.2.1 em develop

---

src/componentes/Globais/ExtracaoDados/Cards.js

Esse PR:
- Inclui a extração de devolução ao tesouro na visão de DRE
[AB#118384](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118384)

feat(118384): Add extração devolução tesouro em DRE

---

src/componentes/Globais/ArquivosDeCarga/BotoesTopo.js
src/componentes/Globais/ArquivosDeCarga/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/BtnAddAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/ModalFormAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/TabelaAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js
src/rotas/index.js
src/services/sme/Parametrizacoes.service.js

feat(118528) Parametrizacoes associacoes
Esse PR:
- Altera endpoint para listagem
- Adiciona controle de permissão a pagina
História: [AB#118528](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118528)

feat(118528) Parametrizacoes associacoes

---

src/componentes/sme/Parametrizacoes/Estrutura/Tags/BtnAddTags.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/ModalFormTags.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/index.js
src/rotas/index.js

feat(118543): Parametrizacoes tags
Esse PR:
- Adiciona controle de permissões a pagina
- Adiciona informação de campo obrigatório
- Adiciona toast para inclusão, edição e exclusão
História: [AB#118543](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118543)

feat(118543): Parametrizacoes tags

---

src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/components/ModalForm.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/components/TopoComBotoes.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/hooks/useDeleteMotivoRejeicao.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/hooks/usePatchMotivoRejeicao.js
src/componentes/sme/Parametrizacoes/Estrutura/MotivosRejeicaoEncerramentoConta/hooks/usePostMotivoRejeicao.js
src/rotas/index.js

feat(118549): Parametrizações motivos rejeicao
Esse PR:
- Adiciona controle de permissão
História: [AB#118549](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118549)

feat(118549): Parametrizações motivos rejeicao

---

package-lock.json
src/componentes/Globais/ExtracaoDados/Cards.js

Esse PR:
- Implementa Dre Extração de Dados - Repasses
História: [AB#117717](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/117717)

feat(117717): Extração de dados: Incluir extração de dados Repasses e exibir o filtro aplicado na Central de downloads

---

src/componentes/sme/Parametrizacoes/Despesas/Fornecedores/BtnAddFornecedores.js
src/componentes/sme/Parametrizacoes/Despesas/Fornecedores/ModalFormFornecedores.js
src/componentes/sme/Parametrizacoes/Despesas/Fornecedores/index.js
src/rotas/index.js

feat(118551): Parametrizacoes Fornecedores
Esse PR:
- Adiciona controle de permissão a pagina
História: [AB#118551](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118551)

feat(118551): Parametrizacoes Fornecedores

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/ProcessosSei/ProcessoSeiPrestacaoDeContaForm.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/AutoCompleteAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/BtnAddAcoes.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/ModalFormAcoesDasAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/TabelaAcoesDasAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/index.js
src/rotas/index.js
src/services/sme/Parametrizacoes.service.js

Esse PR:
- Adiciona permissão nas ações da associaçãoes;
- Adiciona paginação na tabela de ações da associaçãoes;
- Adiciona asteriscos de campos obrigatórios de edição e adição de ação de associação;
- Adiciona mensagens de sucesso na edição, exclusão e adição de ações de associação.
História: [AB#118536](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118536)

feat(118536): Adiciona permissão, paginação e dados de formulário na parametrização de ações das associações

---

src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/ModalFormDocumento.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/index.js
src/rotas/index.js

feat(118555): Parametrizacoes tipos acertos documento
Esse PR:
- Adiciona controle de permissões a pagina
História: [AB#118555](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118555)

feat(118555): Parametrizacoes tipos acertos documento

---

src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/BtnAdd.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/ModalForm.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/index.js
src/rotas/index.js

Esse PR:
- Adiciona permissão de acesso e edição na parametrização;
- Adiciona mensagens na edição, remoção e cadastro;
- Adiciona informações de obrigatoriedade no formulário de cadastro e edição.
História: [AB#118550](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118550)

feat(118550): Adiciona permissão na parametrização de tipos de despesa de custeio

---

src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/NovoFormularioEditaAta/index.js

Esse PR:
- Corrige o layout dos toogles dos membros da ata.
História: [AB#119647](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119647)

fix(119647): Corrige layout membros ata

---

src/services/sme/Parametrizacoes.service.js

Esse PR:
- Resolve Filtrar por Informações em Parametrizações Associação
Historia: [AB#119436](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119436)

fix(119436): Parametrizações: Associações: Filtro de informações não filtra as opções selecionadas

---

src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/NovoFormularioEditaAta/index.js
src/componentes/sme/Parametrizacoes/EdicaoDeTextos/FiqueDeOlho/index.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/AutoCompleteAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/ModalFormAcoesDasAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesDasAssociacoes/index.js
src/services/sme/Parametrizacoes.service.js

História: [AB#118225](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118225)

Posição em Develop 12/04/2024 às 12:02

---

src/componentes/Globais/ExtracaoDados/Cards.js

feat(118381): Extracao dados creditos
Esse PR:
- Adiciona extração a visão de DRE
História: [AB#118381](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118381)

feat(118381): Extracao dados creditos

---

package-lock.json
package.json

Esse PR:
- Atualiza Sprint 87 em Develop

Release 9.3.0 -> Develop

---

src/componentes/sme/PainelParametrizacoes/index.js

Esse PR:
- Remove card usuários de parametrizações
História: [AB#119724](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119724)

feat(119724): Parametrizações: Usuários: Remover o card de Usuários e o título Gestão SME

---

src/componentes/sme/PainelParametrizacoes/index.js

Esse PR:
- Remove card usuários de parametrizações - Homolog

feat(119724): Remove card usuários de parametrizações

---

src/componentes/sme/Parametrizacoes/Estrutura/Acoes/ModalFormAcoes.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/index.js

- Modo visualização na parametrização de ação.
História: [AB#118544](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118544)

feat(118544): Modo visualização na parametrização de ação.

---

src/componentes/sme/Parametrizacoes/Estrutura/Acoes/AssociacoesDaAcao/index.js

- Modo visualização na parametrização de associações da ação
História: [AB#120123](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120123)

feat(120123): Modo visualização na parametrização de associações da ação

---

src/componentes/sme/Parametrizacoes/Estrutura/Acoes/VinculaAssociacoesAAcao/index.js

- Modo visualização na parametrização da página vincular ues
História: [AB#120124](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120124)

feat(120124): Modo visualização na parametrização da página vincular ues

---

src/componentes/sme/Parametrizacoes/Estrutura/Acoes/VinculaAssociacoesAAcao/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/index.js

História: [AB#119474](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119474)

Posição em Develop 23/04/2024 às 11:07h

---

src/componentes/Globais/ExtracaoDados/Cards.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/index.js

- Adiciona card extração processos sei pc
História: [AB#118499](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118499)

feat(118499): Adiciona card extração processos sei pc

---

src/componentes/Globais/ExtracaoDados/Cards.js

Esse PR:
- Cria extração de dados classificação das despesas visão DRE
História: [AB#118386](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118386)

feat(118386): Extração de dados: Incluir extração de Despesas: Classificação das despesas e exibir o filtro aplicado na Central de downloads

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/ProcessosSei/ProcessosSeiPrestacaoDeContas.js

Esse PR:
- Altera mensagens de validação do processo de PC
Atende [AB#119725](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119725)

feat(119725): Valida unicidade de processo associação

---

src/componentes/Globais/ExtracaoDados/Cards.js

- Adiciona permissão extração de ata para visão DRE
História: [AB#118385](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118385)

feat(118385): Adiciona permissão extração de ata para visão DRE

---

src/componentes/Globais/ExtracaoDados/Cards.js

Esse PR:
- Adiciona card de extração de dados do demonstrativo financeiro na visão DRE.
História: [AB#118387](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118387)

feat(118387): Adiciona card extracao demo financeiro na dre

---

src/componentes/Globais/ArquivosDeCarga/BotoesTopo.js
src/componentes/Globais/ArquivosDeCarga/index.js
src/componentes/Globais/GestaoDeUsuarios/utils/RetornaSeTemPermissaoEdicaoGestaoUsuarios.js
src/componentes/Globais/GestaoDeUsuariosForm/components/BarraTopoListagem.js
src/componentes/Globais/GestaoDeUsuariosForm/components/FormUsuario.js
src/componentes/Globais/GestaoDeUsuariosForm/components/GruposAcesso.js
src/componentes/Globais/GestaoDeUsuariosForm/components/UnidadesUsuario.js
src/componentes/Globais/GestaoDeUsuariosForm/style/gestao-de-usuarios-form.scss
src/componentes/Globais/GestaoDeUsuariosList/components/AddUsuario.js
src/componentes/Globais/GestaoDeUsuariosList/components/ListaUsuarios.js
src/componentes/Globais/GestaoDeUsuariosList/style/gestao-de-usuarios-list.scss
src/componentes/Globais/SidebarLeft/getUrls.js
src/rotas/index.js

feat(118558): Controle de permissao gestão usuários
Esse PR:
- Adiciona função que retorna se usuário tem permissão de edição a gestão de usuários de acordo com a visão selecionada
- Adiciona controle de permissão a página de gestão de usuários
História: [AB#118558](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118558)

feat(118558): Controle de permissao gestão usuários

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/ProcessosSei/ProcessoSeiPrestacaoDeContaForm.js
src/componentes/dres/Associacoes/DadosDasAssociacoes/ProcessosSei/ProcessosSeiPrestacaoDeContas.js

Esse PR:
- Adicione um loading para evitar a apresentação do ID dos períodos durante o carregamento dos períodos disponíveis no modal do processo SEI.
História: [AB#120324](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120324)

fix(120324): Adiciona loading periodos disponiveis processo SEI

---

src/componentes/Globais/ExtracaoDados/Cards.js

Esse PR:
- Implementa a extração de despesas na visão de DRE.
Atende [AB#118388](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118388)

feat(118388): Add extração de despesas em DRE

---

package-lock.json
package.json

Esse PR:
- Atualiza axios para a versão 0.27.2.
História: [AB#120999](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120999)

tec(120999): Atualiza axios

---

src/componentes/Globais/ArquivosDeCarga/Filtros.js
src/componentes/Globais/ArquivosDeCarga/index.js
src/componentes/sme/Parametrizacoes/Despesas/EspecificacoesMateriaisServicos/context/MateriaisServicos.js
src/componentes/sme/Parametrizacoes/Despesas/EspecificacoesMateriaisServicos/index.js
src/rotas/index.js

Esse PR:
- Adiciona a carga de especificações de serviços e materiais no painel de parametrização da SME.
História: [AB#29921](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/29921)

feat(29921): Adiciona carga de especificações de serviços e materiais no painel da sme

---

src/componentes/escolas/Receitas/CancelarModalReceitas.js
src/componentes/escolas/Receitas/Formularios/index.js

Esse PR:
- Padroniza o modal de cancelar criação de estorno;
- Altera retorno ao cancelar modal para a despesa de origem do estorno.
História: [AB#120457](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120457)

feat(120457): Altera modal cancelar estorno

---

src/componentes/Globais/ExtracaoDados/Cards.js

feat(118389): Extração contas dre
Esse PR:
- Adiciona card de extração a visao DRE
História: [AB#118389](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118389)

feat(118389): Extração contas dre

---

src/componentes/Globais/ArquivosDeCarga/ModalFormArquivosDeCarga.js
src/componentes/Globais/ArquivosDeCarga/YupSignupSchemaArquivosDeCarga.js
src/componentes/Globais/ArquivosDeCarga/index.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/UrlsMenuInterno.js
src/services/sme/Parametrizacoes.service.js

Esse PR:
- Adiciona a tabela de carga de repasses realizados e repasses previstos;
- Altera modal de cadastro e edição de carga para receber o período caso a carga exija.
História: [AB#33159](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/33159)

feat(33159): Inclui carga repasse no painel de parametrizacao

---

src/componentes/Globais/ArquivosDeCarga/index.js

Esse PR:
- Corrige a verificação do modal da necessidade de incluir o periodo;
História: [AB#33159](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/33159)

feat(33159): Corrige verificacao modal

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/ProcessosSei/ProcessoSeiPrestacaoDeContaForm.js

feat(121650): Processo SEI
Esse PR:
- Adiciona controle de permissão aos campos do formulário
História: [AB#121650](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/121650)

feat(122650): Processo SEI

---

package-lock.json
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
src/context/Despesa/index.js

Esse PR:
- Implementa despesas de períodos anteriores não editáveis
História: AB#121888

feat(121888): Gastos da Escola: Despesas de períodos anteriores ao uso do sistema após conclusão da PC não são editáveis

---

src/componentes/Globais/ArquivosDeCarga/ModalFormArquivosDeCarga.js
src/componentes/Globais/ArquivosDeCarga/YupSignupSchemaArquivosDeCarga.js
src/componentes/Globais/ArquivosDeCarga/index.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/components/Lista.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/components/ModalForm.js
src/services/sme/Parametrizacoes.service.js

Esse PR:
- Adiciona o campo tipo_de_conta no modal de repasses;
- Corrige modal de edição de cargas.
História: AB#121998

feat(121998): Altera campos e modal para receber o paramêtro de tipo de conta

---

src/componentes/Globais/ArquivosDeCarga/ModalFormArquivosDeCarga.js
src/componentes/Globais/ArquivosDeCarga/YupSignupSchemaArquivosDeCarga.js
src/componentes/Globais/ArquivosDeCarga/index.js

Esse PR:
- Altera verificação do conteúdo do arquivo na edição.
História: AB#121998

feat(121998): Modifica verificação do conteúdo do arquivo na edição

---

src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/components/ModalForm.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/components/TopoComBotoes.js

Esse PR:
- Altera labels no cadastro de repasses para "repasse previsto" em vez de apenas "repasse".
Atende história AB#121998

feat(121998): Ajusta titulo

---

src/componentes/Globais/ExtracaoDados/index.js
src/componentes/escolas/Receitas/Formularios/index.js

Correção do evento de limpeza do período de exportação de dados.

Atualiza Homolog

---

src/componentes/Globais/ExtracaoDados/index.js
src/componentes/escolas/Receitas/Formularios/index.js

Esse PR corrige os bugs AB#122298 e AB#122300

Hotfix 9.6.1

---

src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js

- Checa quantidade de despesas incompletas no fluxo de acertos para cenário pontual em que o usuário consegue preencher data inválida sem ativar validação.
História: AB#121675

fix(121675): Corrige validação de despesas incompletas no cenário de acertos

---

src/componentes/Globais/ExtracaoDados/Cards.js

Esse PR:
- Adiciona card de extração de dados de associação.
História: AB#124175

feat(124175): Extração de dados de associações

---

src/componentes/Globais/ExtracaoDados/Cards.js

Esse PR:
- Adiciona card de extração de dados de unidades.
Fixes AB#124176

feat(124176): Adiciona card de extração de unidades

---

src/componentes/Globais/ExtracaoDados/Cards.js

Esse PR:
- Adiciona card de extração de unidades e associações para a visão DRE.
História: AB#124203
História: AB#124202

feat(124203): Adiciona card visao DRE

---

src/componentes/Globais/ModalBootstrap/index.js
src/componentes/Globais/ModalBootstrap/modal-bootstrap.scss
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ArquivosDeReferencia/ArquivosDeReferenciaVisualizacaoDownload.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ModalVisualizarArquivoDeReferencia.js

Esse PR:
- Aumenta o tamanho do modal de visualização dos PDF nos materiais de referencia;
- Adiciona erro quando dispositivo não abre o PDF;
- Modifica icons.
História: AB#124084

feat(124084): Aumenta tamanho modal visualização pdfs

---

src/componentes/Globais/SidebarLeft/index.js
src/componentes/dres/Dashboard/index.js

Esse PR:
- Cria um parâmetro para identificar a ancoragem de acesso da seção de acompanhamento de PC na visão de DRE.
História: AB#124083

feat(124083): Cria parâmetro acesso acompanhamento pc DRE

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ArquivosDeReferencia/ArquivosDeReferenciaVisualizacaoDownload.js
src/componentes/escolas/Despesas/ListaDeDespesas/index.js
src/componentes/escolas/Despesas/metodosAuxiliares.js

Esse PR:
- Remove filtros das despesas quando o acesso é diferente de edição de despesas;
- Adiciona tooltip no acesso de documento.
História: AB#124144

feat(124144): Remove filtros quando acesso diferente desp

---

src/componentes/Globais/ModalBootstrap/index.js
src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentosRelatorios.js

Esse PR:
- Altera o tamanho do modal de visualização;
- Adiciona tooltip.
História: AB#125037

feat(125037): Modifica tamanho do modal e adiciona tooltip

---

src/componentes/escolas/Receitas/FormFiltrosAvancados/index.js
src/componentes/escolas/Receitas/Formularios/index.js
src/componentes/escolas/Receitas/ListaDeReceitas/index.js
src/services/mantemEstadoFiltrosUnidade.service.js

Esse PR:
- Adiciona serviço para manter os filtros das receitas das unidades;
História: AB#124201

feat(124201): Armazena o estado dos filtros de receitas

---

src/componentes/escolas/Receitas/FiltroPorTipoReceita/index.js
src/componentes/escolas/Receitas/FormFiltrosAvancados/index.js
src/componentes/escolas/Receitas/ListaDeReceitas/index.js

Esse PR:
- Unifica o estado dos filtros presentes na listagem de créditos.
História: AB#124201

feat(124201): Unifica estado do filtro na listagem

---

src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/index.js

Esse PR:
Ajuste a dinâmica de exibição do campo de filtro quando não há registro encontrado para tipos de documentos

feat(124182): Exibição do campo de Filtro de pesquisa

---

src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/index.js

Esse PR:
Ajuste a dinâmica de exibição do campo de filtro quando não há registro encontrado para tipos de documentos

feat(124182): Frontend para tela de Tipos de documentos em Parametrizações

---

src/componentes/sme/Parametrizacoes/Despesas/MotivosPagamentoAntecipado/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Despesas/MotivosPagamentoAntecipado/index.js

Esse PR:
Ajuste a dinâmica de exibição do campo de filtro quando não há registro encontrado para motivos de paramento antecipado
História AB#124988

feat(124988):  Frontend para tela de Motivos de pagamento antecipado em Parametrizações

---

src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/ModalForm.js

Esse PR:
Adição de maxlength nos campos do tipo texto para Tipos de Documentos

feat(124182): Adição de maxlength nos campos do tipo texto

---

src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/ModalForm.js

Esse PR:
Adição de maxlength nos campos do tipo texto para Tipos de Documentos

feature(124182): Inclusão de maxlength para os campos de textos

---

src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/index.js

Esse PR:
Manter o bloco de filtros na tela de listagem em caso da busca não retornar resultado

feature(124990): Mostrando os filtros na tela de listagem caso a busca não retornar resultados

---

src/componentes/sme/Parametrizacoes/Despesas/MotivosPagamentoAntecipado/ModalForm.js

Esse PR:
Adição de maxlength nos campos do tipo texto para Motivos de pagamento antecipado
História AB#124988

feat(124988): Adição de maxlength nos campos do tipo texto

---

src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/Tabela.js

Esse PR:
Ajustes de css na tabela de listagem de contas de associações

feat(124990): Ajustes de CSS

---

src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/BtnAdd.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/Filtros.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/ModalConfirmDelete.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/ModalForm.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/ModalInfoNaoPodeExcluir.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/ModalInfoUpdateNaoPermitido.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/Tabela.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/YupSignupSchemaTags.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/index.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/tipo_transacao.scss
src/rotas/index.js
src/services/sme/Parametrizacoes.service.js

Esse PR:
Nova tela de tipos de transação
História AB#124181

feat(124181) Nova tela de tipos de  transação

---

src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/BtnAdd.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/Filtros.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/ModalConfirmDelete.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/ModalForm.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/ModalInfoNaoPodeExcluir.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/ModalInfoUpdateNaoPermitido.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/Tabela.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/YupSignupSchemaTags.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/index.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/tipo_transacao.scss
src/rotas/index.js
src/services/sme/Parametrizacoes.service.js

Esse PR:
Adiciona nova tela para Tipos de transações
História AB#124181

feat(124181) Nova tela tipos de transação

---

src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/ModalForm.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/index.js

Esse PR:
Ajustes na tela de tipos de transação.
História AB#124181

feat(124181): Ajustes na tela de tipos de transação

---

src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/AutoCompleteAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/Filtros.js
src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/FormValidacao.js
src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/ModalForm.js
src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/index.js

Esse PR:
Ajustes na tela de contas de associações na parte do filtro pela associação e remoção do campo que continha o uuid da associação no modal de adicionar ou editar.

feat(124990): Ajustes na tela de contas de associações

---

src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/index.js

Esse PR:
Adição do tooltip no botão de editar na listagem de contas de associações

feat(124990): Adição do tooltip no botão de editar

---

src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/ModalForm.js

Esse PR:
Remoção de código de debug

feat(124990): Remoção de código de debug

---

src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/AutoCompleteAssociacoes.js
src/componentes/sme/Parametrizacoes/Estrutura/parametrizacoes-estrutura.scss

Esse PR:
Ajuste de html e css no botão de buscar

feat(124990): Ajuste de html e css no botão de buscar

---

src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/Tabela.js

Esse PR:
Ajuste de textos de cabeçalho da coluna

feat(124182): Ajuste no texto das colunas da tabela para Tipos de Documentos

---

src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/Tabela.js

Esse PR:
Ajuste de texto das colunas da tabela de tipos de documentos

feat(124182): Ajuste no texto das colunas da tabela

---

src/componentes/sme/Parametrizacoes/Dre/MotivosAprovacaoPcRessalva/hooks/usePostMotivoAprovacaoPcRessalva.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/hooks/usePatchMotivoDevolucaoTesouro.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/hooks/usePostMotivoDevolucaoTesouro.js

Esse PR:
- Corrige mensagens de texto dos toasts de parametrização de motivos de devolução ao tesouro.
História: AB#124987

feat(124987): Corrige texto de mensagens do toast

---

src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/FormValidacao.js
src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/ModalForm.js
src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/index.js

Esse PR:
Adição de novo campo obrigatório Data de início no form de criação e edição

feat(124990): Adição de novo campo Data de início

---

src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/UrlsMenuInterno.js
src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/index.js

Esse PR:
Correção no título da seção da página no menu

feat(124990): Correção no título da seção da página no menu

---

package.json

Atualiza develop com release 9.8.0

Release 9.8.0

---

src/componentes/sme/Parametrizacoes/Estrutura/Tags/ModalConfirmDeleteTag.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/ModalFormTags.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/TabelaTags.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/index.js

Esse PR:
- Altera textos e o layout dos modais na parametrização de tags.
História: AB#125426

feat(125426): Altera textos e layout modal

---

src/componentes/Globais/ArquivosDeCarga/index.js

Esse PR:
Ajusta a label na tela de carga de contas de associações
História AB#124991

feat(124991): carga contas associacoes - label  na tela de carga

---

src/services/sme/Parametrizacoes.service.js

Esse PR:
Ajuste no nome do arquivo de modelo de carga a ser baixado pra ficar dinâmico de acordo com a página acessada.
História AB#125427

feat(125427): Ajuste nome do arquivo modelo de carga

---

src/componentes/Globais/ArquivosDeCarga/index.js

Esse PR:
Ajusta a label na tela de carga de contas de associações
História AB#124991

feat(124991): Ajuste de Label quando o componente de Carga Associação é selecionado

---

src/services/sme/Parametrizacoes.service.js

Esse PR:
Ajuste no nome do arquivo de modelo de carga a ser baixado pra ficar dinâmico de acordo com a página acessada.
História AB#125427

feat(125427): Ajuste no nome do arquivo baixado do modelo de carga

---

src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/components/AutoCompleteAssociacoes.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/components/ModalConfirmacaoExclusao.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/components/ModalForm.js

Esse PR:
- Altera layout de modal.
- Adiciona busca por codigo_eol.
História: AB#125424

feat(125424): Busca e layout em parametrização de repasses

---

src/componentes/Globais/ArquivosDeCarga/ModalFormArquivosDeCarga.js
src/componentes/Globais/ArquivosDeCarga/YupSignupSchemaArquivosDeCarga.js
src/componentes/Globais/ArquivosDeCarga/__tests__/ModelForm.test.js
src/componentes/Globais/ArquivosDeCarga/__tests__/index.test.js
src/componentes/Globais/ArquivosDeCarga/index.js

Esse PR:
Correção validação dos campos na edição de arquivo de carga.
Ajuste na quantidade de itens listados por página para 20
Campo tipo delimitador agora é obrigatório
História AB#125838

feat(125838): Ajustes na edição, criação e listagem de arquivos de carga

---

src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/BtnAdd.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/__tests__/BtnAdd.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/__tests__/Filtros.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/__tests__/ModalInfoNaoPodeExcluir.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/__tests__/ModalInfoUpdateNaoPermitido.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/__tests__/Tabela.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/__tests__/YupSignupSchemaTags.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/index.js

Esse PR:
- Adiciona testes unitários na tela de parametrizações de tipos de transações.
História: AB#125498

feat(125498): Testes parametrizações de tipos transações

---

package.json
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeTransacao/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/__tests__/BtnAdd.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/__tests__/Filtros.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/__tests__/ModalFormTags.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/__tests__/ModalInfoNaoPermitido.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/__tests__/TabelaTags.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/__tests__/YupSignupSchemaTags.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/__tests__/index.test.js

Esse PR:
- Inicia a adição dos teste unitários de tags.
História: AB#125426

feat(125426): Adiciona testes unitários tags

---

src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/__tests__/BtnAdd.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/__tests__/Filtros.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/__tests__/ModalConfirmDelete.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/__tests__/ModalInfoNaoPodeExcluir.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/__tests__/ModalInfoUpdateNaoPermitido.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/__tests__/Tabela.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/__tests__/YupSignupSchemaTags.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/index.js

Esse PR:
Adiciona testes unitários para aumento de cobertura do Frontend
História AB#125882

feat(125882) Testes unitários tipos custeio

---

src/componentes/Globais/ArquivosDeCarga/index.js
src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/ModalForm.js

Esse PR:
Atualiza a Modal de exclusão para o novo padrão.
História AB#124991

feat(124991): carga contas associacoes modal exclusao

---

src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/Filtros.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__tests__/BtnAdd.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__tests__/Filtros.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__tests__/ModalConfirmDeleteAssociacao.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__tests__/ModalConfirmDeleteAssociacao.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__tests__/ModalConfirmUpdateObservacao.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__tests__/ModalConfirmUpdateObservacao.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__tests__/ModalInfoNaoPodeExcluir.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__tests__/Tabela.test.js

Esse PR:
Adiciona testes unitários para aumento de cobertura do Frontend da página de Parametrização de Associações
História AB#125883

feat(125883): Aumento de cobertura de testes unitários de Associações

---

src/componentes/sme/Parametrizacoes/Despesas/Fornecedores/__tests__/ModalFormFornecedores.test.js
src/componentes/sme/Parametrizacoes/Despesas/Fornecedores/__tests__/index.test.js

Esse PR:
Adiciona cobertura de Testes para Fornecedores
História AB#125882

feat(125882): Inclusão de cobertura de testes unitários para Fornecedores

---

src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/ExibicaoQuantidade.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/Filtros.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/Lista.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/ModalConfirmacaoExclusao.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/MotivosDevolucaoTesouro.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/Paginacao.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/TopoComBotoes.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/useDeleteMotivoDevolucaoTesouro.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/useGetMotivosDevolucaoTesouro.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/usePatchMotivoDevolucaoTesouro.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/usePostMotivoDevolucaoTesouro.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/components/Lista.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/components/ModalForm.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/components/TopoComBotoes.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/context/MotivosDevolucaoTesouro.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/hooks/usePatchMotivoDevolucaoTesouro.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/index.js

Esse PR:
- Complementa testes de parametrização de tags;
- Adiciona testes de parametrização de devolução ao tesouro.
História: AB#125959

feat(125959): Adiciona testes

---

src/componentes/sme/Parametrizacoes/Estrutura/Acoes/Filtros.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/__tests__/Filtros.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/index.js

Esse PR:
Aumento da cobertura de testes da index e filtros de Parametrização -> Ações

feat(125959): Aumento da cobertura de testes de Parametrização -> Ações

---

src/componentes/sme/Parametrizacoes/Estrutura/TiposConta/ModalAddEditTipoConta.js
src/componentes/sme/Parametrizacoes/Estrutura/TiposConta/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/Estrutura/TiposConta/__tests__/index.test.js

Esse PR:
Aumento da cobertura de testes de Parametrização -> Tipos de Conta

feat(125959): Aumento da cobertura de testes de Parametrização -> Tipos de Conta

---

src/componentes/sme/Parametrizacoes/Despesas/EspecificacoesMateriaisServicos/components/Lista.js

Esse PR:
Ajuste o estilo de botão ícone de edição
História AB#125420

feat(125420): ajuste na estilização do botão ícone

---

src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosLancamentos/Filtros.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosLancamentos/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosLancamentos/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosLancamentos/index.js

Esse PR:
Aumento da cobertura de testes de Parametrização -> Tipos de acertos de Lançamentos

feat(125959): Aumento da cobertura de testes de Parametrização -> Tipos de acertos de Lançamentos

---

src/componentes/sme/Parametrizacoes/Despesas/EspecificacoesMateriaisServicos/__tests__/usePost.test.js
src/componentes/sme/Parametrizacoes/Despesas/EspecificacoesMateriaisServicos/hooks/usePost.js

Esse PR:
Ajusta a legenda de toast de cadastrado, em padrão com a alteração de cadastro
História AB#125420

feat(125420): param especificacoes materiais servicos mensagem post

---

src/componentes/Globais/EditorWysiwyg/index.js
src/componentes/sme/PainelParametrizacoes/ParametrizacaoCard.js
src/componentes/sme/PainelParametrizacoes/index.js
src/componentes/sme/Parametrizacoes/EdicaoDeTextos/TextosPaa/TabelaTextosPaa.js
src/componentes/sme/Parametrizacoes/EdicaoDeTextos/TextosPaa/index.js
src/rotas/index.js
src/services/escolas/PrestacaoDeContas.service.js

Esse PR:
- Adiciona parametrização texto de PAA.
História: AB#125887

feat(125887): Adiciona parametrização PAA

---

src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/Filtros.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/ModalFormDocumento.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/index.js

Esse PR:
Aumento da cobertura de testes de Parametrização -> Tipos de acertos de Documentos

feat(125959): Aumento da cobertura de testes de Parametrização -> Tipos de acertos de Documentos

---

src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/Filtros.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/ModalFormDocumento.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/index.js

Esse PR:
Aumento da cobertura de testes de Parametrização -> Tipos de acertos de Documentos

feat(125959): Aumento da cobertura de testes de Parametrização -> Tipos de acertos de Documentos 

---

src/componentes/sme/Parametrizacoes/Estrutura/Acoes/AssociacoesDaAcao/FormFiltros/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/AssociacoesDaAcao/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/TabelaAssociacaoAcao.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/__tests__/TabelaAssociacaoAcao.test.js
src/services/sme/Parametrizacoes.service.js

paginacao acoes associacoes e testes

Feature(12607): paginacao acoes associacoes e testes

---

src/componentes/sme/Parametrizacoes/EdicaoDeTextos/TextosPaa/__tests__/TextosPaa.test.js
src/componentes/sme/Parametrizacoes/EdicaoDeTextos/TextosPaa/index.js

Esse PR:
- Adiciona testes unitários.
História: AB#125887

feat(125887): adiciona testes

---

src/utils/RedirectLoginVisaoUe.js
src/utils/ValidacoesAdicionaisFormularios.js
src/utils/__tests__/CoresTags.test.js
src/utils/__tests__/FormataData.test.js
src/utils/__tests__/FormataNomeDreParaTabelas.test.js
src/utils/__tests__/Loading.test.js
src/utils/__tests__/Modais.test.js
src/utils/__tests__/ProcessoSeiMask.test.js
src/utils/__tests__/RedirectLoginVisaoUe.test.js
src/utils/__tests__/ValidacoesAdicionaisFormularios.test.js
src/utils/__tests__/ValidacoesNumeros.test.js
src/utils/__tests__/redirect.test.js

tec(125959): Implementa testes pasta utils

---

src/componentes/sme/Parametrizacoes/Despesas/EspecificacoesMateriaisServicos/__tests__/useDelete.test.js
src/componentes/sme/Parametrizacoes/Despesas/EspecificacoesMateriaisServicos/__tests__/usePatch.test.js
src/componentes/sme/Parametrizacoes/Despesas/EspecificacoesMateriaisServicos/__tests__/usePost.test.js
src/componentes/sme/Parametrizacoes/Dre/MotivosAprovacaoPcRessalva/__tests__/Filtros.test.js
src/componentes/sme/Parametrizacoes/Dre/MotivosAprovacaoPcRessalva/__tests__/Lista.test.js
src/componentes/sme/Parametrizacoes/Dre/MotivosAprovacaoPcRessalva/__tests__/ModalConfirmaExclusao.test.js
src/componentes/sme/Parametrizacoes/Dre/MotivosAprovacaoPcRessalva/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Dre/MotivosAprovacaoPcRessalva/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Dre/MotivosAprovacaoPcRessalva/__tests__/useDelete.test.js
src/componentes/sme/Parametrizacoes/Dre/MotivosAprovacaoPcRessalva/__tests__/useGet.test.js
src/componentes/sme/Parametrizacoes/Dre/MotivosAprovacaoPcRessalva/__tests__/usePatch.test.js
src/componentes/sme/Parametrizacoes/Dre/MotivosAprovacaoPcRessalva/__tests__/usePost.test.js
src/componentes/sme/Parametrizacoes/Dre/MotivosAprovacaoPcRessalva/components/ModalForm.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/useDeleteMotivoDevolucaoTesouro.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/usePatchMotivoDevolucaoTesouro.test.js
src/componentes/sme/Parametrizacoes/Dre/ParametrizacoesMotivosDevolucaoTesouro/__tests__/usePostMotivoDevolucaoTesouro.test.js

Esse PR:
amplia a cobertura de testes do frontend

tec(125959): ampliação de cobertura de testes

---

src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/__tests__/Filtros.test.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/__tests__/Lista.test.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/hooks/useGetRepasses.js

Esse PR:
Adição de testes em Parametrização -> Repasses

feat(125959): Adição de testes em Parametrização -> Repasses

---

src/componentes/Globais/Breadcrumb/index.js
src/componentes/Globais/UI/Button/style.css
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/__tests__/hooks/__tests__/useGetTabelasReceitas.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/__tests__/index.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/hooks/useGetTabelasReceitas.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/style.css
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/index.js
src/index.js

Esse PR:
- Implementa tabela de receitas previstas com ações da associação
AB#124770

feat(124770): PAA receitas previstas consultar recursos

---

src/componentes/Globais/Modal/CustomModalConfirm.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/TipoReceitaForm.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/components/Filtros/Filtros.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/components/UnidadesAssociadas/Lista.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/components/UnidadesAssociadas/useDesvincularUnidade.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/components/UnidadesAssociadas/useGetUnidadesVinculadas.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/components/VincularUnidades/index.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/components/VincularUnidades/useGetUnidadesNaoVinculadas.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/components/VincularUnidades/useVincularUnidade.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/hooks/useDeleteTipoReceita.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/hooks/useGetFiltrosTiposReceita.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/hooks/useGetTipoReceita.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/hooks/usePatchTipoReceita.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/hooks/usePostTipoReceita.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/components/UnidadesAssociadas/hooks/useDesvincularUnidade.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/components/VincularUnidades/index.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/hooks/useDeleteTipoReceita.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/hooks/usePatchTipoReceita.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/hooks/usePostTipoReceita.js

- Melhora testes
- Ajusta mensagens toast de acordo com as especificações
- Ajusta fluxo de criação
- Layout modal de excluir
- Retorna mensagem da api quando erro no cadastro

feat(125425): Ajustes formulário tipo credito

---

src/componentes/sme/Parametrizacoes/Receitas/TiposDeCredito/index.js

Esse PR:
- Altera o filtro de busca por unidades.
História AB#125425

feat(125425): Modifica filtro

---

src/componentes/sme/Parametrizacoes/Receitas/TiposDeCredito/components/Filtros.js

Esse PR:
- Modifica o filtro de unidades na parametrização de tipos de crédito.
História: AB#125425

feat(125425): Modifica filtro associação

---

src/componentes/Globais/Ambientes/__tests__/index.test.js
src/componentes/Globais/AmbientesApi/__tests__/index.test.js
src/componentes/Globais/ArquivosDeCarga/index.js
src/componentes/Globais/Breadcrumb/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDocumento/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Associacoes/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Estrutura/ContasDasAssociacoes/index.js
src/componentes/sme/Parametrizacoes/Estrutura/Periodos/__tests__/usePatchPeriodo.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/TipoReceitaForm.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/TipoReceitaForm.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/hooks/useDeleteTipoReceita.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/hooks/usePatchTipoReceita.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/hooks/usePostTipoReceita.test.js

feat(126668) Task 126745 cobertura de testes

---

src/componentes/sme/PainelParametrizacoes/index.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/Filtros.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/FormValidacao.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/ModalForm.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/Tabela.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/hooks/useAcoesPDDE.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/hooks/usePatchAcaoPDDE.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/hooks/usePatchCategorias.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/hooks/usePostCategorias.js
src/services/sme/Parametrizacoes.service.js

Esse PR:
- Ajustes no layout
- Ajustes na lógica e mensagens de sucesso e erro

feature(126749): Ajustes no layout e mensagens de erro e sucesso

---

src/componentes/Globais/Breadcrumb/__tests__/index.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/__tests__/index.test.js

Esse PR:
- Adiciona testes na tela inicial de PAA.
História: AB#124768

feat(124768): Testes tela inicial paa

---

src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/Filtros.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/Tabela.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/useAcoesPDDE.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/useDeleteAcaoPDDE.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/useDeleteCategoria.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/useGetAcoesPDDE.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/useGetCategorias.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/usePatchAcaoPDDE.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/usePatchCategorias.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/usePostAcaoPDDE.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/usePostCategorias.test.js

Esse PR:
- Adiciona testes unitários para a tela de Parametrização -> Ações PDDE

feat(126749): Adição de testes unitários para Ações PDDE

---

src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/ModalForm.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/Paginacao.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/useDeleteCategoria.test.js
src/componentes/sme/Parametrizacoes/componentes/ModalConfirmarExclusao.js

Esse PR:
- Correção nos testes unitários de deletar categoria de ação pdde

feat(126749): Correção do teste unitário de deletar categoria

---

src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/ModalForm.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/Paginacao.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/useDeleteCategoria.test.js
src/componentes/sme/Parametrizacoes/componentes/ModalConfirmarExclusao.js

Esse PR:
- Adiciona testes unitários de ações pdde para melhorar a cobertura

feat(126749): Adição de testes unitários de ações pdde

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/ReceitasPrevistasModalForm.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/index.js
src/utils/money.js

feat(124771): Implementa validações e valores linha total PTRF

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/index.js

feat(124771): Corrige atualização total

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/ReceitasPrevistasModalForm.js

feat(124771): Permite inputar valores zerados

---

src/componentes/sme/PainelParametrizacoes/index.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/ModalForm.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/ModalForm.test.js

Esse PR:
- Correção dos textos da página de Categoria para Programa
- alteração da posição do card de Ações PDDE na página de Parametrizações

feat(126749): Ajustes de grafia e de layout de Ações PDDE

---

src/services/escolas/Despesas.service.js
src/services/escolas/Paa.service.js
src/services/escolas/PresentesAta.service.js
src/services/escolas/PrestacaoDeContas.service.js
src/services/escolas/RateiosDespesas.service.js
src/services/escolas/__tests__/AtasAssocicao.test.js
src/services/escolas/__tests__/DemonstrativoFinanceiro.test.js
src/services/escolas/__tests__/Despesas.test.js
src/services/escolas/__tests__/Paa.test.js
src/services/escolas/__tests__/PresentesAta.test.js
src/services/escolas/__tests__/PrestacaoDeContas.test.js
src/services/escolas/__tests__/RateiosDespesas.test.js

Esse PR:
Adiciona testes unitários para alcance de cobertura 
História AB#126668

test(126668): Inclusão de testes unitários para aumento de cobertura

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/ReceitasPrevistasModalForm.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/index.js
src/services/visoes.service.js

feat(124771): Ajusta valores das tabelas incluindo informação sobre saldo atual

---

src/services/visoes.service.js

Esse PR:
Remove resposta booleana provisória pra retorno de permissões
História AB#126668

fix(126668): remoção de permissão provisória utilizada em ambiente local

---

src/componentes/Globais/Breadcrumb/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/DetalhamentoAcoesPdde/ModalEdicaoAcaoPdde.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/DetalhamentoAcoesPdde/Paginacao.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/DetalhamentoAcoesPdde/Tabela.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/DetalhamentoAcoesPdde/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/TableReceitasPrevistasPdde.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/hooks/useGetAcoesPdde.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/hooks/useGetCategoriasPddeTotais.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/hooks/usePatchAcaoPdde.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/index.js
src/services/escolas/Paa.service.js

Esse PR:
- Adiciona a tabela de programa PDDE em receitas previstas;
- Adiciona seção de ações PDDE em receitas previstas.
História: AB#126656

feat(126656): Adiciona seção ações pdde em receitas previstas

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/hooks/useDeleteRecursoProprio.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/hooks/useGetFontesRecursos.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/hooks/useGetRecursosProprios.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/hooks/useGetTotalizarRecursoProprio.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/hooks/usePatchRecursoProprio.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/hooks/usePostRecursoProprio.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/style.css
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/TabelaReceitasPrevistas.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/TabelaRecursosProprios.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/TableReceitasPrevistasPdde.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/index.js
src/services/escolas/Paa.service.js

- Implementa tabela de recursos próprios na tab de receitas previstas
- Implementa tab de detalhamento de recursos próprios com criação, edição e exclusão direto na tabela.
- Refatora index de receitas previstas
AB#126196

feat(126196): Detalhamento de recursos próprios

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/ModalEdicaoAcaoPdde.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/Tabela.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/__tests__/ModalEdicaoAcaoPdde.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/__tests__/Paginacao.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/__tests__/Tabela.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/__tests__/hooks/useGetAcoesPdde.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/__tests__/hooks/usePatchAcoesPdde.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/__tests__/index.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/__tests__/hooks/useGetCategoriasPddeTotais.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaTransacoes/Ordenacao/ModalOrdenar.js

Esse PR:
- Corrige labels;
- Adiciona testes unitários.
Histórias: AB#126656 AB#127343

feat(126656): Adiciona teste unitários

---

src/componentes/sme/Mandatos/__fixtures__/mockData.js
src/componentes/sme/Mandatos/__tests__/ExibicaoQuantidade.test.js
src/componentes/sme/Mandatos/__tests__/Filtros.test.js
src/componentes/sme/Mandatos/__tests__/Lista.test.js
src/componentes/sme/Mandatos/__tests__/ModalForm.test.js
src/componentes/sme/Mandatos/__tests__/Paginacao.test.js
src/componentes/sme/Mandatos/__tests__/TopoComBotoes.test.js
src/componentes/sme/Mandatos/__tests__/useDelete.test.js
src/componentes/sme/Mandatos/__tests__/useGet.test.js
src/componentes/sme/Mandatos/__tests__/useGetMaisRecente.test.js
src/componentes/sme/Mandatos/__tests__/usePatch.test.js
src/componentes/sme/Mandatos/__tests__/usePost.test.js
src/componentes/sme/Mandatos/components/Lista.js
src/componentes/sme/Mandatos/components/ModalForm.js
src/componentes/sme/Mandatos/hooks/usePatchMandato.js
src/componentes/sme/Mandatos/hooks/usePostMandato.js

Esse PR:
- Adição de testes para a página de Mandatos
História: AB#127061

feat(127061): Aumento na cobertura de testes unitários

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/__tests__/hooks/useDeleteRecursoProprio.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/__tests__/hooks/useGetFontesRecursos.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/__tests__/hooks/useGetRecursosProprios.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/__tests__/hooks/useGetTotalizarRecursoProprio.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/__tests__/hooks/usePatchRecursoProprio.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/__tests__/hooks/usePostRecursoProprio.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/__tests__/index.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/hooks/useGetFontesRecursos.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/hooks/useGetTotalizarRecursoProprio.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/index.js

feat(126196): Testes detalhamento de recursos próprios

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/TabelaRecursosProprios.js

Esse PR:
- Adiciona total na coluna e livre aplicação e muda layout da tabela.
História: AB#127517

feat(127517): Adiciona valor de livre aplicação na tabela

---

src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/Filtros/FiltroExpandido.js
src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDespesasPeriodosAnteriores/Filtros/FiltroExpandido.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/__tests__/index.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/index.js

- Remove imports do locale do antd
AB#127851

feat(127851): Ajusta impactos da adição do locale no config provider global

---

src/componentes/Globais/UI/Icon/icones.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoRecursosProprios/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/__tests__/TabelaReceitasPrevistas.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/__tests__/index.test.js
src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/__tests__/useConferidoRateioTemplate.test.js
src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/__tests__/useConferidoTemplate.test.js
src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/__tests__/useNumeroDocumentoTemplate.test.js
src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/__tests__/useRowExpansionDespesaTemplate.test.js
src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/__tests__/useRowExpansionReceitaTemplate.test.js
src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/__tests__/useTagInformacaoTemplate.test.js
src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/__tests__/useTagRateioTemplate.test.js
src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/__tests__/useValorTemplate.test.js
src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/useConferidoTemplate.js
src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/useTagRateioTemplate.js
src/hooks/dres/PrestacaoDeContas/__tests__/useCarregaPrestacaoDeContasPorUuid.test.js

feat(127851): Implementa testes hooks dres e corrige outros testes receitas previstas

---

src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/ModalForm.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__fixtures__/mockData.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/hooks/useDeleteCategoriaAcaoPDDE.js
src/services/sme/Parametrizacoes.service.js

Esse PR:
- Ajustes na lógica de deleção da categoria pdde ao editar ação pdde
História: AB#127089

feat(127089): Ajustes na lógica de deleção de categoria pdde.

---

src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/ModalForm.js

Esse PR:
- Correção na mensagem de tooltip do ícone da lixeira ao tentar deletar categoria pdde associada a alguma ação pdde
História: AB#127089

feat(127089): Correção da mensagem de tooltip ao tentar excluir categoria

---

src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/useDeleteCategoria.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/hooks/useDeleteCategoriaAcaoPDDE.js
src/services/sme/__tests__/Parametrizacoes.test.js

Esse PR:
- Correção de testes unitários
- Correção de mensagem de erro
História: AB#127089

feat(127089): Correção de testes unitários. Correção de mensagem de erro

---

src/componentes/escolas/Paa/ElaboracaoPaa/index.js
src/services/sme/Parametrizacoes.service.js

Esse PR:
- Adiciona busca de parâmetro PAA com o mês
- Adiciona validação no botão de elaborar novo paa para habilitar dependendo do valor do parâmetro
História: AB#127073

feat(127073): Ajustes no botão de elaborar novo PAA

---

src/App.test.js
src/componentes/Globais/ExtracaoDados/index.js
src/componentes/Globais/SidebarLeft/__tests__/getUrls.test.js
src/componentes/Globais/SidebarLeft/__tests__/index.test.js
src/componentes/escolas/Despesas/Tags/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/PAA/PeriodosPaa/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/__tests__/useDelete.test.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/__tests__/useGet.test.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/__tests__/useGetTabelasPorAssociacao.test.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/__tests__/usePatch.test.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/__tests__/usePost.test.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesRepasses/hooks/useDeleteRepasse.js
src/hooks/Globais/__tests__/useAcessoEmSuporteInfo.test.js
src/hooks/Globais/__tests__/useCarregaRepassesPendentesPorPeriodoAteAgora.test.js
src/hooks/Globais/__tests__/useCarregaTabelaDespesa.test.js
src/hooks/Globais/__tests__/useCarregaTabelaReceita.test.js
src/hooks/Globais/__tests__/useDataTemplate.test.js
src/rotas/__tests__/index.test.js
src/store/__tests__/index.test.js

Esse PR:
Adiciona testes unitários para ampliação de cobertura de frontend
História AB#128124

test(128124): Testes unitários para ampliação de cobertura do frontend

---

src/rotas/index.js

feat(124696): Corrige permissão rota situação patrimonial

---

src/componentes/escolas/Paa/ElaboracaoPaa/__tests__/index.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/__tests__/usePostPaa.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/index.js

Esse PR:
- Adiciona testes unitários
História: AB#127073

test(127073): Adição de testes unitários

---

src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/VincularDespesas/FormFiltrosDespesas.js

feat(124696): Corrige botão limpar filtros

---

src/componentes/sme/ConsultaDeSaldosBancarios/ConsultaDeSaldosBancariosDetalhesAssociacoes.js
src/componentes/sme/ConsultaDeSaldosBancarios/Filtros.js
src/componentes/sme/ConsultaDeSaldosBancarios/__fixtures__/mockData.js
src/componentes/sme/ConsultaDeSaldosBancarios/__tests__/BrnExportar.test.js
src/componentes/sme/ConsultaDeSaldosBancarios/__tests__/ConsultaDeSaldosBancariosDetalhesAssociacoes.test.js
src/componentes/sme/ConsultaDeSaldosBancarios/__tests__/Filtros.test.js
src/componentes/sme/ConsultaDeSaldosBancarios/__tests__/ModalVisualizarExtrato.test.js
src/componentes/sme/ConsultaDeSaldosBancarios/__tests__/SelectConta.test.js
src/componentes/sme/ConsultaDeSaldosBancarios/__tests__/SelectPeriodo.test.js
src/componentes/sme/ConsultaDeSaldosBancarios/__tests__/TabelaSaldosDetalhesAssociacoes.test.js
src/componentes/sme/ConsultaDeSaldosBancarios/__tests__/TabelaSaldosPorDre.test.js
src/componentes/sme/ConsultaDeSaldosBancarios/__tests__/TabelaSaldosPorTipoDeUnidade.test.js
src/componentes/sme/ConsultaDeSaldosBancarios/__tests__/TabelaSaldosPorUeDre.test.js

Esse PR:
- Adição de testes unitários em Consulta de Saldos Bancários
História: AB#128124

feat(128124): Aumento da cobertura de testes

---

src/componentes/Globais/CentralDeDownloads/FormFiltrosDownloads.js
src/componentes/Globais/CentralDeDownloads/TabelaDownloads.js
src/componentes/Globais/CentralDeDownloads/__tests__/FormFiltrosDownloads.test.js
src/componentes/Globais/CentralDeDownloads/__tests__/TabelaDownloads.test.js
src/componentes/Globais/CentralDeDownloads/__tests__/index.test.js

feat(128124): Implementa testes central de download

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/ModalEdicaoReceitaPrevistaPdde.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/__tests__/ModalEdicaoAcaoPdde.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/__tests__/Tabela.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/__tests__/hooks/usePatchAcoesPdde.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/__tests__/hooks/usePostAcoesPdde.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/hooks/usePatchReceitaPrevistaPdde.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/DetalhamentoAcoesPdde/hooks/usePostReceitaPrevistaPdde.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/__tests__/TabelaReceitasPrevistas.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/__tests__/hooks/useGetProgramasPddeTotais.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__fixtures__/mockData.js

Esse PR:
- Adição de testes para Post de Receita Prevista PDDE
- Ajustes nos payloads de criação adicionando o paa uuid
- Ajustes nos imports do métodos de requests
- Ajustes nas nomenclaturas de variáveis
História: AB#127116

feat(127116): Ajustes testes unitários PAA

---

src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/usePatchCategorias.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/usePostCategorias.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/hooks/useAcoesPDDE.js
src/services/sme/__tests__/Parametrizacoes.test.js

Esse PR:
- Correção da url do request de programas pdde
História: AB#127116

feat(127116): Ajustes testes unitários

---

src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/InformarValores/BarraAcaoEmLote.js
src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/InformarValores/index.js
src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/VincularDespesas/hooks/useGetDespesas.js
src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/VincularDespesas/index.js
src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/hooks/useGetBemProduzido.js
src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/hooks/usePatchBemProduzido.js
src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/hooks/usePostExluirDespesaBemProduzidoEmLote.js
src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/index.js
src/paginas/escolas/SituacaoPatrimonial/EdicaoBemProduzido/index.js
src/rotas/index.js
src/services/escolas/BensProduzidos.service.js
src/services/escolas/Despesas.service.js

Esse PR:
- Implementa tabela para informar valores utilizados
- Implementa validações
- Implementa chamada api para salvar valores utilizados
- Refatora chamadas para salvar rascunho
AB#127456

feat(127456): Implementa fluxo informar valores

---

src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/InformarValores/index.js

feat(127456): Ajusta validação quando valor disponível 0

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/ModalConfirmarPararAtualizacaoSaldo.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/ReceitasPrevistasModalForm.js

Esse PR:
Ajusta legendas conforme validações de PO
História #126467

feat(126467): ajustes legendas

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/__tests__/ModalConfirmarPararAlualizaCaoSaldo.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/__tests__/ReceitasPrevistasModalForm.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/__tests__/hooks/usePararAtualizacaoSaldoPaa.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/__tests__/index.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/index.js

Esse PR:
Adiciona testes unitários da história
História AB#126467

test(126467): testes unitários - homolog

---

src/componentes/Globais/DevolucaoAoTesouroAjuste/__tests__/index.test.js
src/componentes/Globais/EdicaoDeSenha/FormAlterarSenha/__tests__/index.test.js
src/componentes/Globais/EdicaoDeSenha/FormAlterarSenha/index.js
src/componentes/Globais/EdicaoDeSenha/FormRedefinirSenha/__tests__/index.test.js
src/componentes/Globais/EdicaoDeSenha/FormRedefinirSenha/index.js
src/componentes/Globais/EsqueciMinhaSenha/RecuperarSenha/index.js
src/componentes/Globais/EsqueciMinhaSenha/__tests__/index.test.js
src/componentes/Globais/EsqueciMinhaSenha/index.js
src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/__tests__/RelatorioAposAcertos.test.js
src/services/escolas/__tests__/PrestacaoDeContas.test.js

Esse PR:
- Adiciona/corrige testes unitários em:
- DevolucaoAoTesouroAjuste
- EdicaoDeSenha  
- EsqueciMinhaSenha
- ExibeAcertosEmLancamentosEDocumentosPorConta
- PrestacaoDeContas.test.js

test(129213): Adição de testes unitários

---

package-lock.json
package.json

Esse PR:
- Atualiza o yup para a versão 0.32.11.
História: AB#128815

feat(128815): Atualiza yup para 0.32.11

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/ModalFormAdicionarPrioridade.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/useGetAcoesPDDE.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/useGetEspecificacoes.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/useGetPrioridadeTabelas.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/useGetTiposDespesaCusteio.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/usePostPrioridade.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/validationSchema.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/hooks/useGetAcoesAssociacao.js
src/services/escolas/Paa.service.js

Esse PR:
- Adiciona modal de criar nova prioridade
- Adiciona 2 novos requests de obter dados dos selects do modal e de criar a prioridade

feat(127465)): Adição de modal de criar nova prioridade paa

---

src/componentes/Globais/Tag/tag.scss
src/componentes/escolas/SituacaoPatrimonial/ListaBemProduzido/FormFiltrosBens.js
src/componentes/escolas/SituacaoPatrimonial/ListaBemProduzido/hooks/useGetBemProduzidosComAdquiridos.js
src/componentes/escolas/SituacaoPatrimonial/ListaBemProduzido/index.js
src/hooks/Globais/useGetPeriodoComPC.js
src/services/escolas/BensProduzidos.service.js

Esse PR:
- Adiciona a listagem de bens na situação patrimonial;
História: [AB#127458](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127458)

feature(127458): Adiciona listagem situação patrimonial

---

src/componentes/escolas/SituacaoPatrimonial/ListaBemProduzido/hooks/useGetBemProduzidosComAdquiridos.js
src/componentes/escolas/SituacaoPatrimonial/ListaBemProduzido/index.js

Esse PR:
- Altera comportamento da listagem ao alterar filtros;
História: [AB#127458](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127458)

feat(127458): Altera listagem

---

src/componentes/escolas/SituacaoPatrimonial/ListaBemProduzido/index.js

Esse PR:
- Adiciona a tela de quando não é encontrado nenhum resultado,
- Limpa status salvo ao limpar filtros.
História: [AB#127458](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127458)

feat(127458): Adiciona tela sem resultado 404

---

package.json

PR de retorno da release 9.18.0 para develop. ref história 130057

Release 9.18.0 → develop

---

src/componentes/Globais/GestaoDePerfis/ModalPerfisForm.js
src/componentes/Globais/GestaoDePerfis/YupSignupSchemaPerfis.js
src/componentes/dres/Associacoes/DadosDasAssociacoes/ProcessosSei/ProcessoSeiPrestacaoDeContaForm.js

Esse PR:
- Altera o formato da validação de tipos de array no yup.
História: [AB#130061](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/130061)

fix(130061): Alteracao de validação de tipos no yup

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/FormFiltros.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/Tabela.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/useGetPrioridadeTabelas.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/useGetPrioridades.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/usePostPrioridade.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/index.js
src/services/escolas/Paa.service.js

Esse PR:
- Adiciona filtros
- Adiciona listagem

feat(127464): Adição de filtros e listagem de prioridades

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/FormFiltros.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/ModalFormAdicionarPrioridade.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/Tabela.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/index.test.js

Esse PR:
- Adiciona testes unitários para Prioridades

feature(127464): Adição de testes unitários para Prioridades

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/FormFiltros.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/FormFiltros.test.js

Esse PR:
- Altera os labels dos campos dos filtros
- Altera os testes unitários que usam os labels dos campos dos filtros

feature(127464): Ajustes nos labels dos filtros e nos testes unitários

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/ModalFormAdicionarPrioridade.test.js

Esse PR:
- Melhoria na cobertura de testes do modal de criação de prioridade

test(127464): Melhoria na cobertura de testes de Prioridade

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/FormFiltros.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/ModalFormAdicionarPrioridade.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/Tabela.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/useGetPrioridadeTabelas.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/useGetPrioridades.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/usePatchPrioridade.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/validationSchema.js
src/services/escolas/Paa.service.js

Esse PR:
- Refatora o componente de filtro mantendo apenas 1 parâmetro para passagem de dadosTabelas
- Adiciona um hook/service Patch para edição de Prioridade
- Inclui um parâmetro em ModalForm para receber o objeto a ser alterado no formulário
- Inclui a tag indicativa, na coluna de Ação) quando o registro está como Prioridade igual a "Não" (Não priorizado)
- Adiciona a função handleEditar na tabela
História [AB#127466](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127466)

feat(127466): Implementação de edição de Prioridades- develop

---

src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
src/componentes/escolas/Despesas/CadastroDeDespesas/index.js
src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/InformarValores/index.js
src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/VincularDespesas/index.js
src/componentes/escolas/SituacaoPatrimonial/FormularioBemProduzido/index.js
src/componentes/escolas/SituacaoPatrimonial/ListaBemProduzido/index.js
src/paginas/escolas/Despesas/EdicaoDeDespesa/index.js

Esse PR:
- Adiciona a visualização despesa em situação patrimonial;
- Bloqueia deseleciona despesas na etapa de vincular despesas;
- Altera bloqueio de botões no fluxo de situação patrimonial.
História: [AB#129379](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/129379)

feat(129379): Adiciona visualização despesa em situação patrimonial

---

src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/FiltrosTransacoes/__tests__/index.test.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/FiltrosTransacoes/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/Justivicativa/__tests__/index.test.js
src/componentes/escolas/PrestacaoDeContas/TopoSelectPeriodoBotaoConcluir.js
src/componentes/escolas/PrestacaoDeContas/__fixtures__/mockData.js
src/componentes/escolas/PrestacaoDeContas/__tests__/BarraAvisoErroProcessamentoPC.test.js
src/componentes/escolas/PrestacaoDeContas/__tests__/BotaoConciliacao.test.js
src/componentes/escolas/PrestacaoDeContas/__tests__/DataUltimaConciliacao.test.js
src/componentes/escolas/PrestacaoDeContas/__tests__/InformacoesIniciais.test.js
src/componentes/escolas/PrestacaoDeContas/__tests__/ModalGerarPrevia.test.js
src/componentes/escolas/PrestacaoDeContas/__tests__/ModalGerarPreviaSendoGerada.test.js
src/componentes/escolas/PrestacaoDeContas/__tests__/ModalSalvarDataSaldoExtrato.test.js
src/componentes/escolas/PrestacaoDeContas/__tests__/PresidenteAusente.test.js
src/componentes/escolas/PrestacaoDeContas/__tests__/SelectPeriodoConta.test.js
src/componentes/escolas/PrestacaoDeContas/__tests__/TopoSelectPeriodoBotaoConcluir.test.js
src/componentes/escolas/PrestacaoDeContas/__tests__/index.test.js

Esse PR:
Adiciona testes unitários para os cenários da task [AB#130901](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/130901)
História [AB#130711](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/130711)

test(130711): Testes unitários Prestação de Contas

---

src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/IconeDataSaldoBancarioPendentes.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/__tests__/DataSaldoBancario.test.js

[AB#129997](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/129997)

feat(129997): Implementa testes DataSaldoBancario

---

src/componentes/escolas/Despesas/CadastroDeDespesas/__tests__/CadastroForm.test.js
src/componentes/escolas/Despesas/CadastroDeDespesas/__tests__/CadastroFormCapital.test.js
src/componentes/escolas/Despesas/CadastroDeDespesas/__tests__/CadastroFormCusteio.test.js
src/componentes/escolas/Despesas/CadastroDeDespesas/__tests__/CadastroFormDespesaImposto.test.js
src/componentes/escolas/Despesas/CadastroDeDespesas/__tests__/CadastroFormFormik.test.js
src/componentes/escolas/Despesas/CadastroDeDespesas/__tests__/index.test.js

Esse PR:
- Aumenta a cobertura de testes unitários de despesas.
História: [AB#131508](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/131508)

feat(131508): Aumento de cobertura de testes

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/Tabela.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/index.test.js

Esse PR:
inclui os testes unitários da feature de duplicação de Prioridades
História [AB#127468](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127468)

test(127468): testes unitarios

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/BadgeCustom.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/Tabela.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/useGetPrioridades.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/usePatchPrioridade.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/usePostPrioridade.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/index.js
src/index.js
src/services/escolas/Paa.service.js

Esse PR:
- Inclui um componente para reutilização em duas colunas na tabela (BadgeCustom)
- Hook de API de duplicação
- Adiciona a funcionalidade de duplicar uma prioridade na tabela
- Os registros duplicados deve ser exibidos no topo da tabela
História [AB#127468](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127468)

feat(127468): Ação para duplicar Prioridade - Homolog

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/Tabela.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/index.test.js

Esse PR:
inclui os testes unitários da feature de duplicação de Prioridades
História [AB#127468](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127468)

test(127468): testes unitarios - Homolog

---

src/componentes/escolas/Despesas/CadastroDeDespesas/cadastro-de-despesas.scss

hotfix(132141): combo motivos de pagamento antecipado fora modal

hotfix(132141): combo motivos de pagamento antecipado fora modal

---

src/componentes/Globais/ExtracaoDados/Cards.js

[AB#129205](https://dev.azure.com/SME-Spassu/COPLAN%20-%20PTRF/_sprints/taskboard/COPLAN%20-%20PTRF%20Team/COPLAN%20-%20PTRF/Sprint%20015%20-%20COPLAN%20-%20PTRF?workitem=129205)
- Adicionado novo card de extração para saldo bancário das unidades

feat(129205): Adiciona novo card de extração para Saldo bancário das unidades

---

src/componentes/Globais/ExtracaoDados/__tests__/ExtracaoSaldosBancarios.test.js

[AB#129205](https://dev.azure.com/SME-Spassu/COPLAN%20-%20PTRF/_sprints/taskboard/COPLAN%20-%20PTRF%20Team/COPLAN%20-%20PTRF/Sprint%20015%20-%20COPLAN%20-%20PTRF?workitem=129205)
- Adicionado teste para novo card de extração para saldo bancário das unidades

test(129205): Adiciona testes unitários para a extração de saldos bancários

---

package.json
src/componentes/Globais/DatePickerField/index.js
src/componentes/escolas/Despesas/CadastroDeDespesas/cadastro-de-despesas.scss

hotfix(132141-132102): combo motivos de pagamento antecipado fora modal e ajuste datas com um dia a menos

hotfix(132141-132102): combo motivos de pagamento e datas

---

src/componentes/Globais/DatePickerField/index.js

hotfix(132141-132102): import moment

hotfix(132141-132102): import moment

---

package.json
src/componentes/Globais/DatePickerField/index.js
src/componentes/escolas/Despesas/CadastroDeDespesas/cadastro-de-despesas.scss
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/index.js

Esse PR:
- Altera o texto do modal de confirmação de deleção de prioridade.
História: [AB#127467](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127467)

feat(127467): Altera texto modal

---

src/utils/__tests__/Mascaras.test.js
src/utils/__tests__/money.test.js

[AB#132450](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/132450)

feat(132450): Completa testes de utils

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/BarraTopoTitulo/__tests__/index.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/BarraTopoTitulo/index.js

feature(129382): Exibe a referência do PAA no título da página

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/Resumo.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/useGetResumoPrioridades.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/usePatchPrioridade.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/usePostPrioridade.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/index.js
src/services/escolas/Paa.service.js

História [AB#127462](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127462)

feature(127462): Tabela de Resumo de Prioridades

---

src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/Justivicativa/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js

[AB#131974](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/131974)

feat(131974): Ajusta obrigatoriedade campo justificativa

---

src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/Justivicativa/__tests__/index.test.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/Justivicativa/index.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/__tests__/DataSaldoBancario.test.js
src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js

[AB#131974](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/131974)

feat(131974): Corrige e atualiza testes saldo bancário

---

src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/ResumoPrioridades.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/usePostPrioridade.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/index.js

[AB#133161](https://dev.azure.com/SME-Spassu/COPLAN%20-%20PTRF/_sprints/taskboard/COPLAN%20-%20PTRF%20Team/COPLAN%20-%20PTRF/Sprint%20017%20-%20COPLAN%20-%20PTRF?workitem=133161)
- Exibe mensagem de erro dinâmica, vinda do backend;
- Adiciona testes unitários para cenários de criação/atualização de prioridades.

Feature/133161 Verificação de Saldo Prioridade

---

package.json
src/componentes/Globais/DatePickerField/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/__tests__/ResumoPrioridades.test.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/hooks/usePostPrioridade.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Prioridades/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/hooks/useGetAcoesAssociacao.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/ReceitasPrevistas/hooks/useGetProgramasPddeTotais.js
src/services/escolas/Associacao.service.js
src/services/escolas/Paa.service.js

[AB#133236](https://dev.azure.com/SME-Spassu/COPLAN%20-%20PTRF/_sprints/taskboard/COPLAN%20-%20PTRF%20Team/COPLAN%20-%20PTRF/Sprint%20017%20-%20COPLAN%20-%20PTRF?workitem=133236)
- Adiciona page_size em query de receitas previstas

Feat/133236 Alterar limite na listagem de receitas previstas

---

src/componentes/Globais/CardsDevolucoesParaAcertoDaDre/__tests__/index.test.js
src/componentes/Globais/EscolheUnidade/__tests__/ListaDeUnidades.test.js
src/componentes/sme/Mandatos/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Despesas/TiposDeCusteio/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/__tests__/TabelaAssociacaoAcao.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Acoes/__tests__/index.test.js
src/componentes/sme/Parametrizacoes/Estrutura/AcoesPDDE/__tests__/ModalForm.test.js
src/componentes/sme/Parametrizacoes/Estrutura/Tags/__tests__/ModalFormTags.test.js
src/componentes/sme/Parametrizacoes/Receitas/ParametrizacoesMotivosEstorno/__tests__/Lista.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/TipoReceitaForm.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/components/UnidadesAssociadas/Lista.test.js
src/componentes/sme/Parametrizacoes/Receitas/TiposReceita/__tests__/components/VincularUnidades/index.test.js
src/paginas/escolas/Despesas/CadastroDeDespesas/__tests__/index.test.js
src/paginas/escolas/Despesas/EdicaoDeDespesa/__tests__/index.test.js

feature(134790): correcao testes unitarios

feature(134790): correcao testes unitarios

---

src/hooks/Globais/TagsInformacoesAssociacoes/useTagInformacaoAssociacaoEncerradaTemplate.js

Esse PR:
- Corrige a coluna de informações da tabela de ações das associações e ações.
História: AB#134848

fix(134848): Corrige coluna informações

---

src/componentes/dres/Associacoes/DadosDasAssociacoes/DadosDasContas/InfosContas.js

Esse PR:
- Altera permissão de ações da DRE sobre o encerramento de contas.
História: AB#135339

fix(135339): Altera permissão

---

src/componentes/Globais/EditorWysiwygCustom/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Relatorios/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Relatorios/styles.css

[AB#133240](https://dev.azure.com/SME-Spassu/COPLAN%20-%20PTRF/_sprints/taskboard/COPLAN%20-%20PTRF%20Team/COPLAN%20-%20PTRF/Sprint%20018%20-%20COPLAN%20-%20PTRF?workitem=133240)
- Adiciona nova seção de relatórios contendo a aba Introdução

fix(editor-wysiwyg-custom): Ajuste da nova seção de relatórios contendo a aba Introdução

---

src/componentes/Globais/EditorWysiwygCustom/editor-wysiwyg-custom.scss
src/componentes/Globais/EditorWysiwygCustom/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Relatorios/index.js
src/componentes/escolas/Paa/ElaboracaoPaa/ElaborarNovoPlano/Relatorios/styles.css

[AB#133240](https://dev.azure.com/SME-Spassu/COPLAN%20-%20PTRF/_sprints/taskboard/COPLAN%20-%20PTRF%20Team/COPLAN%20-%20PTRF/Sprint%20018%20-%20COPLAN%20-%20PTRF?workitem=133240)
- Adiciona nova seção de relatórios contendo a aba Introdução

Feat/133240: Adiciona seção de Introdução em relatórios de PAA
