- .gitignore
- Dockerfile
- conf/default.conf
- docker-compose.yml
- entrypoint.sh
- env_sample
Esse PR:
- Contém Configuração do Dockerfile
> Adiciona configuraçao do docker

- src/componentes/Despesas/ListaDeDespesas/index.jsx
Esse PR:
- Corrige erro que ocorria na lista de despesas quando alguns campos estavam vazios.
> Corrige lista despesas com campos vazios

- package.json
- src/componentes/Cabecalho/index.js
- src/componentes/Receitas/Formularios/index.js
- src/componentes/SidebarLeft/index.js
- src/paginas/Login/LoginForm.js
- src/rotas/index.js
- src/services/Receitas.service.js
- src/services/auth.service.js
- src/utils/ValidacoesAdicionaisFormularios.js
> Autorizaçao de usuario

- src/componentes/Receitas/Formularios/index.js
- src/paginas/Login/LoginForm.js
ESSe PR contém:
- No término de criação de receita o usuário é redirecionado para lista de receita.
> Criaçao de receita redireciona para list de receitas

- src/componentes/Receitas/Formularios/index.js
- src/services/auth.service.js
- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR contém.
- Modal para confirmação de cancelamento de receita.
> Modal para confirmar cancelamento de inclusao de receita

- src/componentes/SidebarLeft/index.js
- Atualizaçao do menu creditos da escola.
> Atualizaçao menu creditos da escola

- src/componentes/Despesas/ListaDeDespesas/index.jsx
Esse PR:
- Muda o formato da data exibida na lista de despesas para DD/MM/YYYY.
> Altera formato da data na lista despesas

- src/componentes/Despesas/ListaDeDespesas/index.jsx
- src/componentes/SidebarLeft/index.js
Esse PR:
- Altera formato da data na lista despesas para DD/MM/YYY.  História 13075.
> Altera formato da data na lista de despesas

- src/componentes/Receitas/Formularios/index.js
- src/componentes/Receitas/ListaDeReceitas/index.js
- src/paginas/Receitas/EdicaoReceita/index.js
- src/rotas/index.js
- src/services/Receitas.service.js
> Ediçao de uma receita.

- env_sample
- src/services/Api/index.js
- src/services/Receitas.service.js
- Correção da leitura da variável de ambiente API_URL.
> API_URL setada corretamente

- src/componentes/Receitas/Formularios/index.js
- src/services/Receitas.service.js
- src/services/constantes.js
> Deleçao de receita.

- src/componentes/Despesas/CadastroDeDespesas/CadastroForm.js
- src/paginas/Despesas/EdicaoDeDespesa/index.js
- src/utils/ValidacoesAdicionaisFormularios.js
> Finalizando Deletar Despesa

- src/componentes/Receitas/ListaDeReceitas/index.js
- src/services/Receitas.service.js
- Correção na paginação de receitas.
> Correção paginação de receitas

- src/componentes/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/Despesas/CadastroDeDespesas/CadastroFormCapital.js
- src/componentes/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
- src/context/Despesa/index.js
- Realizando pequenos ajustes de layout
> Realizando ajustes no Cadastro de Despesa

- src/componentes/Receitas/Formularios/index.js
- Correção grafia excluir receita.
> Correçao grafia excluir receita.

- src/componentes/Despesas/CadastroDeDespesas/CadastroForm.js
- Corrigindo ortografia da mensagens de Cancelar e Excluir Despesa
> Corrigindo ortografia das mensagens

- src/componentes/Despesas/CadastroDeDespesas/CadastroForm.js
- src/utils/Modais.js
- Exibindo mensagem ao escolher Tipo de aplicação do recurso = Capital
> Exibir Mensagem no Formulário de Despesas e Refatorando os Modais

- src/componentes/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/ModalBootstrap/index.js
- src/utils/Modais.js
- Criando Componente ModalBootstrap
> Criando Componente ModalBootstrap

- src/services/Receitas.service.js
- Os requests de receitas usam o authorization token.
> Requests de receitas usando authorization token

- src/componentes/Despesas/ListaDeDespesas/index.jsx
- Finalizando Filtros Avançados em Despesas
> Resolvendo conflitos e criando o PR

- src/services/auth.service.js
- Correção para a exibição da mensagem de erro.
> Correçao mensagem de erro.

- src/services/Despesas.service.js
- Uso do token de autenticaçao nos processos despesas.
> Uso do token de autenticaçao nos processos despesas.

- src/services/RateiosDespesas.service.js
- Usa token nos requests de rateios despesas.
> Usa token nos requests de rateios despesas.

- src/componentes/DatePickerField/index.js
- No momento da edição de uma receita a sua data é mostrada corretamente.
> Correção na exibição da data de um receita na edição.

- src/componentes/PrestacaoDeContas/SelectPeriodoConta.js
- src/componentes/PrestacaoDeContas/index.js
- Incluindo Texto Última conciliação e botão iniciar prestação de contas
> Incluindo Texto Última conciliação e botão iniciar prestação de contas

- public/index.html
- src/App.js
- src/componentes/PrestacaoDeContas/DetalheDasPrestacoes/index.js
> Removendo cache da páginas

- src/App.js
> Resolvendo Rotas

- src/App.js
> Resolvendo problemas com Rotas detalhe-das-prestacoes

- src/componentes/Associacao/DadosDaAssociacao/index.js
- src/componentes/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/Receitas/Formularios/index.js
- src/utils/Modais.js
- Finalizando ajustes pontuais solicitados por Ananda Grinkraut
> Finalizando ajustes pontuais solicitados por Ananda Grinkraut

- src/componentes/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/paginas/Login/index.js
- src/paginas/PrestacaoDeContas/index.js
> Incluindo state Reload

- src/componentes/Dashborard/DashboardCard.js
Esse PR:
- Adiciona campo outras receitas no painel de ações.
> feat(14998): Outras receitas no painel de ações

- package.json
- src/componentes/PrestacaoDeContas/index.js
- Finalizando ajustes feature 15110
> Finalizando ajustes feature 15110

- src/componentes/PrestacaoDeContas/index.js
- Ajustes na página do demonstrativo financeiro.
> Ajustes para o demonstrativo financeiro.

- src/services/auth.service.js
> Correção no Logout

- src/componentes/PrestacaoDeContas/DetalheDasPrestacoes/TabelaDeLancamentosDespesas/index.js
- src/componentes/PrestacaoDeContas/DetalheDasPrestacoes/TabelaDeLancamentosReceitas/index.js
- src/utils/Modais.js
- Corrigindo textos errados da mensagens Sprint 4
> Corrigindo textos errados

- src/utils/Modais.js
- Finalizando ajustes sprint formatação valor dentro do Modal
> Finalizando ajustes sprint formatação valor dentro do Modal

- src/componentes/PrestacaoDeContas/RelacaoDeBens/index.js
- src/componentes/PrestacaoDeContas/index.js
- src/componentes/PrestacaoDeContas/prestacao-de-contas.scss
- src/services/RelacaoDeBens.service.js
- Geração da prévia do documento de relação de bens.
- Geração do documento final de relação de bens.
> Geração do documento de relação de bens.

- src/componentes/PrestacaoDeContas/DemonstrativoFinanceiro/index.js
- src/componentes/PrestacaoDeContas/RelacaoDeBens/index.js
- src/componentes/PrestacaoDeContas/index.js
- src/services/DemonstrativoFinanceiro.service.js
- Ajustes no componente de demonstrativo financeiro.
- Ajustes no componente de relação de bens
> Correção demonstrativo financeiro

- src/componentes/PrestacaoDeContas/DetalheDasPrestacoes/TabelaValoresPendentesPorAcao/index.js
- src/componentes/PrestacaoDeContas/DetalheDasPrestacoes/TabelaValoresPendentesPorAcao/styles.css
- src/componentes/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/services/TabelaValoresPendentesPorAcao.service.js
- Exibição da tabela de valores pendentes.
> Tabela de valores pendentes.

- src/componentes/Despesas/CadastroDeDespesas/CadastroForm.js
- Troca da localização da mensagem no cadastro despesa quando à divergência de valores.
> Troca da localização da mensagem no cadastro despesa

- src/componentes/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/Despesas/CadastroDeDespesas/CadastroFormCapital.js
- src/componentes/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
- src/componentes/Receitas/Formularios/index.js
- src/componentes/Receitas/ListaDeReceitas/index.js
- Loading nas páginas de receitas.
- Correção nas mensagens de erros no cadastro despesa.
> Colocar Loading nas páginas de receitas quando tiver consultas a api.

- src/componentes/PrestacaoDeContas/DetalheDasPrestacoes/TabelaValoresPendentesPorAcao/index.js
> Correçao cores na tabela de valores pendentes

- src/componentes/Despesas/CadastroDeDespesas/CadastroForm.js
- src/utils/ValidacoesAdicionaisFormularios.js
- Finalizando tornar obrigatório campo CPF em despesas
> Finalizando Tornar Obrigatório Campo CPF em Despesas

- src/componentes/Despesas/CadastroDeDespesas/CadastroForm.js
Finalizando exibir loading em despesas
> Finalizando exibir loading em despesas

- src/componentes/Receitas/FormFiltrosAvancados/index.js
Esse PR:
- Cria um botão para limpar o formulário de filtros de receitas.
> feat(16500): Recurso limpar filtros na lista de receitas

- src/componentes/Despesas/CadastroDeDespesas/CadastroFormCapital.js
- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR:
- Adiciona máscara ao campo Número do processo de incorporação no lançamento de despesas.
> feat(16683): Add máscara ao campo Número do processo de incorporação

- src/componentes/Associacao/DadosDaAssociacao/index.js
- src/componentes/ValoresReprogramados/index.js
- Finalizando Feature/17922 valores reprogramados - Incluir Loading
> Finalizando incluir loading valores reprogramados

- src/componentes/Despesas/FormFiltrosAvancados/index.js
- Botão para limpar filtros na listagem de despesas.
> Adição de botão 'Limpar Filtros' nos filtros de despesas

- src/componentes/Receitas/Formularios/index.js
Resolvendo correções quando tipo de receita for Ambos
> Resolvendo correções quando tipo de receita for Ambos

- src/componentes/Receitas/Formularios/index.js
- src/componentes/Receitas/Schemas/index.js
Esse PR:
- Implementa o detalhamento da receita no cadastro de crédito.
> feat(17923): Cria detalhamento da receita no cadastro de crédito

- src/componentes/PrestacaoDeContas/DetalheDasPrestacoes/TopoComBotoes/index.js
- src/componentes/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/services/PrestacaoDeContas.service.js
- Lógica para vincular observações à ação selecionada.
- Mudança do título da página de conciliação.
> Vínculo observações à ação.

- src/componentes/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/SidebarLeft/index.js
Remove do menu a opção de cadastrar despesa e renomeia o botão "Cancelar" no form para "Voltar".
> feat(17931): Remove do menu a opção cadastro de despesas

- src/componentes/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/Despesas/CadastroDeDespesas/CadastroFormCapital.js
- src/componentes/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
Esse PR:
- Faz ajustes de texto no cadastro de despesas.
> feat(17934): Ajustes de textos no cadastro de despesas

- src/componentes/PrestacaoDeContas/DemonstrativoFinanceiro/index.js
Esse PR:
- Remove a paginação que era exibida no relatório financeiro da prestação de contas.
> feat(17936): Remove paginação da prestação de contas

- src/componentes/SidebarLeft/index.js
- src/services/auth.service.js
- Incluir tipo escola junto ao nome no menu lateral.
> Incluir tipo escola junto ao nome no menu lateral.

- src/componentes/Receitas/Formularios/index.js
- src/paginas/Login/index.js
- src/paginas/Login/login.scss
- Finalizando Feature 18429 Correções Necessárias
> Finalizando Feature 18429 Correções Necessárias

- src/componentes/ValoresReprogramados/index.js
- Finalizando Feature/correcoes escoha sprint 6
> Finalizando Correcoes Escoha Sprint 6

- src/componentes/PrestacaoDeContas/DemonstrativoFinanceiro/index.js
> Finalizando Feature-18894

- src/componentes/PrestacaoDeContas/index.js
Esse PR:
- Corrige bug na exibição na data de preenchimento da ata
Estava sendo exibida data de preenchimento mesmo quando a ata ainda não
tinha sido preenchida.
> fix(18895): Corrige bug na exibição na data de preenchimento da ata

- src/componentes/Associacao/DadosDasContas/FormDadosDasContas/index.js
- Finalizando Feature Novos Ajustes nas Labels
- Ajuste de texto na conta do programa quando for cartão
- Alinhamento realizado pelos campos
> Finalizando Feature Novos Ajustes nas Labels

- src/componentes/GeracaoDaAta/VisualizacaoDaAta/TabelaDinamica/index.js
- src/componentes/GeracaoDaAta/VisualizacaoDaAta/TabelaTotais/index.js
Esse PR:
- Ajusta o cálculo do total de créditos futuros não estava somando os repasses de livre aplicação
> feat(19339): Ata linha créditos futuros soma repasses RLA no total

- package.json
- Atualizando a versão do front
> Atualizando a versão do front

- src/App.js
- src/componentes/escolas/Associacao/DadosDaAssociacao/index.js
- src/componentes/escolas/Associacao/DadosDasContas/index.js
- src/componentes/escolas/Associacao/Membros/index.js
- src/componentes/escolas/Dashborard/DashboardCard.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/FormFiltrosAvancados/index.js
- src/componentes/escolas/Despesas/ListaDeDespesas/index.jsx
- src/componentes/escolas/PrestacaoDeContas/index.js
- src/componentes/escolas/Receitas/FormFiltrosAvancados/index.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/escolas/Receitas/ListaDeReceitas/index.js
- src/paginas/Login/EsqueciMinhaSenha/index.js
- src/paginas/Login/RedefinirMinhaSenha/index.js
- src/utils/Modais.js
- Refatorando Nova Arquitetura
> Refatorando Nova Arquitetura

- src/componentes/dres/Associacoes/FiltrosAssociacoes.js
- Finalizando ajustes de labels
> Finalizando ajustes de labels

- src/services/dres/Associacoes.service.js
- src/utils/RedirectLoginVisaoUe.js
- Finalizando Feature/20311 condicionais para UUID
> Finalizando condicionais para uuid

- src/services/escolas/Associacao.service.js
- src/services/escolas/Despesas.service.js
- src/services/escolas/Receitas.service.js
* Os serviços de receitas que precisam enviar uuid da associação foram atualizados.
* Os serviços de membros da associação que precisam enviar uuid da associação foram atualizados.
* Os serviços de despesas que precisam enviar uuid da associação foram atualizados.
> Features/20439 Atualizaçao das chamadas que precisam enviar o uuid da associacao.

- src/componentes/dres/Associacoes/DadosDasAssociacoes/RegularidadeUnidadeEducacional/index.js
- src/componentes/dres/Associacoes/index.js
- src/paginas/dres/Associacoes/RegularidadeUnidadeEducacional/index.js
- src/rotas/index.js
- src/services/dres/Associacoes.service.js
- src/services/dres/RegularidadeUnidadeEducaional.service.js
* Controle da regularidade da unidade educacional/associação.
> Features/20362 dres regularidade unidade educacional.

- src/services/visoes.service.js
- Criando dados mockados para representar visão SME
> Setando dados Fake para visão SME

- src/componentes/Globais/Cabecalho/index.js
- src/componentes/Globais/SidebarLeft/getUrls.js
- src/services/visoes.service.js
- Finalizando Feature/20066 ajustes visao dre
> Finalizando Feature 20066 Ajustes Visão Dre

- src/paginas/escolas/404/index.js
- src/paginas/escolas/404/pagina-404.scss
- Finalizando Feature 20066 Ajustes Click Login Página de Erro
> Finalizando Feature 20066 Ajustes Click Login Página de Erro

- src/componentes/dres/Associacoes/DadosDasAssociacoes/TopoComBotoes.js
- Finalizando Feature/20335 ajustes link regularidade
> Finalizando Feature/20335 - Ajustes Link Regularidade

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaDeLancamentosDespesas/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- Finalizando ajustes na fluxo de conciliação bancária
> Efetuando ajustes na fluxo de conciliação bancária

- src/componentes/dres/Diretoria/Atribuicoes/index.js
Esse PR contém
* Correção ao Cancelar atribuição
* Correção ao fechar a mensagem de 'Desfazer' atribuição
> Features/correções atribuições

- src/componentes/escolas/PrestacaoDeContas/ModalConcluirPeriodo.js
- src/componentes/escolas/PrestacaoDeContas/TopoSelectPeriodoBotaoConcluir.js
- src/componentes/escolas/PrestacaoDeContas/index.js
- Finalizando inclusão de ModalConcluirPeriodo
> Incluindo ModalConcluirPeriodo

- src/componentes/dres/Diretoria/Atribuicoes/index.js
- src/componentes/dres/Diretoria/TecnicosDaDiretoria/CadastroTecnicosDre.js
- src/rotas/index.js
* Direcionamento para unidades de atribuição com filtro setado.
> Features/20477 conferir atribuicões

- src/componentes/escolas/PrestacaoDeContas/DemonstrativoFinanceiro/index.js
- src/componentes/escolas/PrestacaoDeContas/RelacaoDeBens/index.js
- src/componentes/escolas/PrestacaoDeContas/TopoSelectPeriodoBotaoConcluir.js
- src/componentes/escolas/PrestacaoDeContas/index.js
* Correção na exibição da data nas previas dos documentos
> Features/correção na exibição da data nas previas dos documentos

- src/componentes/escolas/PrestacaoDeContas/DemonstrativoFinanceiro/index.js
- src/componentes/escolas/PrestacaoDeContas/RelacaoDeBens/index.js
* Correção na data na geração da prévia.
> Features/correçao na exibiçao data nas previas dos documentos

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
Corrige a referência feita a repasses des períodos únicos da Ata.
> fix(23503): Corrige referência de período .u na Ata

- src/componentes/escolas/Associacao/DadosDasContas/FormDadosDasContas/index.js
- src/componentes/escolas/Associacao/DadosDasContas/index.js
* Bug: Correção ao salvar informações de dados da associação dados da conta.
> Features/23150 dados associacao o botao nao salva informaçoes

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
* Valor realizado agora e atualizado de acordo com valor total do capital.
> Features/22673 bug valor realizado de capital não preenche automaticamente

- src/services/escolas/DemonstrativoFinanceiro.service.js
> Features/correçao metodos get 

- README.md
- package.json
> docs(1.2.0): Atualiza versão para 1.2.0

- src/componentes/Globais/EsqueciMinhaSenha/RecuperacaoResposta/index.js
- src/componentes/Globais/EsqueciMinhaSenha/RecuperacaoResposta/respostaErro.js
- src/componentes/Globais/EsqueciMinhaSenha/RecuperacaoResposta/respostaSucesso.js
- src/componentes/Globais/EsqueciMinhaSenha/index.js
- Finalizando ajustes sprint 11
> Finalizando ajustes sprint 11

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- Eliminando return erros de CadastroForm, desnecessário
> Eliminando return erros de CadastroForm

- src/utils/Modais.js
- Finalizando alteração da mensagem Modal Período Fechado, que aparece em Despesas e Receitas
> Alterando mensagem Modal Período Fechado, que aparece em Despesas e Receitas

- README.md
- package.json
> docs(1.3.0): Inicia versão 1.3.0 Sprint 12

- src/componentes/dres/Associacoes/DadosDasAssociacoes/ProcessosSei/ProcessoSeiRegularidade.js
Esse PR:
- Altera o cadastro de processo SEI de uma unidade incluindo a máscara para
digitação do processo de regularidade.
> feat(22905): Add máscara ao processo SEI de regularidade

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/Justivicativa/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaDeLancamentosDespesas/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaDeLancamentosReceitas/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TopoComBotoes/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
Esse PR:
- Altera o o módulo de conciliação que passa a verificar se o período está fechado e não permite a conciliação se estiver.
> feat(27676): Bloqueia conciliação de período fechado

- package.json
- src/index.js
> Features/27024 uso sentry front.

- src/componentes/dres/Diretoria/DadosDaDiretoria/index.js
- src/utils/Modais.js
Esse PR:
- Altera a edição de dados da diretoria para apresentar mensagem de gravação com sucesso.
> feat(23152): Confirma gravação dados diretoria

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/InformacoesDevolucaoAoTesouro.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoApuracao/index.js
- src/componentes/escolas/Associacao/ModalMembros.js
- Finalizando ajustes de labels sprint 12
> Finalizando ajustes de labels sprint 12

- src/componentes/Globais/SidebarLeft/getUrls.js
- src/componentes/sme/AcompanhamentoPcsSme/BarraDeStatus.js
- src/componentes/sme/AcompanhamentoPcsSme/DashboardCard.js
- src/componentes/sme/AcompanhamentoPcsSme/SelectPeriodo.js
- src/componentes/sme/AcompanhamentoPcsSme/dashboard.scss
- src/componentes/sme/AcompanhamentoPcsSme/index.js
- src/paginas/SME/AcompanhamentoPcsSme/index.js
- src/rotas/index.js
- src/services/sme/DashboardSme.service.js
- src/services/visoes.service.js
Esse PR implementa o painel de resumo geral do acompanhamento de prestações de contas da visão SME.
> Feature(28840) Acompanhamento de PCs SME

- src/componentes/sme/AcompanhamentoPcsSme/BarraDeStatus.js
- src/componentes/sme/AcompanhamentoPcsSme/BarraTotalUnidades.js
- src/componentes/sme/AcompanhamentoPcsSme/DashboardCard.js
- src/componentes/sme/AcompanhamentoPcsSme/index.js
Esse PR altera o layout do painel de acompanhamento de Prestações
de contas da SME para apresentar o total de unidades em
uma barra horizontal. 
Necessário para se adequar a modificações feitas no protótipo após inicio do desenvolvimento da história.
> feat(28840)Linha de total Acompanhamento PC SME

- src/componentes/sme/AcompanhamentoPcsSme/ResumoPorDre.js
- src/componentes/sme/AcompanhamentoPcsSme/index.js
Esse PR:
- Exibe informações resumidas por DRE para acompanhamento de prestações de contas pela SME.
> feat(28852): Resumo por DRE no acompanhamento PC SME

- src/componentes/escolas/Associacao/Membros/ConfirmaDeleteMembroDialog.js
- src/componentes/escolas/Associacao/Membros/index.js
- src/componentes/escolas/Associacao/TabelaMembros/index.js
- src/services/escolas/Associacao.service.js
Esse PR:
- Implementa o recurso de apagar um membro da associação.
> feat(29301): Apaga membro associação

- src/componentes/sme/AcompanhamentoPcsSme/ResumoPorDre.js
Esse PR faz ajustes solicitados pela PO durante a review da Sprint 13:
- Acrescenta título à coluna de ações em SME > Acompanhamento de PCs.
> refac(Sprint 13): Ajustes solicitados na review

- src/componentes/escolas/PrestacaoDeContas/index.js
- Finalizando Feature 31469 - [Associações] Acrescentar mensagem ao loading de geração de documentos da prestação de contas
> Incluindo mensagem na geração de documentos assíncrona

- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoDadosDasUes/TabelaListaPrestacoesDaDre.js
- Finalizando Feature 31430 - [DRE] No relatório consolidado DRE exibir vazios em vez zeros nos valores das PCs não apresentadas
> Substituindo zeros por espaço em branco quando status da PC for NAO_APRESENTADA

- src/componentes/sme/Parametrizacoees/Estrutura/AcoesDasAssociacoes/AutoCompleteAssociacoes.js
- src/componentes/sme/Parametrizacoees/Estrutura/AcoesDasAssociacoes/index.js
Buscando com o Autocomplete em todas as associacoes e não mais nas ações. Setando automaticamente a unidade selecionada quando for escolhida no Autocomplete
> - Finalizando Feature 29897 - ajustes

- src/componentes/sme/Parametrizacoees/Estrutura/AcoesDasAssociacoes/TabelaAcoesDasAssociacoes.js
- src/componentes/sme/Parametrizacoees/Estrutura/AcoesDasAssociacoes/index.js
- src/componentes/sme/Parametrizacoees/Estrutura/Associacoes/ModalFormAssociacoes.js
- src/componentes/sme/Parametrizacoees/Estrutura/Associacoes/index.js
- Finalizando ajustes sprint 14
> Finalizando ajustes da sprint 14

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
- Alterando label de Tipo de custeio para Tipo de despesa de custeio
> Alterando label de Tipo de custeio para Tipo de despesa de custeio

- src/componentes/escolas/Associacao/Membros/index.js
- src/componentes/escolas/Associacao/ModalMembros.js
Esse PR:
- Adiciona ao formulário de membros da associação campos de telefone e endereço para o cargo de presidente da diretoria executiva.
[AB#33201](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/33201)
> feat(33201): Novos campos presidente associação

- .gitignore
- src/componentes/Globais/Cabecalho/cabecalho.scss
- src/componentes/Globais/Cabecalho/index.js
- src/componentes/Globais/SidebarLeft/index.js
[AB#29932](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/29932)
- Removido do menu hamburger as informacoes de usuário
- Adicionado menu dropdown para informacoes de usuário no cabeçalho
- alterado icone das notificações para 'sininho'
> Alterada a posicao das informacoes de usuario

- src/componentes/escolas/MeusDados/formInicialEditar.js
- src/componentes/escolas/MeusDados/index.js
- src/services/auth.service.js
Esse PR corrige erro na atualização de e-mail e senha. O front não estava passando corretamente a autenticação necessária.
O e-mail alterado também não estava sendo atualizado no campo do formulário.
Resolve bug [AB#32999](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/32999)
> fix(32999): Erro na atualização de e-mail

- src/componentes/sme/Parametrizacoees/Despesas/TiposDeCusteio/BtnAdd.js
- src/componentes/sme/Parametrizacoees/Despesas/TiposDeCusteio/Filtros.js
- src/componentes/sme/Parametrizacoees/Despesas/TiposDeCusteio/ModalConfirmDelete.js
- src/componentes/sme/Parametrizacoees/Despesas/TiposDeCusteio/ModalForm.js
- src/componentes/sme/Parametrizacoees/Despesas/TiposDeCusteio/ModalInfoNaoPodeExcluir.js
- src/componentes/sme/Parametrizacoees/Despesas/TiposDeCusteio/ModalInfoUpdateNaoPermitido.js
- src/componentes/sme/Parametrizacoees/Despesas/TiposDeCusteio/Tabela.js
- src/componentes/sme/Parametrizacoees/Despesas/TiposDeCusteio/YupSignupSchemaTags.js
- src/componentes/sme/Parametrizacoees/Despesas/TiposDeCusteio/index.js
- src/rotas/index.js
- src/services/sme/Parametrizacoes.service.js
Esse PR:
- Implementa o cadastro de tipos de custeio nas parametrizações do sistema.
História: [AB#29935](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/29935)
> feat(29935): Cadastro de tipos de custeio

- src/componentes/Globais/ArquivosDeCarga/YupSignupSchemaArquivosDeCarga.js
- Incluindo outros MIME TYPES para validar se é arquivo csv
> Incluindo outros MIME TYPES para validar se é arquivo csv

- README.md
> docs(1.7.0): Atualização versão

- entrypoint.sh
- src/componentes/Globais/EditorWysiwyg/index.js
- Incluindo Editor Key no Front
> Fix correcoes entrypoint

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaValoresPendentesPorAcao/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaValoresPendentesPorAcao/styles.css
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- Finalizando Feature 34030 - [Associação] Conciliação bancária: Alterações no quadro resumo
> Finalizando Feature 34030 - [Associação] Conciliação bancária: Alterações no quadro resumo

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- Finalizando Corrigindo passagem de parametro (conta ao inves de periodo) para método patchDesconciliarTransacao
> Corrigindo passagem de parametro (conta ao inves de periodo) para método patchDesconciliarTransacao

- src/componentes/dres/Associacoes/DadosDasAssociacoes/RegularidadeUnidadeEducacional/index.js
Esse PR:
- Implementa a verificação da permissão de atualização na página de regularidade de uma associação.
História: [AB#25394](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/25394)
> feat(25394): Verifica permissão pode atualizar regularidade

- src/componentes/escolas/GeracaoDaAta/ModalEditarAta.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TopoComBotoes/index.js
- src/componentes/escolas/PrestacaoDeContas/DemonstrativoFinanceiro/index.js
- src/componentes/escolas/PrestacaoDeContas/RelacaoDeBens/index.js
- src/componentes/escolas/PrestacaoDeContas/TopoSelectPeriodoBotaoConcluir.js
- src/componentes/escolas/PrestacaoDeContas/index.js
Esse PR cria na funcionalidade de prestação de contas a aplicação das permissões:
- Pode concluir período
- Pode gerar prévias
- Pode baixar documentos
- Pode atualizar atas
História [AB#25385](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/25385)
> feat(25385): Aplica permissões em prestações de contas

- src/componentes/sme/ConsultaDeSaldosBancarios/TabelaSaldosPorDre.js
- src/componentes/sme/ConsultaDeSaldosBancarios/index.js
- src/services/sme/ConsultaDeSaldosBancarios.service.js
- Finalizando Feature 35170 - [SME] Consulta de saldos bancários: Por Diretoria
> Finalizando feature 35170 saldos por dre

- src/componentes/sme/ConsultaDeSaldosBancarios/TabelaSaldosPorUeDre.js
- src/componentes/sme/ConsultaDeSaldosBancarios/index.js
- src/services/sme/ConsultaDeSaldosBancarios.service.js
- Finalizando Feature 35171 - [SME] Consulta de saldos bancários: Por tipo de UE e DRE
> Finalizando Featue 35171 saldos por ue e dre

- src/componentes/escolas/PrestacaoDeContas/DemonstrativoFinanceiroPorConta/index.js
- src/componentes/escolas/PrestacaoDeContas/index.js
- src/services/escolas/DemonstrativoFinanceiro.service.js
Esse PR alterar a geração do demonstrativo financeiro que passa a ser gerado por conta e não mais por ação.
[AB#34019](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34019)
> feat(34019): Demonstrativo financeiro por conta

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/data-saldo-bancario.scss
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/services/escolas/PrestacaoDeContas.service.js
- src/services/sme/Parametrizacoes.service.js
- Finalizando Feature 35167 - [Associações] - Conciliação bancária: upload do extrato bancário
> finalizando feature 35167 - upload extrato bancario

- src/componentes/Globais/ModalBootstrap/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/componentes/sme/ConsultaDeSaldosBancarios/ConsultaDeSaldosBancariosDetalhesAssociacoes.js
- src/componentes/sme/ConsultaDeSaldosBancarios/ModalVisualizarExtrato.js
- src/componentes/sme/ConsultaDeSaldosBancarios/consulta-saldos-bancarios.css
- src/paginas/Login/LoginForm.js
- src/services/escolas/PrestacaoDeContas.service.js
- Finalizando Feature 35175 - [SME] Consulta de saldos bancários: Por Unidade Escolar: Download e Preview do extrato anexado
> feature 35175- download e preview extrato bancario

- src/componentes/escolas/PrestacaoDeContas/DemonstrativoFinanceiroPorConta/index.js
- src/componentes/escolas/PrestacaoDeContas/RelacaoDeBens/index.js
Esse PR ajusta o botão de download de prévias dos documentos de PC para
ser exibido apenas se for uma prévia.
> feat(31433): Previas de documentos assíncronos botão download

- src/componentes/escolas/PrestacaoDeContas/DemonstrativoFinanceiroPorConta/index.js
- src/componentes/escolas/PrestacaoDeContas/RelacaoDeBens/index.js
- src/componentes/escolas/PrestacaoDeContas/prestacao-de-contas.scss
- src/services/escolas/DemonstrativoFinanceiro.service.js
Em prestação de contas implementa opção de fazer o
download do demonstrativo financeiro em PDF ou XLSX.
História: [AB#34020](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34020)
> feat(34020): Download D.Financeiro em XLSX ou PDF

- README.md
- package.json
> docs(1.9.0): Inicio Sprint 18

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaValoresPendentesPorAcao/index.js
- Alterando ordem de exibição das linhas da coluna
> Alterando ordem de exibição das linhas da coluna

- src/componentes/escolas/Despesas/FormFiltrosAvancados/index.js
- src/componentes/escolas/Despesas/ListaDeDespesas/index.jsx
- Finalizando Feature 39207 - [Associação] Renomear os status de gastos das escolas de INCOMPLETO para RASCUNHO
> Feature 39207 - [Associação] Renomear os status de gasto

- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoDadosDasUes/index.js
> Finalizando ajustes

- package.json
[AB#41498](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/41498)
> docs(1.13.0): Abre Sprint 22

- src/componentes/Globais/GestaoDePerfis/index.js
- src/services/GestaoDePerfis.service.js
Esse PR corrige bug na lista de usuários no perfil de acessos. A lista de usuários estava exibindo usuários que não
pertenciam à unidade.
Fix [AB#40708](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/40708)
> fix(40708): Corrige lista de usuários no perfil de acessos

- src/services/visoes.service.js
Corrige o comportamento do login que travava no
primeiro login de um usuário que não tem visão
SME.
[AB#40231](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/40231)
> fix(40231): Corrige login usuário sem visão SME

- package.json
> docs(1.14.0): Abre versão 1.14.0

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/metodosAuxiliares.js
Esse PR:
- Remove o preenchimento automático do campo Quantidade de itens no cadastro de despesa quando o tipo for Capital
História: [AB#42534](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42534)
> feat(42534): Altera preenchimento campo Quantidade de itens

- src/componentes/Globais/Dashborard/DashboardCard.js
- src/componentes/Globais/Dashborard/DashboardCardInfoConta.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/FormRecebimentoPelaDiretoria.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/objetoColunasDinamicas.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoApuracao/TabelaExecucaoFinanceira.js
- src/componentes/escolas/Associacao/ModalMembros.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
- src/componentes/escolas/Receitas/FiltroPorTipoReceita/index.js
- src/componentes/escolas/Receitas/FormFiltrosAvancados/index.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/escolas/Receitas/ModalSelecionaRepasse.js
- src/componentes/sme/PainelParametrizacoes/index.js
- src/componentes/sme/Parametrizacoees/Despesas/TiposDeCusteio/BtnAdd.js
- src/componentes/sme/Parametrizacoees/Despesas/TiposDeCusteio/ModalForm.js
- src/componentes/sme/Parametrizacoees/Despesas/TiposDeCusteio/index.js
Esse PR:
- Realiza ajustes de textos em diversos pontos da aplicação
História [AB#40185](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/40185)
> feat(40185): Realiza ajustes de textos diversos

- src/componentes/Globais/GestaoDePerfis/GestaoDePerfisForm.js
- src/componentes/Globais/GestaoDePerfis/GestaoDePerfisFormFormik.js
Esse PR:
- Corrige a permissão de edição/inclusão do email na Gestão de Perfis. Permitindo sua edição ou alteração
Historia: [AB#41618](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/41618)
> fix(41618): Corrige a permissão de edição/inclusão do email na Gestão de Perfis

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroSaidaForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/ModalDeletarDespesa.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR:
- Permite a partir da edição do Crédito de Recursos Externos editar/excluir uma despesa vinculada
História: [AB#42267](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42267)
> feat(42267): Créditos de recursos externos: permitir edição/exclusão a partir da entrada

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroSaidaForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/ModalDeletarDespesa.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/utils/ValidacoesAdicionaisFormularios.js
História: [AB#42574](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42574)
> homolog(42574): Posição em Develop às 15:35

- src/componentes/escolas/Associacao/Membros/index.js
- src/componentes/escolas/Associacao/ModalMembros.js
- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR:
- Implementa no formulário de membro da associação o campo cpf para o estudante
História: [AB#39140](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39140)
> feat(39140): [Associação] Cadastro de membros deve gravar o CPF também para alunos

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroSaidaForm.js
Esse PR:
- Altera título e texto no modal que informa que os valores do Recurso Externo e sua saída são diferentes.
História: [AB#42267](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42267)
> feat(42267): Altera texto modal valores distintos

- Jenkinsfile
História: [AB#42574](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42574)
> homolog(42574): Posição em Develop 08/07/2021 às 17:46

- Jenkinsfile
[AB#43368](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43368)
> Posição de Develop em 12/07 13:24

- Jenkinsfile
- package.json
[AB#41495](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/41495)
> Posição de Develop em 13/07 13:27

- src/componentes/escolas/Despesas/ListaDeDespesas/index.jsx
Esse PR:
Altera a saída vinculada a créditos de recursos externos para utilização de formulário simplificado
História: [AB#42276](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42276)
> feat(42276): Gastos da escola: Na edição de saídas vinculadas a créditos de recursos externos usar formulário simplificado

- src/componentes/escolas/Receitas/FiltroPorTipoReceita/index.js
- src/componentes/escolas/Receitas/FormFiltrosAvancados/index.js
- src/componentes/escolas/Receitas/ListaDeReceitas/index.js
- src/componentes/escolas/Receitas/SomaDosCreditos/index.js
- src/componentes/escolas/Receitas/SomaDosCreditos/soma-dos-creditos.scss
- src/services/escolas/Receitas.service.js
Esse PR:
- Realiza chamada ao endpoint que retorna os valores,
- Exibe tabela com soma dos valores sem filtro,
- Exibe tabela com soma dos valores com filtro.
História: [AB#29419](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/29419)
> feat(29419) Exibe tabela com soma dos valores de créditos

- src/componentes/sme/Parametrizacoees/Estrutura/Associacoes/TabelaAssociacoes.js
feat(34948): Altera coluna CNPJ para nome DRE
Esse PR:
- Altera coluna CNPJ para nome DRE
- Reordena as colunas para: (Nome da Associação, Unidade educacional, DRE)
História: [AB#34948](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34948)
> feat(34948) Altera coluna CNPJ para nome DRE

- src/componentes/dres/Dashboard/BarraDeStatus.js
- src/componentes/dres/Dashboard/dashboard.scss
- src/componentes/dres/Dashboard/index.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/FormFiltros.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/index.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/objetoColunasDinamicas.js
- src/services/dres/PrestacaoDeContas.service.js
Esse PR:
- Implementa a exibição de todas as prestações de conta do período e DRE a partir do painel de acompanhamento de prestações de contas, independente do seu status.
História: [AB#40217](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/40217)
> feat(40217): [DRE] Acompanhamento das Prestações de Contas:  Ver todas as prestações

- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/escolas/Receitas/ListaDeReceitas/index.js
- src/utils/Modais.js
feat(40428): Exibe msg ao selecionar tipo crédito
Esse PR:
- Verifica se possui mensagem ao usuario no retorno do endpoint,
- Adiciona modal para exibir a mensagem,
- Exibe mensagem ao selecionar tipo de crédito.
História: [AB#40428](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/40428)
> feat(40428) Exibe msg ao selecionar tipo crédito

- src/paginas/Login/LoginForm.js
feat(42234): Adiciona botão para exibir senha
Esse PR:
- Adiciona botão para exibir senha.
História: [AB#42234](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42234)
> feat(42234) Adiciona botão para exibir senha

- src/componentes/escolas/Despesas/FormFiltrosAvancados/index.js
- src/services/escolas/RateiosDespesas.service.js
feat(23153): Adiciona filtro por tipo conta
Esse PR:
- Adiciona campo de filtro por tipo de conta a interface Gastos da escola,
- Adiciona o filtro ao request da API.
História: [AB#23153](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/23153)
> feat(23153) Adiciona filtro por tipo conta

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/ModalErroDeletarCadastroDespesa.js
Esse PR:
- Implementa mensagem clara ao usuário que tenta deletar uma despesa que tem relacionamentos
História: [AB#39149](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39149)
> feat(39149): [Associação]  Mensagem ao não conseguir apagar despesas por estar relacionada a outras entidades

- src/componentes/escolas/Receitas/Formularios/index.js
feat(42235): Verifica se deve exibir detalhamento de crédito
Esse PR:
- Verifica se deve exibir o detalhamento de crédito,
- Altera o campo para obrigatório, caso deva ser exibido.
História: [AB#42235](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42235)
> feat(42235) Verifica se deve exibir detalhamento de crédito

- src/componentes/escolas/Receitas/Formularios/index.js
feat(42235) parte 2: Altera mensagem
Esse PR:
- Altera mensagem de erro do campo detalhamento de crédito.
História: [AB#42235](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42235)
> feat(42235) parte 2 Altera mensagem

- src/componentes/escolas/Receitas/ModalSelecionaRepasse.js
fix(43756): Altera tamanho modal
Esse PR:
- Adiciona tamanho "lg" ao modal
História: [AB#43756](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43756)
> fix(43756) Altera tamanho modal

- src/paginas/escolas/DadosDasContasAssociacao/index.js
fix(43861) Altera texto do item Dados das contas.
Esse PR:
- Altera texto do item Dados das contas
História: [AB#43861](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43861)
> fix(43861) Altera texto do item Dados das contas

- src/componentes/Globais/GestaoDePerfis/GestaoDePerfisForm.js
- src/componentes/Globais/GestaoDePerfis/GestaoDePerfisFormFormik.js
Esse PR:
- Realiza tratament, exibição e bloqueio de seleção para grupos de acordo com a visão selecionada
História: [AB#42237](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42237)
> feat(42237): Perfil de Acessos: Exibir grupos de acessos das visões subordinadas

- src/utils/ValidacoesAdicionaisFormularios.js
fix(42728) Altera visualização da data
Esse PR:
- Altera visualização da data recebida pela API
História: [AB#42728](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42728)
> fix(42728) Altera visualização da data

- src/componentes/Globais/GestaoDePerfis/GestaoDePerfisForm.js
- src/componentes/Globais/GestaoDePerfis/GestaoDePerfisFormFormik.js
Esse PR:
- Altera o regras e o campo grupos de select option para checkbox
História: AB# 42237
> feat(42237): Perfil de Acessos: Exibir grupos de acessos das visões subordinadas - Parte 4

- src/componentes/dres/RelatorioConsolidado/ExecucaoFinanceira/index.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoApuracao/TopoComBotoes.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoApuracao/index.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/componentes/dres/RelatorioConsolidado/relatorio-consolidado.scss
Esse PR faz alterações na interface de geração do relatório consolidado DRE para considerar a sua geração assíncrona.
O que foi feito:
[X] Mensagem: "O relatório está sendo gerado..." ao gerar;
[X] Atualização da linha de status do relatório com loading;
[X] Alteração do label do botão quando "processando";
[X] Na página principal tratar habilitação dos botões conforme status;
[X] Implementa timer para consulta do status;
[X] Na página de apuração desabilitar geração quando "processando";
[X] Na página de apuração alterar o label quando "processando".
História: [AB#31426](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/31426)
> feat(31426): Relatório consolidado DRE - Assíncrono

- package.json
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/data-saldo-bancario.scss
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/FiltrosTransacoes/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/Justivicativa/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TopoComBotoes/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/componentes/escolas/PrestacaoDeContas/prestacao-de-contas.scss
- src/services/escolas/PrestacaoDeContas.service.js
feat(43735) Altera comportamento botão salvar
Esse PR:
- Altera component de upload de arquivos,
- Divide salvamento de uma conciliação em dois blocos (extrato bancário e justificativas),
- Altera layout baseando-se no protótipo.
História: [AB#43735](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43735)
> feat(43735) Altera comportamento botão salvar

- src/componentes/Globais/Dashborard/DashboardCard.js
- src/paginas/Login/LoginForm.js
feat(43597) Ajusta textos
Esse PR:
- Realiza ajustes de textos.
História: [AB#43597](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43597)
> feat(43597) Ajusta textos

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/services/escolas/PrestacaoDeContas.service.js
feat(43735) parte 2 aprimora cadastro de conciliacao por bloco
Esse PR:
- Permite o envio de uma justificativa vazia
História: [AB#43735](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43735)
> feat(43735) parte 2 aprimora cadastro de conciliacao por bloco

- src/componentes/dres/RelatorioConsolidado/ModalSalvarJustificativa.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoApuracao/JustificativaDiferenca.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoApuracao/index.js
feat(34435) Altera comportamento botão salvar.
Esse PR:
- Altera comportamento do botão salvar
- Altera comportamento do botão limpar
- Exibe modal informativo ao salvar informações
História: [AB#34435](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34435)
> feat(34435) Altera comportamento botão salvar

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/data-saldo-bancario.scss
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
feat(43735)-parte-3 ajuste de textos
Esse PR:
- Ajusta textos
- Adiciona classe para bloquear botão upload
História: [AB#43735](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43735)
> feat(43735)-parte-3 ajuste de textos

- src/paginas/Login/LoginForm.js
- src/paginas/Login/login.scss
Ajuste input de senha
Esse PR:
- Ajusta icone de mostrar/ocultar senha
> Ajuste input de senha

- src/componentes/Globais/SidebarLeft/getUrls.js
- src/componentes/sme/PainelParametrizacoes/ParametrizacaoCard.js
- src/componentes/sme/PainelParametrizacoes/index.js
- src/componentes/sme/Parametrizacoees/Despesas/Fornecedores/index.js
Esse PR:
- Adiciona verificação de permissão para acesso e alteração no Cadastro de Fornecedores em DRE e SME
História: [AB#43751](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43751)
> feat(43751): Cadastro de fornecedores

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
feat(43985)-parte-2 ajusta campo de razao social
Esse PR:
- Ajusta campo razão social
História: [AB#43985](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43985)
> feat(43985)-parte-2 ajusta campo de razao social

- src/componentes/Globais/SidebarLeft/index.js
- src/componentes/sme/PainelParametrizacoes/ParametrizacaoCard.js
- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR:
- Corrige problema de exibição do menu ao clicar em botões de voltar
História: [AB#39281](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39281)
> fix(39281): Problema no menu após clicar no botão voltar

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaValoresPendentesPorAcao/index.js
feat(41991) Exibe saldo reprogramado anterior
Esse PR:
- Exibe o saldo reprogramado anterior na coluna "Conciliado"
História: [AB#41991](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/41991)
> feat(41991) Exibe saldo reprogramado anterior

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ArquivosDeReferenciaVisualizacaoDownload.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ModalVisualizarArquivoDeReferencia.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/services/dres/PrestacaoDeContas.service.js
Esse PR:
- Implementa visualização e download de arquivos de referência por conta
História: [AB#43799](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43799)
> feat(43799): Acompanhamento PC: Em análise: Parte 2 - Arquivos de referência: Visualização e Download

- src/componentes/Globais/Cabecalho/index.js
- src/componentes/Globais/CentralDeDownloads/FormFiltrosDownloads.js
- src/componentes/Globais/CentralDeDownloads/TabelaDownloads.js
- src/componentes/Globais/CentralDeDownloads/central-de-downloads.scss
- src/componentes/Globais/CentralDeDownloads/index.js
- src/context/CentralDeDownloads/index.js
- src/index.js
- src/paginas/CentralDeDownloads/index.js
- src/rotas/index.js
- src/services/CentralDeDownload.service.js
feat(43961) Adiciona central de downloads
Esse PR:
- Adiciona componentes que compoem a pagina de central de downloads
- Adiciona services para consumo da API de central de downloads
- Adiciona icone para acessar a central de downloads
Historia: [AB#43961](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43961)
> feat(43961) Adiciona central de downloads

- src/componentes/escolas/Associacao/DadosDaAssociacao/index.js
Esse PR:
- Altera Dados da Associação label dos campos Email e código EOL
História: [AB#46248](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46248)
> feat(46248): Dados da Associação e Ficha Cadastral: E-mail da Associação passa a chamar e-mail da UE

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/cadastro-de-despesas.scss
Esse PR:
- Altera posição btn remover rateio
- Ajusta posicionamento dos elementos
- Cria folha de estilo e estiliza botão remover despesa
História: [AB#46300](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46300)
> feat(46300): Gastos da Escola: Alterar posição e estilo do botão "Remover Despesa" que exclui um rateio

- src/componentes/Globais/CentralDeDownloads/index.js
- src/componentes/Globais/SidebarLeft/index.js
- src/componentes/sme/ConsultaDeSaldosBancarios/BtnExportar.js
- src/componentes/sme/ConsultaDeSaldosBancarios/ConsultaDeSaldosBancariosDetalhesAssociacoes.js
- src/componentes/sme/ConsultaDeSaldosBancarios/Filtros.js
- src/services/sme/ConsultaDeSaldosBancarios.service.js
- src/utils/Modais.js
feat(37007) Exporta informações de extrato
Esse PR:
- Adiciona chamada do endpoint para realizar exportação assincrona
- Adiciona botão para exportar planilha
- Adiciona modal de confirmação de exportação
- Aprimora componentes relacionados a central de downloads
História: [AB#37007](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/37007)
> feat(37007) Exporta informações de extrato

- src/componentes/escolas/Receitas/ListaDeReceitas/index.js
Esse PR: 
- Cria indicativo visual de créditos sem gastos vinculados em recursos externos
História: [AB#46301](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46301)
> feat(46301): Créditos de recursos externos: indicativo visual de créditos sem gastos vinculados  

- src/componentes/escolas/Associacao/Membros/index.js
- src/componentes/escolas/Associacao/ModalMembros.js
Esse PR:
- Altera validação campo EOL estudante
História: [AB#46267](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46267)
> feat(46267):  Dados da Associação: Membros: Melhorar validação código EOL aluno

- src/componentes/sme/PainelParametrizacoes/ParametrizacaoCard.js
Esse PR: 
- Altera layout Cards Parametrizações
História: [AB#46278](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46278)
> fix(46278): Cards de parametrização apresentam falha visual ao redimensionar a página

- src/componentes/dres/RelatorioConsolidado/ExecucaoFinanceira/index.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/services/dres/RelatorioConsolidado.service.js
feat(31428) Gera previa relatorio assincronamente
Esse PR:
- Altera chamadas ao endpoint de gerar prévia documento
- Adiciona loading enquanto previa é gerada
- Adiciona confirmação ao usuario que previa esta sendo gerada
- Adiciona botão de download previa
História: [AB#31428](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/31428)
> feat(31428) Gera previa relatoriio assincronamente

- src/componentes/sme/Parametrizacoees/Estrutura/Associacoes/ModalFormAssociacoes.js
- src/componentes/sme/Parametrizacoees/Estrutura/Associacoes/index.js
- src/services/sme/Parametrizacoes.service.js
Esse PR: 
- Faz verificação de dados cadastrados para a associação, para exibir mensagem de acordo
História: [AB#34051](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34051)
> feat(34051): Faz verificação de dados cadastrados para a associação

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabsConferenciaDeLancamentos.js
Esse PR:
- Altera método que seleciona os lancamentos, fazendo verificação se existe algum com status de ajuste
História: [AB#43844](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43844)
> feat(43844): Acompanhamento PC: Em análise: Parte 4 - Conferência de lançamentos: Solicitação de ajustes - Parte 2

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabsConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
Esse PR:
- Inclui Loading e Ancora
- Refatora métodos Conferencia de Lancamentos
> feat(43844): Acompanhamento PC: Em análise: Parte 4 - Conferência de lançamentos: Solicitação de ajustes - Parte 3

- src/componentes/Globais/DatePickerField/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ArquivosDeReferencia/TabsArquivosDeReferencia.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabsConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/ModalErroDevolverParaAcerto.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/devolucao-para-acertos.scss
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
- src/componentes/dres/PrestacaoDeContas/ModalConcluirAnalise.js
- src/componentes/sme/Parametrizacoees/Estrutura/Acoes/index.js
Esse PR: 
- Separa devolução para acerto da conclusão da análise
História: [AB#43893](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43893)
> feat(43893): Acompanhamento PC: Em análise: Parte 7 - Separar devolução para acerto da conclusão da análise

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/cadastro-de-despesas.scss
Esse PR:
- Remove especificações de material ou serviço que não estejam ativas
História: AB#47936
> feat(47936): Permitir desativar uma especificação de material ou serviço

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/ModalCheckNaoPermitidoConfererenciaDeDocumentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/services/dres/PrestacaoDeContas.service.js
Esse PR:
- Implementa conferência de documentos
História: [AB#43889](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43889)
> feat(43889): Implementa conferência de documentos

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/BotaoSalvarRodape.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/ModalCheckNaoPermitidoConfererenciaDeDocumentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/services/dres/PrestacaoDeContas.service.js
História: [AB#48903](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/48903)
> homolog(48903): Posição em Develop 15/09/2021 às 08:11

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/CabecalhoDocumento.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/FormularioAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/TopoComBotoes.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/YupSignupSchemaDetalharAcertosDocumentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
- src/hooks/dres/PrestacaoDeContas/useCarregaPrestacaoDeContasPorUuid.js
- src/rotas/index.js
- src/services/dres/PrestacaoDeContas.service.js
- src/store/reducers/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/actions.js
- src/store/reducers/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/reducer.js
- src/store/reducers/index.js
Esse PR: 
-  Implementa Solicitação de Ajustes em Conferência de  Documentos
História: [AB#43891](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43891)
> feat(43891): Acompanhamento PC: Em análise: Parte 6 - Conferência de documentos: Solicitação de ajustes.

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/FiltrosAcertosDeLancamentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosDocumentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosLancamentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabsAcertosEmLancamentosPorConta.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabsConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/DevolverParaAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TabsConferenciaAtualHistorico.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TopoComBotoes.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/rotas/index.js
- src/services/dres/PrestacaoDeContas.service.js
Esse PR:
- Implementa Ver resumo de acertos -  Conferência atual
História: [AB#43914](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43914)
> feat(43914): Acompanhamento PC: Em análise: Parte 8a - Ver resumo de acertos: Conferência atual 

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TopoComBotoes.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
Esse PR: 
- Implementa trava em botão Devolver para acertos
- Bloqueia o envio de diversas requisições para devolver acertos
- Altera condição de bloqueio de botão ver resumo
História: [AB#43993](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43993)
> feat(43993): Acompanhamento PC: Em análise: Parte 8b - Ver resumo de acertos: Histórico - Parte 02

- src/componentes/Globais/FormFiltroPorPalavra/index.js
- src/componentes/escolas/Despesas/FormFiltrosAvancados/index.js
- src/componentes/escolas/Despesas/ListaDeDespesas/Paginacao.js
- src/componentes/escolas/Despesas/ListaDeDespesas/index.jsx
- src/componentes/escolas/Despesas/ListaDeDespesas/lista-de-despesas.scss
- src/services/escolas/Despesas.service.js
feat(46303) Agrupa rateios
Esse PR:
- Adiciona tabela para exibir rateios agrupados por despesa
- Adiciona paginação a tabela
- Refatora filtro por palavra (necessario para a paginação da tabela funcionar corretamente)
- Refatora filtros avançados (necessário para a paginação da tabela funcionar corretamente)
- Adiciona chamada aos novos endpoints de despesa
História: [AB#46303](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46303)
> feat(46303) Agrupa rateios

- src/componentes/Globais/CardsDevolucoesParaAcertoDaDre/index.js
- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/TextoSuperior.js
- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/TopoComBotaoVoltar.js
- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/consulta-detalhamento-analise-da-dre.scss
- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/index.js
- src/componentes/escolas/AnaliseDre/index.js
- src/rotas/index.js
Esse PR:
- Implementa Consulta de análises da DRE: Detalhamento da análise
História: [AB#44206](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/44206)
> feat(44206): Consulta de análises da DRE: Detalhamento da análise

- src/componentes/Globais/GestaoDePerfis/index.js
Esse PR: 
- Inclui loading ao carregar lista de usuários
História: [AB#50044](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50044)
> fix(50044): Aplicação não está exibindo o loading no carregamento da lista de usuários

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
feat(48640) Altera validação de periodo fechado
Esse PR:
- Altera validação de periodo fechado para o campo data transacao
História: [AB#48640](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/48640)
> feat(48640) Altera validação de periodo fechado

- src/utils/ValidacoesAdicionaisFormularios.js
fix(46265) Adiciona validacao
Esse PR:
- Adiciona validacao por tipo nulo, no campo tipo transacao
História: [AB#46265](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46265)
> fix(46265) Adiciona validacao

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/ModalConfirmaDevolverParaAcerto.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TopoComBotoes.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
Esse PR:
- Implementa mensagem ao Devolver para acertos
História: [AB#45592](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/45592)
> feat(45592): Novo processo de devolução para acertos de PC: Parte 1 - Mensagem explicativa ao devolver

- src/componentes/escolas/Despesas/FormFiltrosAvancados/index.js
- src/componentes/escolas/Despesas/ListaDeDespesas/index.jsx
- src/services/escolas/Despesas.service.js
- src/services/escolas/RateiosDespesas.service.js
feat(46304): Adiciona filtro por tag
Esse PR:
- Adiciona o campo vinculo a atividade nos filtros avançados
- Adiciona o novo campo na chamada da API
História: [AB#46304](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46304)
> feat(46304): Adiciona filtro por tag

- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/FormFiltros.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/index.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/multiselect.scss
Esse PR:
- Realiza Pesquisa sobre qual componente será usado - Ant
- Implementa um teste com Ant multiselect
História: [AB#50224](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50224)
> fix(50224):  Acompanhamento PC: o filtro por status não está funcionando - Parte 1

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/TrilhaDeStatus/index.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/index.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
Esse PR:
- Implementa leitura novo status Retornada após acertos
História: [AB#45618](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/45618)
> feat(45618): Novo processo de devolução para acertos de PC: Parte 2 - Prestação de Contas - Novo status "Retornada após acertos"

- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/BarraDeStatus.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/FormFiltros.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/index.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/multiselect.scss
Esse PR:
- Corrige filtro lista de prestações de contas - DRE
História: [AB#50224](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50224)
> fix(50224): Acompanhamento PC: o filtro por status não está funcionando

- src/componentes/dres/Associacoes/DadosDasAssociacoes/RegularidadeUnidadeEducacional/ModalConfirmarApagarMotivoNaoRegularidade.js
- src/componentes/dres/Associacoes/DadosDasAssociacoes/RegularidadeUnidadeEducacional/MotivoNaoRegularidade.js
- src/componentes/dres/Associacoes/DadosDasAssociacoes/RegularidadeUnidadeEducacional/index.js
- src/services/dres/RegularidadeUnidadeEducaional.service.js
Esse PR:
- Inclui motivo de não regularidade e suas devidas verificações
História: [AB#33225](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/33225)
> feat(33225): Regularidade das Associações: Inclusão do motivo de não regularidade da Associação

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/RelatorioDosAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TabsConferenciaAtualHistorico.js
- src/services/dres/PrestacaoDeContas.service.js
feat(44023) - Gera previa relatorio de acertos
Esse PR:
- Adiciona "bloco" para geração do relatório de acertos a interface
- Adiciona chamada a API de geração de previa
- Adiciona chamada a API de consulta de status
- Adiciona chamada a API de download do documento
História: [AB#44023](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/44023)
> feat(44023) - Gera previa relatorio de acertos

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/RelatorioDosAcertos.js
feat(44023)-parte-2 Conserta inversao de contas
Esse PR:
- Conserta inversão de contas ao gerar pdf
História: [AB#44023](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/44023)
> feat(44023)-parte-2 Conserta inversao de contas

- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/index.js
Esse PR:
- Corrige plural Devolvida para acertos
História: [AB#45618](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/45618)
> feat(45618):  Novo processo de devolução para acertos de PC: Parte 2 - Prestação de Contas - Novo status  Retornada após acertos - Ajustes

- src/componentes/escolas/Despesas/ListaDeDespesas/index.jsx
- src/services/escolas/RateiosDespesas.service.js
feat(46304)-parte-2 Adiciona parametro tag uuid
Esse PR:
- Adiciona parametro tag uuid
> feat(46304)-parte-2 Adiciona parametro tag uuid

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TopoComBotoes.js
feat(44181)-parte-3 remove botão imprimir relatorio
Esse PR:
- Remove botão "imprimir relatório"
História: [AB#44181](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/44181)
> feat(44181)-parte-3 remove botão imprimir relatorio

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroSaidaForm.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaTransacoes/index.js
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/useRowExpansionDespesaTemplate.js
- src/utils/ValidacoesAdicionaisFormularios.js
feat(51753) Ajustes de textos
Esse PR:
- Ajusta textos.
História: [AB#51753](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/51753)
> feat(51753) Ajustes de textos

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroSaidaForm.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaTransacoes/index.js
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/useRowExpansionDespesaTemplate.js
feat(51753)-parte-2 Ajustes de texto
Esse PR:
- Realiza ajustes de texto
História: [AB#51753](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/51753)
> feat(51753)-parte-2 Ajustes de texto

- package.json
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
Esse PR:
- Altera, na consulta de solicitações de ajustes, o detalhe de ajustes de
documento para exibir o novo campo detalhamento da solicitação de
ajuste.
História: [AB#52319](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52319)
> feat(52319): Altera detalhe consulta acertos de documento

- src/App.js
- src/componentes/escolas/GeracaoDaAta/ModalReverDevolucoesAoTesouro.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/FormularioEditaAta/YupSignupSchemaEditarAta.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/FormularioEditaAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/TopoComBotoes/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TabelaPresentes/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TextoDinamicoInferior/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
- src/componentes/escolas/GeracaoDaAta/geracao-da-ata.scss
- src/rotas/index.js
- src/services/escolas/PresentesAta.service.js
- src/utils/ValidacoesAdicionaisFormularios.js
feat(52122) Distinguir a ata do parecer do conselho fiscal
Esse PR:
- Adiciona pagina para edição da Ata
- Adiciona uma lista de presentes ao formulario da ata
- Adiciona tabela com presentes ao corpo da ata
História: [AB#52122](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52122)
> feat(52122) Distinguir a ata do parecer do conselho fiscal

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TabelaPresentes/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
feat(52122)-parte-2 Ajuste tabela de presentes
Esse PR:
- Realiza ajuste no exibição da tabela de presentes, quando vazia
História: [AB#52122](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52122)
> feat(52122)-parte-2 Ajuste tabela de presentes

- src/componentes/Globais/BarraMensagem/barraMensagem.scss
- src/componentes/Globais/BarraMensagem/index.js
- src/componentes/escolas/PrestacaoDeContas/PresidenteAusente.js
- src/componentes/escolas/PrestacaoDeContas/index.js
- src/paginas/PaginasContainer.js
- src/paginas/escolas/PrestacaoDeContas/index.js
- src/services/escolas/PrestacaoDeContas.service.js
feat(51989) Mensagem presidente ausente.
Esse PR:
- Adiciona caixa de mensagem informando presidente ausente
- Adapta componente que gera a caixa de mensagem
História: [AB#51989](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/51989)
> feat(51989) Mensagem presidente ausente

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TabelaDinamica/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TabelaTotais/index.js
Esse PR:
- Remove texto colunas tabela
História: [AB#53174](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53174)
> feat(53174): Ata: melhorias de redação e nas tabelas de dados (página e pdf)

- src/paginas/Login/LoginForm.js
Esse PR:
-Altera o formulário de login para exibir qualquer mensagem de erro de validação do login como é retornada pelo back, inclusive mensagem que ocorre quando o usuário não está ativo.
História [AB#50812](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50812)
> feat(50812): Altera login para exibir mensagem user não ativo

- src/componentes/Globais/CardsDevolucoesParaAcertoDaDre/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TabsConferenciaAtualHistorico.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
- src/componentes/escolas/PrestacaoDeContas/PresidenteAusente.js
feat(53366): esconder aba "Conferencia atual"
Esse PR:
- Exibe aba "Conferencia atual" apenas quando status da PC for em analise
História: [AB#53366](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53366)
> feat(53366) esconder aba "Conferencia atual"

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroSaidaForm.js
- src/utils/ValidacoesAdicionaisFormularios.js
feat(53206) Numero documento aceitar apenas numeros
Esse PR:
- Adiciona função para aceitar apenas numeros
História: [AB#53206](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53206)
> feat(53206) Numero documento aceitar apenas numeros

- src/componentes/Globais/SidebarLeft/index.js
feat(50811) ocultar sub-menus
Esse PR:
- Exibe item do menu apenas se usuário tiver acesso a pelo menos 1 sub-menu
História: [AB#50811](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50811)
> feat(50811) ocultar sub-menus

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/InformacoesDevolucaoAoTesouro.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/FormularioEditaAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
Esse PR:
- Corrige ata de retificação não abre para edição
História: [AB#54078](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/54078)
> fix(54078): A ata de retificação não abre para edição

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/VerificaSaldoReprogramadoInicial.js
feat(50801)-parte-2 ajuste no valor nulo dos inputs
Esse PR:
- Realiza ajuste nos valores nulo dos inputs
História: [AB#50801](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50801)
> feat(50801)-parte-2 ajuste no valor nulo dos inputs

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/FormularioEditaAta/index.js
Esse PR:
- Corrige o useEffect de atas para responder a mudanças na lista de presentes padrão.
História: [AB#54223](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/54223)
> feat(54223): Altera apresentação de presentes nas atas

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosEmValoresReprogramados.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabsAjustesEmValoresReprogramados.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/VerificaSaldoReprogramadoInicial.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/services/dres/PrestacaoDeContas.service.js
feat(50806) Solicitações de ajustes
Esse PR:
- Adiciona bloco para visualizar solicitações de ajustes em valores reprogramados
História: [AB#50806](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50806)
> feat(50806) Solicitações de ajustes

- src/componentes/dres/Diretoria/Comissoes/FormFiltros.js
- src/componentes/dres/Diretoria/Comissoes/ListaComissoes.js
- src/componentes/dres/Diretoria/Comissoes/Modais/index.js
- src/componentes/dres/Diretoria/Comissoes/Modais/multiselect.scss
- src/componentes/dres/Diretoria/Comissoes/TopoComBotoes.js
- src/componentes/dres/Diretoria/Comissoes/comissoes.scss
- src/componentes/dres/Diretoria/Comissoes/index.js
- src/componentes/dres/Diretoria/UrlsMenuInterno.js
- src/paginas/dres/Diretoria/Comissoes/index.js
- src/rotas/index.js
- src/services/dres/Comissoes.service.js
feat(46226) Cadastro de membros de comissoes
Esse PR:
- Adiciona aba "comissões" a dados da diretoria
- Adiciona chamadas a API de CRUD de membros da comissões
- Adiciona components responsáveis pela exibição da nova página
- Adiciona nova rota para acessar a nova aba
- Verifica permissões para acessar a nova aba
História: [AB#46226](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46226)
> feat(46226) Cadastro de membros de comissoes

- src/services/dres/Comissoes.service.js
feat(46226)-parte-2 ajuste filtro
Esse PR:
- Realiza ajuste no filtro
História: [AB#46226](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46226)
> feat(46226)-parte-2 ajuste filtro

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/hooks/Globais/useDataTemplate.js
feat(50154): Ajuste distribuição de colunas
Esse PR:
- Ajusta distribuição das colunas
História: [AB#50154](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50154)
> feat(50154): Ajuste distribuição de colunas

- src/componentes/Globais/SidebarLeft/getUrls.js
- src/componentes/dres/RegularidadeAssociacoes/FiltrosAssociacoes.js
- src/componentes/dres/RegularidadeAssociacoes/TabelaAssociacoes.js
- src/componentes/dres/RegularidadeAssociacoes/associacoes.scss
- src/componentes/dres/RegularidadeAssociacoes/index.js
- src/paginas/dres/RegularidadeAssociacoes/DetalhesDaAssociacao/index.js
- src/paginas/dres/RegularidadeAssociacoes/index.js
- src/rotas/index.js
- src/services/dres/Associacoes.service.js
Esse PR:
- Cria a nova funcionalidade que permite a gestão dos status de regularidade das associações pela DRE.
História: [AB#40136](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/40136)
> feat(40136): Cria DRE Regularidade Associações

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
feat(54213): Exibição de loading
Esse PR:
- Exibe loading em todos as trocas de status de um PC
História: [AB#54213](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/54213)
> feat(54213): Exibição de loading

- README.md
- hotfixes.md
- package.json
- src/componentes/dres/RelatorioConsolidado/ExecucaoFinanceira/index.js
- src/componentes/dres/RelatorioConsolidado/ModalMsgGeracaoRelatorio.js
- src/componentes/dres/RelatorioConsolidado/SelectConta.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/services/dres/RelatorioConsolidado.service.js
[AB#54469](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/54469)
> Posição de Develop em 20/12 10:20

- package.json
- src/componentes/dres/RegularidadeAssociacoes/AnalisesRegularidade/RegularidadeAssociacaoNoAno/index.js
- src/componentes/dres/RegularidadeAssociacoes/AnalisesRegularidade/TabsAnaliseAnoVigenteHistorico.js
- src/componentes/dres/RegularidadeAssociacoes/SelecaoAnoAnaliseRegularidade.js
Esse PR:
- Cria o detalhamento histórico de análises de regularidade da associação por ano.
História: [AB#40179](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/40179)
> feat(40179): Cria detalhe regularidade associação histórico

- src/componentes/dres/RegularidadeAssociacoes/AnalisesRegularidade/RegularidadeAssociacaoNoAno/index.js
- src/componentes/dres/RegularidadeAssociacoes/AnalisesRegularidade/TabsAnaliseAnoVigenteHistorico.js
- src/componentes/dres/RegularidadeAssociacoes/SelecaoAnoAnaliseRegularidade.js
Esse PR:
- Corrige situação que causava a não atualização dos status de regularidade logo ao entrar na aba de histórico de análises
de regularidade.
História: [AB#40179](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/40179)
> feat(40179): Resolve problema histórico regularidade

- src/componentes/escolas/ValoresReprogramados/index.js
feat(52005)-parte-2: ajuste
Esse PR:
- Realiza ajuste no uuid da acao
História: [AB#52005](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52005)
> feat(52005)-parte-2: ajuste

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
feat(50154): ajuste de colunas
Esse PR:
- Ajusta tamanho das colunas com porcentagem
História: [AB#50154](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50154)
> feat(50154): ajuste de colunas

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
feat(50154)-parte-3: Remoção de comentários
Esse PR:
- Remove comentários
História: [AB#50154](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50154)
> feat(50154)-parte-3: Remoção de comentários

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaTransacoes/index.js
- src/componentes/escolas/PrestacaoDeContas/prestacao-de-contas.scss
feat(46229): Exibir tags no detalhamento de gastos
Esse PR:
- Adiciona tag a visualização dos rateios da despesa
- Altera layout de acordo com protótipo
História: [AB#46229](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46229)
> feat(46229): Exibir tags no detalhamento de gastos

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/FiltrosTransacoes/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaTransacoes/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaValoresPendentesPorAcao/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/services/escolas/PrestacaoDeContas.service.js
feat(52339): Retirar creditos da conciliacao bancaria
Esse PR:
- Realiza chamada aos novos endpoints
- Altera textos de titulo dos blocos
- Lista apenas lançamentos de gastos
- Remove filtro por tipo de lançamento
- Altera linha de crédito do Quadro resumo
História: [AB#52339](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52339)
> feat(52339): Retirar creditos da conciliacao bancaria

- src/componentes/escolas/Receitas/Formularios/index.js
feat(52339)-parte-2: Retirar creditos da conciliacao
Esse PR:
- Remove mensagem de crédito ja demonstrando, ao editar um crédito
História: [AB#52339](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52339)
> feat(52339)-parte-2: Retirar creditos da conciliacao

- src/componentes/Globais/SidebarLeft/getUrls.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
- src/componentes/escolas/PrestacaoDeContas/ModalConcluirPeriodo.js
- src/componentes/escolas/PrestacaoDeContas/PresidenteAusente.js
- src/componentes/escolas/PrestacaoDeContas/index.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/escolas/Receitas/ModalDeletarReceita.js
feat(49904): Alteração de texto
Esse PR:
- Altera textos requisitados
História: [AB#49904](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/49904)
> feat(49904): Alteração de texto

- src/services/dres/RelatorioConsolidado.service.js
fix(54919): Relatório consolidado
Esse PR:
- Altera nome dos parametros na chamada da API de justificativas
História: [AB#54919](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/54919)
> fix(54919): Relatório consolidado

- src/componentes/escolas/PrestacaoDeContas/PresidenteAusente.js
feat(49904)-parte-2: Ajuste de texto
Esse PR:
- Adiciona função para formatar nome do cargo quando tiver "diretoria executiva" incluido
História: [AB#49904](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/49904)
> feat(49904)-parte-2: Ajuste de texto

- src/componentes/dres/Dashboard/DashboardCard.js
- src/componentes/escolas/GeracaoAtaRetificadora/index.js
Esse PR: 
-  Exibe tooltip com informação de pcs não recebidas
História: [AB#55954](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55954)
> feat(55954): Acompanhamento PC: Dashboard: Card Não Recebidas chamar atenção para a existência de PCs apresentadas

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ComentariosDeAnalise.js
feat(56033): Notificação de comentários
Esse PR:
- Altera mensagem de envio da notificação
História: [AB#56033](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/56033)
> feat(56033): Notificação de comentários

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabsConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/services/auth.service.js
- src/services/mantemEstadoAcompanhamentoDePc.service.js
- src/services/visoes.service.js
Esse PR:
- Persiste estado Acompanhamento de PC por usuário e prestação de contas
História: [AB#50162](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50162)
> feat(50162): Análise de PC: Manter estado de seleção, filtros e  posição na análise de lançamentos após solicitar ajustes

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ComentariosDeAnalise.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabsConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/services/auth.service.js
- src/services/mantemEstadoAcompanhamentoDePc.service.js
- src/services/visoes.service.js
[AB#56175](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/56175)
> Posição de Develop em 17/01/22 10:25 

- src/componentes/escolas/GeracaoAtaRetificadora/BoxAtaRetificadora/index.js
- src/componentes/escolas/GeracaoAtaRetificadora/index.js
- src/componentes/escolas/GeracaoDaAta/GeracaoAtaApresentacao/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TextoDinamicoSuperior/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TopoComBotoes/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
- src/componentes/escolas/PrestacaoDeContas/index.js
- src/services/dres/PrestacaoDeContas.service.js
- src/services/escolas/Associacao.service.js
- src/services/escolas/AtasAssociacao.service.js
- src/services/escolas/PrestacaoDeContas.service.js
Esse PR:
- Faz as alterações necessárias para o tratamento de prévias de atas de apresentação e retificação.
História: [AB#52133](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52133)
> feat(52133): Cria previas de atas de apresentação e retificação

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TopoComBotoes/index.js
[AB#56175](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/56175)
> Posição de Develop em 20/01 11:06

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TextoDinamicoInferior/index.js
Esse PR:
- Altera o texto final da ata em tela para textos diferentes nos casos da ata ter ou não comentários.
História: [AB#55187](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55187)
> feat(55187): Altera texto final ata em tela conforme comentários

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/FormularioEditaAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TextoDinamicoInferior/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TextoDinamicoSuperior/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
[AB#56175](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/56175)
> Posição de Develop em 21/01/22 06:49

- src/App.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/Assinaturas/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/FormularioEditarAta/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/TopoComBotoes/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TabelaAprovadas/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TextoDinamicoSuperior/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TopoComBotoes/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/ata-parecer-tecnico.scss
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/index.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/rotas/index.js
- src/services/dres/AtasParecerTecnico.service.js
- src/services/dres/RelatorioConsolidado.service.js
feat(46251): Ata de parecer tecnico
Esse PR:
- Cria pagina para visualizar e ditar ata de parecer tecnico
- Realiza chamadas aos novos endpoints da API
> feat(46251): Ata de parecer tecnico

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/FormularioEditarAta/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/index.js
- src/componentes/dres/RelatorioConsolidado/index.js
feat(46251)-parte-2: Ata parecer tecnico
Esse PR:
- Impede a exibição do box da ata sem um relatorio consolidado gerado
> feat(46251)-parte-2: Ata parecer tecnico

- src/componentes/dres/RelatorioConsolidado/SelectConta.js
- src/componentes/dres/RelatorioConsolidado/index.js
feat(55535) Gerar lauda
Esse PR:
- Bloqueia o botão de gerar lauda caso não exista uma ata
História: [AB#55535](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55535)
> feat(55535) Gerar lauda

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/FormularioEditarAta/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TabelaAprovadas/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TextoDinamicoSuperior/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
feat(46251)-parte-3: Numero e data portaria
Esse PR:
- Adiciona campos de numero e data da portaria
> feat(46251)-parte-3: Numero e data portaria

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TextoDinamicoSuperior/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
feat(46251)-parte-4: Ajuste nome dre:
Esse PR:
- Retira "DIRETORIA REGIONAL DE EDUCACAO" do nome da dre para exibição no corpo da ata
> feat(46251)-parte-4: Ajuste nome dre

- src/componentes/Globais/ToastCustom/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/FormularioEditarAta/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TopoComBotoes/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/ata-parecer-tecnico.scss
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/index.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoApuracao/index.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/services/dres/AtasParecerTecnico.service.js
feat(50065): Ata parecer tecnico PDF
Esse PR:
- Adiciona funcionalidade de gerar ata
- Adiciona funcionalidade de baixar ata
História: [AB#50065](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50065)
> feat(50065): Ata parecer tecnico PDF

- src/componentes/Globais/ToastCustom/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/EdicaoAta/FormularioEditarAta/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TextoDinamicoSuperior/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TopoComBotoes/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/ata-parecer-tecnico.scss
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/index.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoApuracao/index.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/services/dres/AtasParecerTecnico.service.js
[AB#56175](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/56175)
> Posição de Develop em 31/1/22 10:24

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TabelaAprovadas/index.js
- src/componentes/dres/RelatorioConsolidado/index.js
feat(46251): Ajustes tamanho tabela
Esse PR:
- Realiza ajustes no tamanho da tabela
> feat(46251): Ajustes tamanho tabela

- src/componentes/Globais/CardsDevolucoesParaAcertoDaDre/CardsInfoDevolucaoSelecionada.js
- src/componentes/escolas/PrestacaoDeContas/index.js
Esse PR
- Inclui novo Card de Data de devolução da UE condicionalmente
História: [AB#55937](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55937)
> feat(55937):  Resumo de acertos: Novo card exibindo data do retorno após ajustes pela Associação 

- src/componentes/Globais/ModalBootstrap/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/FormRecebimentoPelaDiretoria.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContasNaoApresentada/index.js
- src/componentes/dres/PrestacaoDeContas/ModalConcluirAnalise.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
feat(57189): Adiciona o recomendacoes
Esse PR:
- Altera layout do modal de conclusão de PC com ressalvas
- Adiciona campo recomendacoes ao formulario
História: [AB#57189](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57189)
> feat(57189): Adiciona o recomendacoes

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
- src/componentes/dres/PrestacaoDeContas/ModalConcluirAnalise.js
feat(57189)-parte-2: Alteração layout conclusao PC
Esse PR:
- Altera layout do modal ao concluir PC como reprovada
História: [AB#57189](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57189)
> feat(57189)-parte-2: Alteração layout conclusao PC

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
fix(57992)-parte-3: Mensagem de erro ao não poder devolver PC
Esse PR:
- Adiciona condição para verificar se pode devolver a PC
- Ajuste no loading
História: [AB#57992](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57992)
> fix(57992)-parte-3: Mensagem de erro ao não poder devolver PC

- src/componentes/Globais/SidebarLeft/getUrls.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/FormularioEditaAta/YupSignupSchemaAta.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/FormularioEditaAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/EdicaoAta/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TabelaRepassesPendentes/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
- src/hooks/Globais/useCarregaRepassesPendentesPorPeriodoAteAgora.js
- src/services/escolas/AtasAssociacao.service.js
Esse PR:
- Inclui justificativa e tabela de repasses pendentes em ata
História: [AB#57423](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57423)
> feat(57423): Ata: inclusão de nova tabela e justificativa (Repasses pendentes de crédito)

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
fix(57755) Corrige ver resumo
Esse PR:
- Corrige condição para liberar o botão "ver resumo"
História: [AB#57755](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57755)
> fix(57755) Corrige ver resumo

- src/componentes/sme/Parametrizacoees/Estrutura/Periodos/ModalFormPeriodos.js
- src/componentes/sme/Parametrizacoees/Estrutura/Periodos/YupSignupSchemaPeriodos.js
- src/componentes/sme/Parametrizacoees/Estrutura/Periodos/index.js
fix(57486): Periodo data de termino do periodo
Esse PR:
- Remove obrigatoriedade do campo Fim realização de despesas
História: [AB#57486](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57486)
> fix(57486): Periodo data de termino do periodo

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ArquivosDeReferencia/TabsArquivosDeReferencia.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoFinanceiroTabelaAcoes.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/VerificaSaldoReprogramadoInicial.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
- src/componentes/dres/PrestacaoDeContas/ModalConcluirAnalise.js
fix(57755)-parte-2: Ajuste
Esse PR:
- Realiza ajuste na habilitação do botão
História: [AB#57755](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57755)
> fix(57755)-parte-2: Ajuste

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/index.js
feat(58586): Alterar status "Retornada após acertos"
Esse PR:
- Altera status para "Apresentada após acertos"
História: [AB#58586](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58586)
> feat(58586): Alterar status "Retornada após acertos"

- src/componentes/Globais/ToastCustom/index.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/escolas/Receitas/ListaDeReceitas/index.js
- src/componentes/escolas/Receitas/ReferenciaDaDespesaEstorno/index.js
- src/paginas/escolas/Receitas/CadastroReceita/index.js
- src/paginas/escolas/Receitas/EdicaoReceita/index.js
- src/services/escolas/RateiosDespesas.service.js
Esse PR: 
- Refatora módulo de Receita, separando form
- Refatora ToastCustom para receber função de Callback
- Cria Estorno de Gastos da Escola
História: [AB#58666](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58666)
> feat(58666): Créditos da Escola: Estornos de gastos de escola

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/ModalDeletarRateioComEstorno.js
- src/componentes/escolas/Despesas/ListaDeDespesas/index.jsx
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/utils/Modais.js
feat(58660): Lançamento do estorno a partir do gasto
Esse PR:
- Altera estilização do link "Estornar despesa"
- Adiciona tooltip de estorno a listagem de despesas
- Adiciona mensagem de confirmação para excluir rateio ou despesa que possui estornos
História: [AB#58660](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58660)
> feat(58660): Lançamento do estorno a partir do gasto

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/TabelaDetalharAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/useRowExpansionDespesaTemplate.js
Esse PR:
- Adiciona informação de estorno em Acompanhamento de PC
História: [AB#58775](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58775)
> feat(58775) Acompanhamento de PC: Conferência de Lançamentos: Exibir informação de estorno

- src/componentes/escolas/Receitas/ReferenciaDaDespesaEstorno/index.js
Esse PR: 
- Altera componente ReferenciaDaDespesaEstorno para refletir mudanças da API
História: [AB#58775](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58775)
> feat(58775): Acompanhamento de PC: Conferência de Lançamentos: Exibir informação de estorno - Parte 02

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/escolas/Receitas/ReferenciaDaDespesaEstorno/index.js
História: [AB#59207](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59207)
> homolog(59207): Posição em Develop 03/03/2022 às 10:19h

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/cadastro-de-despesas.scss
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- src/context/Despesa/index.js
- src/paginas/escolas/Despesas/EdicaoDeDespesa/index.js
- src/utils/Modais.js
- src/utils/ValidacoesAdicionaisFormularios.js
feat(59496) Adiciona formulario de imposto.
Esse PR:
- teste para o novo formulario de imposto
História: [AB#59496](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59496)
> feat(59496) Adiciona formulario de imposto

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/ListaDeDespesas/index.jsx
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- src/paginas/escolas/Despesas/EdicaoDeDespesa/index.js
- src/utils/Modais.js
- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR:
- Adiciona imposto retido na fonte a despesa
História: [AB#59496](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59496)
> feat(59496): Gastos da Escola: Lançamento de imposto retido na fonte

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
Esse PR: 
- Corrige exibição de número do documento
História: [AB#59496](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59496)
> feat(59496): Gastos da Escola: Lançamento de imposto retido na fonte - Parte 03

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/ExibeMotivosPagamentoAntecipadoNoForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/ModalMotivosPagamentoAntecipado.js
- src/paginas/escolas/Despesas/EdicaoDeDespesa/index.js
- src/services/escolas/Despesas.service.js
- src/utils/ValidacoesAdicionaisFormularios.js
Esse PR:
- Implementa confirmação e justificativa de motivos de pagamento antecipado em despesas
> feat(58539): Gastos da Escola: Confirmação e justificativa de pagamento antecipado

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/ListaDeDespesas/index.jsx
- src/componentes/escolas/Despesas/metodosAuxiliares.js
feat(59496)-ajustes-valores:
Esse PR:
- Altera regra dos calculos para consistencia da despesa
> feat(59496)-ajustes-valores:

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TabelaDespesasComPagamentoAntecipado/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
- src/services/escolas/AtasAssociacao.service.js
Esse PR:
- Exibe tabela com despesas com pagamento antecipado em Ata de Apresentação e Retificação
> feat(58564): Atas de apresentação e retificação: Tabela Despesas com pagamento antecipado

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCapital.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormCusteio.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/cadastro-de-despesas.scss
- src/componentes/escolas/Despesas/ListaDeDespesas/lista-de-despesas.scss
- src/componentes/escolas/Despesas/Tags/index.js
feat(61023): aprimorar a relação entre a despesa e o crédito gerado
Esse PR:
- Impede a edição de rateios estornados
> feat(61023): aprimorar a relação entre a despesa e o crédito gerado

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/escolas/Receitas/ModalMotivosEstorno.js
- src/services/escolas/Receitas.service.js
Esse PR:
- Inclui modal, form, validações de motivos de estorno
- Altera Payload e envia para a API
> feat(60061): Incluir motivos do estorno

- src/componentes/escolas/Receitas/Formularios/index.js
Esse PR:
-  Ajusta validação quando data é vazio
História: [AB#60061](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60061)
> feat(60061): Incluir motivos do estorno - Parte 02

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/escolas/Receitas/ModalMotivosEstorno.js
História: [AB#60977](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60977)
> homolog(60977): Posição em Develop 28/03/2022 às 13:27h

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
Esse PR:
- Corrige cálculo de validação em cadastro de despesas
História: [AB#61388](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61388)
> fix(61388): O formulário da despesa não está realizando o cálculo correto para validação dos valores

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Receitas/ModalMotivosEstorno.js
História: [AB#60977](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60977)
> homolog(60977): Posição em Develop 29/03/2022 às 15:20h

- src/componentes/sme/PainelParametrizacoes/index.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/BtnAdd.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/Filtros.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/ModalConfirmDelete.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/ModalForm.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/ModalInfoNaoPodeExcluir.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/ModalInfoUpdateNaoPermitido.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/Tabela.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/YupSignupSchemaMotivosEstorno.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/index.js
- src/rotas/index.js
- src/services/sme/Parametrizacoes.service.js
feat(60953): Parametrizacao motivos
Esse PR:
- Adiciona card de motivos estorno as parametrizacoes
- Adiciona rota do novo card
- Adiciona CRUD de motivos estorno
- Adiciona validacoes do novo CRUD
História: [AB#60953](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60953)
> feat(60953): Parametrizacao motivos

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/sme/PainelParametrizacoes/index.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/BtnAdd.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/Filtros.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/ModalConfirmDelete.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/ModalForm.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/ModalInfoNaoPodeExcluir.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/ModalInfoUpdateNaoPermitido.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/Tabela.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/YupSignupSchemaMotivosEstorno.js
- src/componentes/sme/Parametrizacoees/Receitas/ParametrizacoesMotivosEstorno/index.js
- src/rotas/index.js
- src/services/sme/Parametrizacoes.service.js
História: [AB#60977](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60977)
> homolog(60977): Posição em Develop 31/03/2022 às 11:22h

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
feat(61835): Remove bloco pagamento antecipado
Esse PR:
- Remove bloco pagamento antecipado
História: [AB#61835](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61835)
> feat(61835): Remove bloco pagamento antecipado

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
História: [AB#61902](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61902)
> homolog(61902): Posição em Develop 05/04/2022 às 16:19h 

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/ModalMotivosPagamentoAntecipado.js
- src/utils/Modais.js
Esse PR:
- Cria encadeamento de modais de acordo com a ordem estabelecida
- Refatora módulo de Cadastro de Despesa
História: [AB#60031](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60031)
> fix(60031): Gasto da escola: Modais conflitantes

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/ModalMotivosPagamentoAntecipado.js
- src/utils/Modais.js
História: [AB#61902](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61902)
> homolog(61902): Posição em Develop 12/04/2022 às 10:37h

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
feat(61290)-parte-2: Ajuste min date data pagamento imposto
Esse PR:
- Ajusta min date data pagamento imposto
História: [AB#61290](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61290)
> feat(61290)-parte-2: Ajuste min date data pagamento imposto

- hotfixes.md
- package.json
- src/componentes/escolas/Receitas/Formularios/index.js
Esse PR corrige o bug [AB#62617](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62617)
PR em pre-produção.
> fix(62617): Corrige mensagem de período fechado em estorno

- src/componentes/escolas/Despesas/ListaDeDespesas/Paginacao.js
- src/componentes/escolas/Despesas/ListaDeDespesas/index.jsx
- src/services/escolas/Despesas.service.js
Esse PR:
- Permite a ordenação das despesas por imposto e exibe suas informações
História: [AB#61360](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61360)
> feat(61360): Exibir informações de retenção de imposto nos gastos da escola

- hotfixes.md
- package.json
- src/componentes/escolas/Receitas/Formularios/index.js
Esse PR resolve o bug [AB#62983](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62983)
> fix(62983): Corrige comportamento botão salvar crédito

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabsConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/services/dres/PrestacaoDeContas.service.js
Esse PR: 
- Inclui informações de impostos e ordenação na Análise da PC
História: [AB#61151](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61151)
> feat(61151): Exibir informações de retenção de imposto na análise de PC

- src/componentes/escolas/Associacao/Membros/CadastroDeMembrosDaAssociacao/FormCadastroDeMembrosDaAssociacao.js
- src/componentes/escolas/Associacao/Membros/CadastroDeMembrosDaAssociacao/index.js
- src/services/escolas/Associacao.service.js
feat(60309): Seleção de cargo na educação do servidor
Esse PR:
- Permite seleção de cargo educação do servidor
História: [AB#60309](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60309)
> feat(60309): Seleção de cargo na educação do servidor

- README.md
- package.json
História: [AB#63585](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63585)
> doc(63585): Release notes - release 4

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/FiltrosConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabsConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/services/dres/PrestacaoDeContas.service.js
- src/services/mantemEstadoAcompanhamentoDePc.service.js
Esse PR:
-  Implementa novos filtros em Análise de PC para Conferência de lançamentos
História: [AB#55988](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55988)
> feat(55988): Acompanhamento PC: Novos filtros na conferência de lançamentos

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
Corrige: [AB#63574](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63574)
> fix(63574): Ata de retificação: Duplicação de devolução ao tesouro 

- hotfixes.md
- package.json
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
Corrige bug: [AB#63574](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63574)
> hotfix(1.30.1)

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ArquivosDeReferencia/TabsArquivosDeReferencia.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
- src/componentes/dres/PrestacaoDeContas/ModalDeleteAjusteSaldoPC.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/services/dres/PrestacaoDeContas.service.js
Esse PR:
- Altera layout do bloco de extrato bancario
- Adiciona informações do extrato da UE
História: [AB#62450](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62450)
> feat(62450):  Solicitacao de ajuste saldo

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
- src/services/dres/PrestacaoDeContas.service.js
feat(62450)-parte-3 Ajustes de saldo
Esse PR:
- Resolve problemas ao trocar de aba das contas
História: [AB#62450](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62450)
> feat(62450)-parte-3 Ajustes de saldo

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/DevolucaoParaAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
- src/services/dres/PrestacaoDeContas.service.js
feat(62450)-ajustes-visuais
Esse PR:
- Realiza ajustes visuais
- Adiciona parametro de analise ao carregar analises de contas
> feat(62450)-ajustes-visuais

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosEmExtratosBancarios.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabsAjustesEmExtratosBancarios.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/services/dres/PrestacaoDeContas.service.js
Esse PR altera a página de resumo de acertos para apresentar as solicitações de acerto em informações de extrato bancário.
História: [AB#62548](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62548)
> feat(62548): Altera página de resumo de acertos - Parte 1

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/FiltrosConferenciaDeLancamentos.js
Esse PR: 
- Corrige label para Filtrar por intervalo de datas
História: [AB#55988](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55988)
> feat(55988): Acompanhamento PC: Novos filtros na conferência de lançamentos - Parte 02

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosEmExtratosBancarios.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/services/dres/PrestacaoDeContas.service.js
Esse PR altera a página de resumo de acertos para apresentar as solicitações de acerto em informações de extrato bancário.
História: [AB#62548](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62548)
> feat(62548): Altera página de resumo de acertos

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TabelaAprovadas/index.js
feat(57865): Inclusão de recomendacoes ata parecer tecnico
Esse PR:
- Adiciona recomendações a ata de parecer tecnico em tela
História: [AB#57865](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57865)
> feat(57865): Inclusão de recomendacoes ata parecer tecnico

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
feat(62450)-ajuste
Esse PR:
- Realiza ajuste na condição para mostrar valor zerado
> feat(62450)-ajuste

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/AnalisesDeContaDaPrestacao.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
História: [AB#63583](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63583)
> homolog(63583): Posição em Develop 13/05/2022 às 13:38

- README.md
- package.json
História: [AB#64695](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64695)
> docs(64695): Atualiza release notes 1.31.0

- src/componentes/dres/Diretoria/Atribuicoes/index.js
Esse PR: 
- Cria ação para retirar atribuições
História: [AB#46253](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46253)
> feat(46253): Atribuições por unidade: Criar ação para retirar atribuições

- src/componentes/dres/Diretoria/Atribuicoes/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ComentariosDeAnalise.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
Esse PR:
- Inclui validações e ajustes
História: [AB#55961](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55961)
> feat(55961): Acompanhamento PC: Remoção do bloco Cobrança da PC e revisão do bloco Comentários - Parte 02

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/Assinaturas/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TabelaAprovadas/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
feat(62580): Melhoriar ata parecer tecnico
Esse PR:
- Altera layout de exibição das tabelas
História: [AB#62580](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62580)
> feat(62580): Melhoriar ata parecer tecnico

- src/componentes/sme/PainelParametrizacoes/index.js
- src/rotas/index.js
Corrige o bug: [AB#64110](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64110)
> fix(64110): acesso fornecedores

- src/componentes/sme/PainelParametrizacoes/index.js
- src/rotas/index.js
Corrige: [AB#64110](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64110)
> fix(64110): O acesso e edição não está funcionando para a funcionalidade DRE Cadastro de Fornecedores

- hotfixes.md
- package.json
- src/componentes/sme/PainelParametrizacoes/index.js
- src/rotas/index.js
Corrige: [AB#64110](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64110)
> hotfix(1.31.1)

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ModalVisualizarArquivoDeReferencia.js
Corrige: [AB#64886](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64886)
> fix(64886): Não visualização e não realização do download dos extratos bancários

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaTransacoes/index.js
Corrige: [AB#65220](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/65220)
> hotfix(1.31.2)

- src/services/dres/RelatorioConsolidado.service.js
feat(60314): Altera formato arquivo
Esse PR:
- Altera extensao do arquivo
História: [AB#60314](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60314)
> feat(60314): Altera formato arquivo

- README.md
- package.json
História: [AB#66028](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66028)
> doc(66028)

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TabelaAprovadas/index.js
Esse PR:
- Efetua ajuste solicitado para exibir a lista de PCs Aprovadas em três colunas
História: [AB#62580](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62580)
> feat(62580): Ata de parecer tecnico: melhorias em tela

- src/componentes/dres/ValoresReprogramadosDre/TabelaValoresReprogramados.js
Esse PR:
- Altera tamanho das colunas da tabela
História: [AB#60461](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60461)
> feat(60461): Altera tamanho das colunas da tabela

- src/componentes/dres/RelatorioConsolidado/DemonstrativoDaExecucaoFisicoFinanceira.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/componentes/dres/ValoresReprogramadosDre/TabelaValoresReprogramados.js
História: [AB#67211](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67211)
> homolog(67211): Posição em Develop 20/06/2022 às 13:43h

- src/componentes/dres/ValoresReprogramadosDre/TabelaValoresReprogramados.js
- src/componentes/dres/ValoresReprogramadosDre/index.js
- src/services/dres/ValoresReprogramadosDre.service.js
Esse PR:
- Altera nome do endpoint chamado para listagem de valores reprogramados
- Altera template da tabela para saldo cheque e saldo cartao
História: [AB#60461](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60461)
> feat(60461)-parte-3: altera chamada ao endpoint de valores reprogramados

- src/componentes/Globais/EscolheUnidade/ListaDeUnidades.js
- src/componentes/Globais/EscolheUnidade/index.js
- src/componentes/Globais/SuporteAsUnidades/ModalConfirmaInicioSuporte.js
- src/componentes/Globais/SuporteAsUnidades/index.js
- src/services/auth.service.js
Esse PR implementar comportamento "Viabilizar acesso" (Parte 1) 
[X] Cria Modal de confirmação
[X] Implementa a chamada do endpoint de viabilização de acesso
[X] Implementa log-out sem confirmação após viabilização do acesso
História: [AB#62851](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62851)
> feat(62851): Suporte às Unidades: Viabilizar acesso de suporte - Parte 1

- src/componentes/Globais/SidebarLeft/getUrls.js
Esse PR:
Historia: [AB#53051](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53051)
> feat(53051) Altera posição de icone menus em sideBar

- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/componentes/dres/RelatorioConsolidado/TrilhaDeStatus.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/services/dres/RelatorioConsolidado.service.js
Esse PR:
- Refatora component trilha de status
- Adiciona novo status a trilha de status
- Altera estilo trilha de status
- Adiciona chamada da API ao novo endpoint
História: [AB#63304](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63304)
> feat(63304): Novo status publicado

- src/componentes/sme/ExtracaoDados/index.js
Esse PR:
História: [AB#53051](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53051)
> Feature/53051 Exportacoes dados altera datepicker

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
Corrige o bug: [AB#67882](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67882)
> fix(67882): Altera data pagamento para data documento

- hotfixes.md
- package.json
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
Corrige os bug: 
- [AB#67882](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67882)
- [AB#65722](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/65722)
> hotfix(1.32.1)

- src/componentes/Globais/GestaoDePerfis/index.js
Esse PR:
História: [AB#66363](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66363)
> feat(66363): Suporte às Unidades: Exibir ícone de acesso suporte

- src/componentes/dres/RelatorioConsolidado/Lauda.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/services/dres/Laudas.service.js
- src/utils/ValidacoesAdicionaisFormularios.js
feat(64958): Geração de laudas no momento da publicação
Esse PR:
- Refatora component de Lauda
- Adiciona chamada a API para consultar as laudas do periodo
- Adiciona botão para realizar download da lauda
História: AB#64658
> feat(64958): Geração de laudas no momento da publicação

- src/componentes/dres/RelatorioConsolidado/index.js
Esse PR:
- Remove dependencia useffect 
- Remove bloco else desnecessario
História: [AB#64958](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64958)
> feat(64958)-parte-2: Remove dependencia useeffect

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/FiltrosConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/services/mantemEstadoAcompanhamentoDePc.service.js
Esse PR:
História: [AB#66783](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66783)
> feat(66783) Ajusta todos os estatos provido pelo local storage.

- src/componentes/Globais/MedidorForcaSenha/textoValidacaoSenha.js
Esse PR:
- Alterar o componente que exibe os critérios de validação de senha para incluir texto referente ao requisito de ser diferente das 5 últimas senhas usadas.
História: [AB#66657](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66657)
> feat(66657) Altera texto validação de senhas add 5 últimas

- src/componentes/Globais/Dashborard/index.js
- src/componentes/Globais/MedidorForcaSenha/textoValidacaoSenha.js
[AB#68749](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/68749)
> Posição de Develop em 19/07/2022 14:53

- src/componentes/Globais/EdicaoDeSenha/FormRedefinirSenha/index.js
Esse PR:
- Altera o formulário de redefinição de senha para exibir na íntegra a mensagem de erro retornada pela API.
> feat(66657) Altera tratamento de erro do FormRedefinirSenha

- src/componentes/Globais/EdicaoDeSenha/FormRedefinirSenha/index.js
Esse PR:
- Altera o formulário de redefinição de senha para exibir na íntegra a mensagem de erro retornada pela API.
Continuação (Parte 3)
> feat(66657) Altera tratamento de erro do FormRedefinirSenha - Parte 3

- src/componentes/Globais/ValoresReprogramados/ValoresReprogramadosFormFormik.js
- src/componentes/Globais/ValoresReprogramados/index.js
feat(60462)-ajuste-linha-tabela
Esse PR:
- Realiza ajuste em rowspan
História: [AB#60462](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60462)
> feat(60462)-ajuste-linha-tabela

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TopoComBotoes/index.js
- src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
feat(63318)-parte-2 ajuste modal
Esse PR:
- Realiza ajuste na condição de exibir modal ao publicar
História: [AB#63318](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63318)
> feat(63318)-parte-2 ajuste modal

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/scss/rowExpansionTable.scss
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/scss/tagInformacaoTemplate.scss
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/useRowExpansionDespesaTemplate.js
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/useRowExpansionReceitaTemplate.js
Esse PR:
História: [AB#66809](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66809)
> feat(66809) Conferência de lançamentos: Detalhamento do lançamento: Mudanças de estilo

- src/componentes/Globais/ValoresReprogramados/ValoresReprogramadosFormFormik.js
feat(60462)-parte-3 adiciona classe tr.
Esse PR:
- Adiciona classe as trs
- Remove icone coluna associação
História: [AB#60462](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60462)
> feat(60462)-parte-3 adiciona classe tr

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TabelaTransacoes/index.js
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/scss/rowExpansionTable.scss
Esse PR:
História: [AB#66783](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66783)
> feat de ajuste em tr, e adicionei o retorno exato do elemento HTML

- README.md
- package.json
[AB#70164](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/70164)
> docs(1.34): Release Notes

- src/componentes/dres/RelatorioConsolidado/DemonstrativoDaExecucaoFisicoFinanceira.js
- src/componentes/dres/RelatorioConsolidado/relatorio-consolidado.scss
Esse PR:
- Implementa geração de relatório consolidado DRE único para todas as contas
História: [AB#67941](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67941)
> feat(67941): Relatório consolidado: Parte 07a - Demonstrativo da execução físico-financeira único com todas as contas

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/Assinaturas/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/TabelaAprovadas/index.js
- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
- src/services/dres/AtasParecerTecnico.service.js
Esse PR:
- Altera Ata de Parecer Técnico em tela para exibir apenas PCs do consolidado
História: [AB#70099](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/70099)
> feat(70099): Relatório consolidado: Parte 10a - Ata em tela: Eliminar seções por conta e exibir apenas PCs do consolidado

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/FormularioAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/DetalharAcertosDocumentos/index.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/services/dres/PrestacaoDeContas.service.js
feat(65959) Agrupar tipos de acerto de documento por categoria
Esse PR:
- Exibe tipos de documento agrupados por categoria
- Exibe mensagem de acordo com categoria
História: [AB#65959](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/65959)
> feat(65959) Agrupar tipos de acerto de documento por categoria

- src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosLancamentos/TabelaLancamentos.js
Esse PR:
História: [AB#48777](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/48777)
> feat(48777) ajuste em css na tabela de lançamentos.

- src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosLancamentos/TabelaLancamentos.js
Esse PR:
História: [AB#48777](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/48777)
> feat(48777) Ajusta return de categoria caso seja null.

- src/componentes/dres/RelatorioConsolidado/AtaParecerTecnico/VisualizacaoAtaParecerTecnico/index.js
- src/componentes/dres/RelatorioConsolidado/DemonstrativoDaExecucaoFisicoFinanceira.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoApuracao/index.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/rotas/index.js
- src/services/dres/RelatorioConsolidado.service.js
Esse PR:
- Inicia a leitura dos dados para nova consulta do relatório consolidado em tela
História: [AB#70107](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/70107)
> feat(70107): Relatório consolidado: Parte 11 - Nova consulta do relatório em tela - Parte 01

- src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/ModalFormDocumento.js
Esse PR:
História: [AB#48779](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/48779)
> feat(48779) Ajuste botão disabled para iniciar com o status true

- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/index.js
- src/componentes/sme/Parametrizacoes/PrestacaoContas/TiposAcertosDocumentos/ModalFormDocumento.js
Esse PR:
História: [AB#48779](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/48779)
> feat(48779) Altera disabled para useEffect com useState

- src/componentes/Globais/ValoresReprogramados/BarraStatus.js
- src/componentes/Globais/ValoresReprogramados/Botoes.js
- src/componentes/Globais/ValoresReprogramados/Cabecalho.js
- src/componentes/Globais/ValoresReprogramados/TextoExplicativoDaPagina.js
- src/componentes/Globais/ValoresReprogramados/ValoresReprogramadosFormFormik.js
- src/componentes/Globais/ValoresReprogramados/index.js
- src/componentes/Globais/ValoresReprogramados/valores-reprogramados.scss
- src/componentes/dres/ValoresReprogramadosDre/index.js
- src/services/ValoresReprogramados.service.js
- src/utils/Modais.js
feat(70472)-parte-dois: Valores reprogramados ajustes diversos
Esse PR:
- Realiza ajustes de layout
- Adiciona bloco para texto explicativo
- Adiciona loading
História: [AB#70472](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/70472)
> feat(70472)-parte-dois: Valores reprogramados ajustes diversos

- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoEmTela/index.js
Esse PR:
- Implementa o loading no carregamento de informações
História: [AB#70107](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/70107)
> feat(70107): Ajusta funcionamento do loading

- src/componentes/dres/RelatorioConsolidado/DemonstrativoDaExecucaoFisicoFinanceira.js
Remove SplitButton que foi substituido por botão simples.
> feat(70107): Remove splitbutton

- src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/services/dres/RelatorioConsolidado.service.js
Esse PR: 
- Inicia alterações Consolidado de Publicações Parciais
História: [AB#63342](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63342)
> feat(63342): Relatório consolidado: Parte 08 - Consolidado de publicações parciais

- src/componentes/dres/RelatorioConsolidado/index.js
- src/services/dres/RelatorioConsolidado.service.js
Esse PR:
- Recupera informações sobre o relatorio consolidado da publicacao parcial
História: [AB#63342](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63342)
> feat(63342): Relatório consolidado: Parte 08 - Consolidado de publicações parciais - Parte 02

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosDocumentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/services/dres/PrestacaoDeContas.service.js
Esse PR:
História: [AB#67174](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67174)
> feat(67174) Atualização do status acertos documentos

- src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoEmTela/TabelaExecucaoFinanceira.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/services/auth.service.js
- src/services/visoes.service.js
Esse PR:
- Realiza melhorias em Relatorio Consolidado apos testes
História: [AB#72198](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72198)
> feat(72198): Relatório consolidado - Demonstrativo: melhorias pós testes

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
Esse PR:
História: [AB#72520](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72520)
> fix(72520) ajuste em detalhamento se não existir

- src/componentes/dres/Diretoria/Comissoes/index.js
fix(71868)-comissoes: Sistema permite cadastro de membro duplicado:
Esse PR:
- Exibe mensagem de erro caso o usuario tente duplicar um membro de comissao
História: [AB#71868](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/71868)
> fix(71868)-comissoes: Sistema permite cadastro de membro duplicado

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotaoAcertosLancamentosDevolucaoAoTesouro.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotoesDetalhesParaAcertosDeCategorias.scss
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/LinkCustom.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/RetornaSeTemPermissaoEdicaoAjustesLancamentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosDocumentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/componentes/escolas/Associacao/DadosDaAssociacao/index.js
Esse PR:
- Implementa Interface, Botão e comportamento para ajustes em Devolucao ao Tesouro
História: [AB#57812](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57812)
> feat(57812): Análise da DRE: Acertos: Detalhes de realização para acertos de categoria "Devolução ao tesouro" em lançamentos

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/Cabecalho.js
Esse PR:
- Ajusta texto em campo do frontend.
História: [AB#72201](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72201)
> feat(72201) texto relatorio consolidado front pre prod

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotaoAcertosLancamentosEdicaoGasto.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotoesDetalhesParaAcertosDeCategorias.scss
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/LinkCustom.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/componentes/dres/RelatorioConsolidado/TrilhaDeStatus.js
Esse PR:
- Inclui ajustes lancamentos - edicao de gasto
História: [AB#67644](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67644)
> feat(67644): Análise da DRE: Acertos: Detalhes de realização para acertos de categoria "Edição do lançamento" em Gastos

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotaoAcertosLancamentosEdicaoCredito.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/LinkCustom.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/index.js
- src/componentes/Globais/GestaoDePerfis/index.js
Esse PR:
- Inclui Botao Acertos em Lancamento - Crédito
História: #AB67645
> feat(67645): Análise da DRE: Acertos: Detalhes de realização para acertos de categoria "Edição do lançamento" em Créditos

- src/componentes/Globais/DevolucaoAoTesouroAjuste/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotaoAcertosLancamentosDevolucaoAoTesouro.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/LinkCustom.js
- src/componentes/escolas/Associacao/DadosDaAssociacao/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
- src/rotas/index.js
- src/services/dres/PrestacaoDeContas.service.js
Esse PR:
História: [AB#57812](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57812)
> Feat(57812) formulario devolucao tesouro

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TopoComBotoes.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/index.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormDespesaImposto.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/cadastro-de-despesas.scss
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- src/paginas/escolas/Despesas/EdicaoDeDespesa/index.js
- src/services/escolas/Despesas.service.js
- src/utils/ValidacoesAdicionaisFormularios.js
feat(67644): reabertura seletiva edicao de lancamentos
Esse PR:
- Possibilita a edição de um gasto mesmo com o periodo fechado
- Altera logica do botão voltar
- Adiciona chamada ao endpoint de despesa atualizada
História: [AB#67644](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67644)
> feat(67644): reabertura seletiva edicao de lancamentos

- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
feat(67644)-parte-2: ajuste endpoint tabelas
Esse PR:
- Realiza ajuste na chamada do endpoint tabelas
História: [AB#67644](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67644)
> feat(67644)-parte-2: ajuste endpoint tabelas

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
feat(67644)-parte-tres: Ajuste devolução PC
Esse PR:
- Realiza ajuste na captura dos parametros necessários para devolução da PC
História: [AB#67644](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67644)
> feat(67644)-parte-tres: Ajuste devolução PC

- src/componentes/Globais/DevolucaoAoTesouroAjuste/index.js
> feat(57812) Ajuse em data, valor, e disabled button

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotaoAcertosLancamentosEdicaoGasto.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotaoAcertosLancamentosExclusaoGasto.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/index.js
Esse PR:
- Inclui botão exclusao lancamentos gastos
História: [AB#67646](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67646)
> feat(67646): Análise da DRE: Acertos: Detalhes de realização para acertos de categoria "Exclusão do lançamento", em Gastos

- src/componentes/Globais/DevolucaoAoTesouroAjuste/index.js
Esse PR: 
História: [AB#57812](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57812)
> Feat(57812) ajuste devolucao tesouro

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
feat(67648): Reabertura seletiva ajustes externos
Esse PR:
- Adiciona mensagem quando algum dos acertos for da categoria de ajustes externos
História: [AB#67648](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67648)
> feat(67648): Reabertura seletiva ajustes externos

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotoesDetalhesParaAcertosDeCategorias.scss
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosDocumentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/services/dres/PrestacaoDeContas.service.js
Esse PR:
Lançamento
Documento
História: [AB#67649](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67649)
> Feat(67649) esclarecimentos solicitados

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/LinkCustom.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/index.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroFormFormik.js
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- src/services/escolas/Despesas.service.js
- src/utils/ValidacoesAdicionaisFormularios.js
feat(67646)-exclusao-lancamento: Rebertura seletiva
Esse PR:
- Permite acesso ao formulario de despesas em modo de exclusão
História: [AB#67646](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67646)
> feat(67646)-exclusao-lancamento: Rebertura seletiva

- src/componentes/escolas/Despesas/CadastroDeDespesas/cadastro-de-despesas.scss
feat(67646)-parte-2: ajuste css
Esse PR:
- Realiza ajuste no css para desabilitar botão
História: [AB#67646](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67646)
> feat(67646)-parte-2: ajuste css

- src/componentes/Globais/CardsDevolucoesParaAcertoDaDre/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TabsConferenciaAtualHistorico.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
Esse PR:
- Cria Trigger Click em TabsConferenciaAtualHistorico para controlar exibição das abas Conferência atual e Histórico
História: [AB#72730](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72730)
> fix(72730): Acompanhamento PC: Resumo de acertos - Parte 02

- src/componentes/Globais/CardsDevolucoesParaAcertoDaDre/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TabsConferenciaAtualHistorico.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
Esse PR:
- Cria Trigger Click em TabsConferenciaAtualHistorico para controlar exibição das abas Conferência atual e Histórico
História: [AB#72730](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72730)
> fix(72730) Acompanhamento PC: Resumo de acertos - Parte 02

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/index.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/paginas/escolas/Despesas/EdicaoDeDespesa/index.js
feat(67646): Reabertura seletiva exlusao gasto
Esse PR:
- Adiciona botão para acessar formulario de despesa quando "exclusao despesa"
- Altera ordem dos serviços chamados quando o formulario é acessado pela reabertura seletiva
- Altera titulo da pagina quando exclusão
- Bloqueia campos de despesa quando o usuário pode apenas visualizar
História: [AB#67646](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67646)
> feat(67646): reabertura seletiva exlusao gasto

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/index.js
- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/objetoColunasDinamicas.js
Esse PR:
Historia [AB#72442](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72442)
> fix(72442) Ajusta visões de status da tabela

- src/componentes/dres/PrestacaoDeContas/ListaPrestacaoDeContas/objetoColunasDinamicas.js
Esse PR:
Historia [AB#72442](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72442)
> fix(72442) Inseri header ações em tabela PC

- src/componentes/Globais/CardsDevolucoesParaAcertoDaDre/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TabsConferenciaAtualHistorico.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
História: [AB#72730](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72730)
> Fix(72730) Corrige loading em resumo dos recursos

- src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/services/escolas/Receitas.service.js
feat(67645): Reabertura seletiva, edição de créditos
Esse PR:
- Remove regra de periodo fechado quando edição de créditos através da analise DRE
- Adiciona chamada a API para marcar lançamento como atualizado
- Altera comportamento ao voltar para pagina anterior ao salvar
História: [AB#67645](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67645)
> feat(67645): Reabertura seletiva, edição de créditos

- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/componentes/dres/RelatorioConsolidado/TrilhaDeStatus.js
- src/services/dres/RelatorioConsolidado.service.js
Esse PR:
- Implementa melhorias no demonstrativo do relatório consolidado
História: [AB#72907](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72907)
> feat(72907): Relatório consolidado: Demonstrativo - melhorias

- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/componentes/dres/RelatorioConsolidado/TrilhaDeStatus.js
- src/services/dres/RelatorioConsolidado.service.js
História: [AB#72907](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72907)
> feat(72907): Implementa melhorias no demonstrativo do relatório consolidado

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/BotaoAcertosLancamentosExclusaoCredito.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/index.js
Esse PR:
- Implementa botão de exclusão de lançamento do tipo crédito
História: [AB#67647](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67647)
> feat(67647): Análise da DRE: Acertos: Detalhes de realização para acertos de categoria Exclusão do lançamento em Créditos

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategoriasDocumentos/BotaoAcertoDocumentoInclusaoGasto.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategoriasDocumentos/LinkCustom.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategoriasDocumentos/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
Esse PR: 
-  Inclui botão inclusão de gasto em documentos
História: [AB#67652](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67652)
> feat(67652): Análise da DRE: Acertos: Detalhes de realização para acertos de categoria Inclusão de gasto em documentos

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategoriasDocumentos/BotaoAcertoDocumentoInclusaoCredito.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategoriasDocumentos/index.js
Esse PR:
- Implementa botão inclusão de crédito em ajustes de documentos
História: [AB#67651](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67651)
> feat(67651): Análise da DRE: Acertos: Detalhes de realização para acertos de categoria Inclusão de crédito em documentos

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/DevolucoesAoTesouro/InformacoesDevolucaoAoTesouro.js
Corrige [AB#74773](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74773)
> fix(74773): Corrige página dev. tesouro vazia em ata retificação

- README.md
- package.json
História: [AB#74909](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74909)
> feat(74909): Atualiza Release Notes 1.34.0

- src/componentes/escolas/GeracaoAtaRetificadora/BoxAtaRetificadora/index.js
- src/componentes/escolas/GeracaoDaAta/GeracaoAtaApresentacao/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TopoComBotoes/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/index.js
Esse PR:
História: [AB#74394](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74394)
> Feat(74394) Bloqueia edicao atas front

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/TabelaConferenciaDeLancamentos.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
feat(74431): Marcar lançamento como correto
Esse PR:
- Altera regra para habilitas a opção "marcar como correto" na seleção dos lançamentos
- Adiciona "uuid" e "copiado" ao payload da solicitação de acertos
História: [AB#74431](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74431)
> feat(74431): Marcar lançamento como correto

- src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/FormMarcarPublicacaoNoDiarioOficial.js
- src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
Esse PR:
- Inclui verificação de data e página de publicação preenchidas
História: [AB#74811](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74811)
> feat(74811): Relatório Consolidado: Incluir verificação da data e página da publicação

- src/componentes/escolas/PrestacaoDeContas/DemonstrativoFinanceiroPorConta/index.js
- src/componentes/escolas/PrestacaoDeContas/RelacaoDeBens/index.js
- src/componentes/escolas/PrestacaoDeContas/TopoSelectPeriodoBotaoConcluir.js
História [AB#74391](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74391)
> feat(74391): Altera exibição de prévia para PCs devolvidas

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/RelatorioAposAcertos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/services/escolas/PrestacaoDeContas.service.js
História: [AB#66783](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66783)
> Feat(73204) gerar relatorio apresentacao apos acertos

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/RelatorioAposAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/RelatorioDosAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TabsConferenciaAtualHistorico.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
feat(73288): PDF apos acerto final
Esse PR:
- Exibe bloco de relatório apos acertos em Resumo de acertos - histórico
História: [AB#73288](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73288)
> feat(73288): PDF apos acerto final

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
Esse PR:
História: [AB#74519](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74519)
> feat(74519) Ajusta mensagem de alerta em devolução ao tesouro.

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertosBasico.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertosDevolucaoAoTesouro.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/YupSignupSchemaDetalharAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
Esse PR:
História: [AB#75770](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/75770)
> Feat(75770) obrigatorio campos devolucao

- src/componentes/dres/RelatorioConsolidado/Lauda.js
feat(75110): Gerar lauda unica
Esse PR:
- Adiciona validação para exibir download de lauda unica ou laudas por conta
História: [AB#75110](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/75110)
> feat(75110): Gerar lauda unica

- src/paginas/SME/PrestacaoDeContas/RelatorioConsolidado/index.js
Esse PR:
História: [AB#72647](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72647)
> feat(72647) Altera nome do caminho da pasta

- src/componentes/Globais/ModalBootstrap/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentos.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/BotoesAvancarRetroceder/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Cabecalho/Cabecalho.scss
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Cabecalho/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentosRelatorios.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ResponsavelAnalise/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/TrilhaDeStatus/TrilhaDeStatusConcluida.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/TrilhaDeStatus/TrilhaDeStatusDevolvido.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/TrilhaDeStatus/TrilhaDeStatusEmAnalise.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/TrilhaDeStatus/TrilhaDeStatusNaoPublicada.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/TrilhaDeStatus/TrilhaDeStatusPublicada.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/TrilhaDeStatus/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/BarraDeStatus.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/index.js
- src/componentes/sme/Parametrizacoes/Estrutura/Acoes/VinculaAssociacoesAAcao/index.js
- src/rotas/index.js
- src/services/sme/PrestacaoDeConta.service.js
Esse PR:
História: [AB#72933](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72933)
> Feat(72933) visualizar relatorio consolidado front

- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoRelatoriosConsolidadosSmeListagem/Cabecalho.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoRelatoriosConsolidadosSmeListagem/FormFiltros.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoRelatoriosConsolidadosSmeListagem/ListaRelatorios.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoRelatoriosConsolidadosSmeListagem/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoRelatoriosConsolidadosSmeListagem/multiselect.scss
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/DashboardCard.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/dashboard.scss
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/index.js
- src/rotas/index.js
- src/services/sme/DashboardSme.service.js
feat(72650): Listagem relatórios consolidados
Esse PR:
- Cria página para visualizar listagem de relatorios consolidados
- Adiciona filtros a listagem
- Adiciona paginação a listagem
- Adiciona loading a listagem
História: [AB#72650](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72650)
> feat(72650): Listagem relatórios consolidados

- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Cabecalho/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentosRelatorios.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoRelatoriosConsolidadosSmeListagem/index.js
feat(72650)-parte-2: Ajustes
Esse PR:
- Altera rota para voltar a pagina de listagem
- Altera limpar filtros para limpar todos os status do input
História: [AB#72650](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72650)
> feat(72650)-parte-2: Ajustes

- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/DataSaldoBancario/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/TopoComBotoes/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/services/escolas/PrestacaoDeContas.service.js
fix(76087): Conciliação bancaria
Esse PR:
- Adiciona chamada ao endpoint para verificar se campos podem ser editados
História: [AB#76087](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76087)
> fix(76087): Conciliação bancaria

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/services/dres/PrestacaoDeContas.service.js
Esse PR:
[X] Altera a exibição abas de contas em lançamentos conforme retorno da API
História: [AB#76331](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76331)
> feat(r6.76331): Altera acompanhamento de PC

- src/componentes/Globais/DevolucaoAoTesouroAjuste/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosEmExtratosBancarios.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/index.js
Esse PR:
História: [AB#76333](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76333)
> feat(76333): Analise DRE melhorias diversas

- src/componentes/Globais/BarraMensagem/barraMensagem.scss
- src/componentes/Globais/BarraMensagem/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosLancamentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/useRowExpansionDespesaTemplate.js
- src/hooks/dres/PrestacaoDeContas/ConferenciaDeLancamentos/useRowExpansionReceitaTemplate.js
Esse PR:
História: [AB#76642](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76642)
> Feat(76642) Exibi tarja credito despesa inativa

- src/componentes/Globais/ModalBootstrap/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/ComentariosDeAnaliseSmeNotificados.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/FormikForm.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/ModalDeletarComentario.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/ModalEditarDeletarComentario.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/ModalNotificarComentario.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/index.js
- src/services/dres/PrestacaoDeContas.service.js
- src/services/sme/DashboardSme.service.js
feat(r7.74263)
Esse PR:
- Adiciona bloco de comentarios
- Adiciona chamadas a API
- Adiciona seleção de comentarios para notificar
- Permite reeodenar comentarios
História: [AB#74263](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74263)
> feat(r7.74263)

- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/FormikForm.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/index.js
Esse PR:
- Adiciona regra para edição de comentários
> feat(74263)-ajuste-permissao-leitura-comentarios

- src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
Esse PR:
História: [AB#77031](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/77031)
> Feat(77031) bloquear campo data credito

- src/componentes/Globais/SidebarLeft/getUrls.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/utils/Modais.js
Esse PR:
História: [AB#76653](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76653)
> feat(76653) Ajusta texto de modal e inclui novo texto no menu

- src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
esse PR:
História: [AB#77031](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/77031)
> feat(77031) Ajuste em campo de repasse.

- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/DevolucaoParaAcertos/ModalConfirmaDevolverParaAcerto.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/DevolucaoParaAcertos/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/index.js
- src/services/dres/RelatorioConsolidado.service.js
> feat(74698): Cria bloco devolução consolidado DRE

- src/componentes/escolas/GeracaoAtaRetificadora/BoxAtaRetificadora/index.js
- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TopoComBotoes/index.js
Esse PR:
- Altera regra para bloquear botoes de edição e geração das atas da associacao
História: [AB#76272](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76272)
> fix(76272): Bloqueio edição atas associação

- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/DevolucaoParaAcertos/index.js
- src/services/dres/RelatorioConsolidado.service.js
Muda o label da data e passa a enviar a data limite para o back.
> feat(74698): Altera bloco devolução consolidado DRE

- src/componentes/Globais/ModalBootstrap/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/BotoesAvancarRetroceder/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Cabecalho/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Comentarios/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/DevolucaoParaAcertos/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ResponsavelAnalise/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoRelatoriosConsolidadosSmeListagem/FormFiltros.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoRelatoriosConsolidadosSmeListagem/ListaRelatorios.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoRelatoriosConsolidadosSmeListagem/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/dashboard.scss
- src/services/sme/PrestacaoDeConta.service.js
feat(r7.74208): Relatorio SME status em analise
Esse PR:
- Trata visibilidade dos botoes de acordo com retorno da API
- Trata habilitação dos botoes de acordo com o status do relatorio e regras de cada status
- Trata ação botões avançar e retroceder
- Adiciona modais de confirmação
- Adiciona loading entre trocas de status
História: [AB#74208](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74208)
> feat(r7.74208): Relatorio SME status em analise

- src/services/dres/RelatorioConsolidado.service.js
Corrige o formato da data limite de devolução no payload de devolução de um consolidado DRE.
[AB#74698](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74698)
> feat(74698): Corrige payload devolução consolidado

- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/Cabecalho/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/DevolucaoParaAcertos/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/index.js
feat(r7.74209) relatorio sme status devolvido para acertos
Esse PR:
- Permite usuario analisar o relatório após devolução
- Realiza ajustes de textos
História: [AB#74209](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74209)
> feat(r7.74209) relatorio sme status devolvido para acertos

- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/BotoesAvancarRetroceder/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentosRelatorios.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ResponsavelAnalise/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/index.js
Esse PR:
- Ajusta comportamento botão Concluir Analise
> feat(74208): Análise dos Relatórios Consolidados das DRE's: Visualizar Relatório Consolidado - Status: Em análise

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosEmExtratosBancarios.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabsAjustesEmExtratosBancarios.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/componentes/escolas/PrestacaoDeContas/prestacao-de-contas.scss
Esse PR:
- Implementa navegação entre conciliação bancaria e analise da DRE
História: [AB#77618](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/77618)
> feat(77618): Conciliação Bancária: Incluir opção Voltar que retorne para a tela anterior

- src/componentes/dres/RelatorioConsolidado/DemonstrativoDaExecucaoFisicoFinanceira.js
- src/componentes/dres/RelatorioConsolidado/PublicarDocumentos.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoApuracao/index.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoEmTela/JustificativaDiferenca.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoEmTela/TabelaExecucaoFinanceira.js
- src/componentes/dres/RelatorioConsolidado/RelatorioConsolidadoEmTela/index.js
- src/componentes/dres/RelatorioConsolidado/haDiferencaPrevisaoExecucaoRepasse.js
- src/componentes/dres/RelatorioConsolidado/index.js
- src/utils/Modais.js
Esse PR:
História: [AB#77616](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/77616)
> feat(77616) finaliza ediçoẽs de justificativa de relatório consolidado.

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
História [AB#79389](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79389)
> Feat(79389) altera mensagem publicada

- src/componentes/Globais/Cabecalho/index.js
- src/componentes/Globais/CardsDevolucoesParaAcertoDaDre/index.js
- src/componentes/Globais/DevolucaoAoTesouroAjuste/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDocumentos/TabelaAcertosDocumentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDocumentos/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/TabelaAcertosLancamentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TabsConferenciaAtualHistorico.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/index.js
- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/index.js
- src/componentes/escolas/AnaliseDre/index.js
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/rotas/index.js
- src/services/auth.service.js
- src/services/mantemEstadoAnaliseDre.service.js
- src/services/visoes.service.js
[AB#79488](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79488)
> Update homolog 02 dez manha

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDocumentos/TabelaAcertosDocumentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/TabelaAcertosLancamentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/services/dres/PrestacaoDeContas.service.js
Esse PR:
- Ajusta mensagem lancamentos e documentos na Analise DRE
História: [AB#77703](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/77703)
> feat(77703): Análise DRE: Ajustar mensagem exibida em Acertos dos lançamentos e documentos quando não existe acerto

- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/TopoComBotaoVoltar.js
Implementa a verificação de pendências de ajustes para permitir ou não ir para a conclusão de PC.
[AB#78456](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/78456)
> feat(78456): Implementa verificação pendência

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDocumentos/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
feat(r6.77138)-parte-2
Esse PR:
- Realiza ajuste para manter estado da pagina quando alterar status realizacao
História: [AB#77138](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/77138)
> feat(r6.77138)-parte-2

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosEmExtratosBancarios.js
fix(79379)-analise-dre
Esse PR:
- Escolhe corretamente periodo e conta em conciliação bancaria quando origem é a analise dre
História: [AB#79379](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79379)
> fix(79379)-analise-dre

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosEmExtratosBancarios.js
fix(79379)-analise-dre
Esse PR:
Escolhe corretamente periodo e conta em conciliação bancaria quando origem é a analise dre
> fix(79379): analise dre opcao ir para conciliacao bancaria

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosEmExtratosBancarios.js
- src/componentes/Globais/SidebarLeft/getUrls.js
- src/componentes/Globais/SidebarLeft/index.js
- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/TopoComBotaoVoltar.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/componentes/escolas/PrestacaoDeContas/index.js
- src/context/Sidebar/index.js
- src/services/SideBarLeft.service.js
fix(79379): Analise DRE, itens do menu
Esse PR:
- Seleciona corretamente item do menu quando usuário apertar em algum botão da analise dre que direciona para outra pagina
- Adiciona novo estado ao context de SideBar
- Adiciona condição com o novo estado do context ao menu
História: [AB#79379](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79379)
> fix(79379): Analise DRE, itens do menu

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertosDevolucaoAoTesouro.js
fix(80934): Incluir acerto dev tesouro
Esse PR:
Corrige liberação do botão salvar quando acerto de devolução ao tesouro
> fix(80934): Incluir acerto dev tesouro

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/LinkCustom.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- src/componentes/escolas/Receitas/Formularios/index.js
fix(80955): Botão deletar em credito e despesa
Esse PR:
- Ajusta condição para exibir botão deletar em créditos
- Ajusta condição para exibir botão deletar em gastos
História: [AB#80955](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80955)
> fix(80955): Botão deletar em credito e despesa

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/LinkCustom.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- src/componentes/escolas/Receitas/Formularios/index.js
fix(80955): Botão deletar em credito e despesa
Esse PR:
- Ajusta condição para exibir botão deletar em créditos
- Ajusta condição para exibir botão deletar em gastos
> fix(80955): botao deletar credito despesa

- src/componentes/Globais/CardsDevolucoesParaAcertoDaDre/SelectAnalisesDePcDevolvidas.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/ModalAdicionarAcertosDocumentos.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentosRelatorios.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/CardsInfoDevolucaoSelecionada/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/RelatorioAposAcertos/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/RelatorioDosAcertos/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/TabelaConferenciaDeDocumentosRelatorios/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/TabsConferencia/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/TopoComBotoes/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/VisualizaDevolucoes/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/index.js
História [AB#74264](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74264)
> Feat(74264) Histórico conferencia front

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/BotoesDetalhesParaAcertosDeCategorias/LinkCustom.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/TabelaAcertosEmExtratosBancarios.js
- src/componentes/Globais/SidebarLeft/getUrls.js
- src/componentes/Globais/SidebarLeft/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/FormularioAcertosDevolucaoAoTesouro.js
- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/TopoComBotaoVoltar.js
- src/componentes/escolas/Despesas/CadastroDeDespesas/CadastroForm.js
- src/componentes/escolas/Despesas/metodosAuxiliares.js
- src/componentes/escolas/PrestacaoDeContas/DetalheDasPrestacoes/index.js
- src/componentes/escolas/PrestacaoDeContas/index.js
- src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/ModalAdicionarAcertosDocumentos.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/TabelaConferenciaDeDocumentosRelatorios.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/CardsInfoDevolucaoSelecionada/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/RelatorioAposAcertos/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/TabelaConferenciaDeDocumentosRelatorios/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/TabsConferencia/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/TopoComBotoes/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/VisualizaDevolucoes/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/index.js
- src/context/Sidebar/index.js
- src/services/SideBarLeft.service.js
História: [AB#80734](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80734)
> Posição do front em 13/12/2022 12:45

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
- src/store/reducers/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/actions.js
- src/store/reducers/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/reducer.js
fix(80950): Botão editar acertos redirecionar para ver resumo
Esse PR:
- Adiciona origem ao redux de detalhar acertos
- Adiciona validação de origem ao clicar no botão voltar
História: AB#80950
> fix(80950): Botão editar acertos redirecionar para ver resumo

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
- src/componentes/escolas/Receitas/Formularios/ReceitaFormFormik.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/store/reducers/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/actions.js
- src/store/reducers/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/reducer.js
fix(80950): Botão editar acertos redirecionar para ver resumo
Esse PR:
Adiciona origem ao redux de detalhar acertos
Adiciona validação de origem ao clicar no botão voltar
> fix(80950): editar acerto voltar para ver resumo

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
- src/context/Notificacoes/index.js
- src/rotas/index.js
fix(80957): Modal alerta devolucao
Esse PR:
- Altera regra para exibir modal de devolucao de acertos
História: [AB#80957](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80957)
> fix(80957): Modal alerta devolucao

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
- src/context/Notificacoes/index.js
- src/rotas/index.js
fix(80957): Modal alerta devolucao
Esse PR:
Altera regra para exibir modal de devolucao de acertos
> Resolve conflito 80957

- src/componentes/sme/AcompanhamentoPcsSme/DashboardCard.js
- src/componentes/sme/AcompanhamentoPcsSme/ResumoPorDre.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/BarraDeStatusPorDiretoria.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/BarraTotalAssociacoes.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/DashboardCardPorDiretoria.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/index.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/style.scss
- src/paginas/SME/PrestacaoDeContas/AcompanhamentoPcsSmePorDre/index.js
- src/rotas/index.js
- src/services/dres/RelatorioConsolidado.service.js
[x] Nova página e rota
[x] Chamada recebendo o uuid da DRE, o período
[x] Seleção de período (já trazendo o período passado por parâmetros)
[x] Exibir barra de total de unidades
[x] Exibir os cards (usar mesmo componente da página anterior) 
História [AB#28853](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/28853)
> Feat(28853) resumo dre detalhe

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
- src/componentes/sme/AcompanhamentoPcsSme/ResumoPorDre.js
- src/componentes/sme/AcompanhamentoPcsSme/index.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/BarraDeStatusPorDiretoria.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/BarraTotalAssociacoes.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/DashboardCardPorDiretoria.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/index.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/style.scss
- src/context/Notificacoes/index.js
- src/paginas/SME/PrestacaoDeContas/AcompanhamentoPcsSmePorDre/index.js
- src/rotas/index.js
- src/services/dres/RelatorioConsolidado.service.js
- src/store/reducers/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/actions.js
- src/store/reducers/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/reducer.js
História: [AB#80734](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80734)
> Posição do front em 14/12/2022 13:15

- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/index.js
[AB#82073](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82073)
> feat(82073): Altera texto status em PCs devolvida_apresentada e devolvida_recebida

- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/TopoComBotaoVoltar.js
- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/index.js
[x] Incluir condição para exibição do botão baseada no status da PC já exibido na tela
HístoriaAB#80958
> feat(80958) Ajusta r6 onde colocamos o incluir acertos

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDocumentos/TabelaAcertosDocumentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDocumentos/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/TabelaAcertosLancamentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/index.js
- src/componentes/escolas/AnaliseDre/ConsultaDetalhamentoAnaliseDaDre/index.js
- src/componentes/escolas/Receitas/Formularios/index.js
- src/componentes/sme/AcompanhamentoPcsSme/ResumoPorDre.js
- src/componentes/sme/AcompanhamentoPcsSme/index.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/BarraDeStatusPorDiretoria.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/BarraTotalAssociacoes.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/DashboardCardPorDiretoria.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/index.js
- src/componentes/sme/AcompanhamentoPcsSmePorDre/style.scss
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/BarraDeStatus/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/ConferenciaDeDocumentos/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/DevolucaoParaAcertos/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEDetalhe/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/TabelaConferenciaDeDocumentosRelatorios/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/TopoComBotoes/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/index.js
- src/context/Notificacoes/index.js
- src/paginas/SME/PrestacaoDeContas/AcompanhamentoPcsSmePorDre/index.js
- src/rotas/index.js
- src/services/dres/RelatorioConsolidado.service.js
- src/store/reducers/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/actions.js
- src/store/reducers/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ConferenciaDeLancamentos/DetalharAcertos/reducer.js
> Feat(74210) visualizar relatorio consolidado

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
feat(74945): Acompanhamento de PC em retificacao
Esse PR:
- Cria metodo para bloquear retorno para em recebida quando PC esta retificada
História: [AB#74945](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74945)
> feat(74945): Acompanhamento de PC em retificacao

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/Cabecalho.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoRelatoriosConsolidadosSmeListagem/index.js
feat(80680): Incluir referencia retificacao
Esse PR:
- Cria estado para armazenar referencia da retificacao
- Adiciona filtro de retificacao
História: [AB#80680](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80680)
> feat(80680): Incluir referencia retificacao

- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/Cabecalho.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/index.js
História: [AB#74494](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74494)
> feat(74494) finaliza em retificação prestacaoConta

- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/RelatorioDosAcertos/index.js
- src/services/sme/AcompanhamentoSME.service.js
feat(74212): Gerar previa relatorio sme
Esse PR:
- Altera componente relatorio de acertos (ver resumo sme)
- Adiciona novos serviços para chamadas de API de geração do pdf
História: [AB#74212](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74212)
> feat(74212): Gerar previa relatorio sme

- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/RelatorioDosAcertos/index.js
- src/componentes/sme/AcompanhamentoRelatoriosConsolidadosSME/AcompanhamentoDeRelatorioConsolidadoSMEResumoAcertos/index.js
feat(74213): Relatorio sme final
Esse PR:
- Altera componente RelatorioAcertos para lidar com a aba de historico
História: [AB#74213](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74213)
> feat(74213): Relatorio sme final

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/TabelaAcertosLancamentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
feat(82939): Conferencia de lancamentos
Esse PR:
- Altera regra de seleção das checkbox
- Altera layout das checkbox
- Altera regra de exibição das opções após selecionar algum acerto
História: [AB#82939](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82939)
> feat(82939): Conferencia de lancamentos

- src/componentes/escolas/GeracaoDaAta/VisualizacaoDaAta/TopoComBotoes/index.js
História [AB#82942](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82942)
> feat(82942) Remove botão de devolução ao tesoro, na ata de retificação.

- .gitignore
- package-lock.json
Esse PR:
- Corrige versionamento de pacotes e dependências
História: [AB#83246](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83246)
> feat(83246): Corrige versionamento de pacotes e dependências

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDocumentos/TabelaAcertosDocumentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosDocumentos/index.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/TabelaAcertosLancamentos.js
- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
feat(82977): Conferencia de documentos
Esse PR:
Altera regra de seleção das checkbox
Altera layout das checkbox
Altera regra de exibição das opções após selecionar algum acerto
História: [AB#82977](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82977)
> feat(82977): Conferencia documentos

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/index.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ComentariosDeAnalise.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/GetComportamentoPorStatus.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/DevolverParaAcertos.js
- src/componentes/dres/PrestacaoDeContas/DetalhePrestacaoDeContas/ResumoDosAcertos/TopoComBotoes.js
- src/componentes/dres/PrestacaoDeContas/RetornaSeTemPermissaoEdicaoAcompanhamentoDePc.js
- src/componentes/dres/PrestacaoDeContas/prestacao-de-contas.scss
Esse PR:
- Implementa perfil de atualização em Acompanhamento de PC
História: [AB#42280](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42280)
> feat(42280): Acompanhamento de PC: Implementar perfil de acesso de atualização

- .gitignore
- package-lock.json
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js
[AB#82970](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82970)
> Update homolog 12 jan23

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/acertos-lancamentos.scss
- src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/InfoPublicacaoNoDiarioOficial.js
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/Cabecalho.js
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/Filtros.js
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/MotivoRetificacao.js
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/TabelaPcsEmRetificacao.js
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/TituloTabela.js
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js
- src/componentes/dres/RelatorioConsolidado/Retificar/index.js
- src/componentes/dres/RelatorioConsolidado/relatorio-consolidado.scss
- src/services/dres/RelatorioConsolidado.service.js
feat(83914): Desfazer retificacao
Esse PR:
- Adiciona novo bloco para desfazer retificacao
- Adiciona uma rota para o botão "editar retificacao"
- Trata os campos que não podem ser selecionados na tabela de PCs em retificacao
- Implementa acao de desfazer
História: [AB#83914](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83914)
> feat(83914): Desfazer retificacao

- src/componentes/Globais/ExibeAcertosEmLancamentosEDocumentosPorConta/AcertosLancamentos/acertos-lancamentos.scss
- src/componentes/dres/RelatorioConsolidado/MarcarPublicacaoNoDiarioOficial/InfoPublicacaoNoDiarioOficial.js
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/Cabecalho.js
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/Filtros.js
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/MotivoRetificacao.js
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/TabelaPcsEmRetificacao.js
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/TituloTabela.js
- src/componentes/dres/RelatorioConsolidado/RetificacaoRelatorioConsolidado/index.js
- src/componentes/dres/RelatorioConsolidado/Retificar/index.js
- src/componentes/dres/RelatorioConsolidado/relatorio-consolidado.scss
- src/services/dres/RelatorioConsolidado.service.js
História: [AB#83752](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83752)
> Posição de Develop em 26/01/2023 14:10

- src/componentes/Globais/Cabecalho/ModalNotificaErroConcluirPC.js
- src/componentes/Globais/Cabecalho/index.js
- src/componentes/Globais/SidebarLeft/index.js
- src/context/Notificacoes/index.js
- src/services/Notificacoes.service.js
Esse PR:
- Implementa monitoramento de PC
História: [AB#78971](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/78971)
> fix(78971) - Implementa monitoramento de PC

- src/componentes/dres/Associacoes/index.js
- src/services/dres/Associacoes.service.js
Esse PR:
- Corrigindo o tempo de resposta em pesquisa associação
História: [AB#84513](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/84513)
> fix(84513) Associação: Tempo de resultado de pesquisa 
